/*!
 * Knockout JavaScript library v3.5.3
 * (c) The Knockout.js team - http://knockoutjs.com/
 * License: MIT (http://www.opensource.org/licenses/mit-license.php)
 */

(function() {(function(p){var z=this||(0,eval)("this"),v=z.document,R=z.navigator,w=z.jQuery,G=z.JSON;w||"undefined"===typeof jQuery||(w=jQuery);(function(p){"function"===typeof define&&define.amd?define(["exports","require"],p):"object"===typeof exports&&"object"===typeof module?p(module.exports||exports):p(z.ko={})})(function(S,T){function K(a,c){return null===a||typeof a in X?a===c:!1}function Y(b,c){var d;return function(){d||(d=a.a.setTimeout(function(){d=p;b()},c))}}function Z(b,c){var d;return function(){clearTimeout(d);
d=a.a.setTimeout(b,c)}}function aa(a,c){c&&"change"!==c?"beforeChange"===c?this.pc(a):this.ib(a,c):this.qc(a)}function ba(a,c){null!==c&&c.s&&c.s()}function ca(a,c){var d=this.qd,e=d[t];e.ta||(this.Rb&&this.ob[c]?(d.uc(c,a,this.ob[c]),this.ob[c]=null,--this.Rb):e.I[c]||d.uc(c,a,e.K?{da:a}:d.$c(a)),a.La&&a.gd())}var a="undefined"!==typeof S?S:{};a.b=function(b,c){for(var d=b.split("."),e=a,f=0;f<d.length-1;f++)e=e[d[f]];e[d[d.length-1]]=c};a.L=function(a,c,d){a[c]=d};a.version="3.5.3";a.b("version",
a.version);a.options={deferUpdates:!1,useOnlyNativeEvents:!1,foreachHidesDestroyed:!1};var H;if("undefined"!==typeof trustedTypes)try{H=trustedTypes.createPolicy("knockout",{createHTML:function(a){return a},createScript:function(a){return a}})}catch(fa){}a.a=function(){function b(a,b){for(var c in a)f.call(a,c)&&b(c,a[c])}function c(a,b){if(b)for(var c in b)f.call(b,c)&&(a[c]=b[c]);return a}function d(a,b){a.__proto__=b;return a}function e(b,c,e,d){var l=b[c].match(n)||[];a.a.D(e.match(n),function(b){a.a.Pa(l,
b,d)});b[c]=l.join(" ")}var f=Object.prototype.hasOwnProperty,g={__proto__:[]}instanceof Array,h="function"===typeof Symbol,m={},k={};m[R&&/Firefox\/2/i.test(R.userAgent)?"KeyboardEvent":"UIEvents"]=["keyup","keydown","keypress"];m.MouseEvents="click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave".split(" ");b(m,function(a,b){if(b.length)for(var c=0,e=b.length;c<e;c++)k[b[c]]=a});var l={propertychange:!0},q;H||(q=v&&function(){for(var a=3,b=v.createElement("div"),c=
b.getElementsByTagName("i");b.innerHTML="\x3c!--[if gt IE "+ ++a+"]><i></i><![endif]--\x3e",c[0];);return 4<a?a:p}());var n=/\S+/g,r;return{Jc:["authenticity_token",/^__RequestVerificationToken(_.*)?$/],D:function(a,b,c){for(var e=0,d=a.length;e<d;e++)b.call(c,a[e],e,a)},A:"function"==typeof Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b)}:function(a,b){for(var c=0,e=a.length;c<e;c++)if(a[c]===b)return c;return-1},Mb:function(a,b,c){for(var e=0,d=a.length;e<d;e++)if(b.call(c,
a[e],e,a))return a[e];return p},Ra:function(b,c){var e=a.a.A(b,c);0<e?b.splice(e,1):0===e&&b.shift()},wc:function(b){var c=[];b&&a.a.D(b,function(b){0>a.a.A(c,b)&&c.push(b)});return c},Nb:function(a,b,c){var e=[];if(a)for(var d=0,l=a.length;d<l;d++)e.push(b.call(c,a[d],d));return e},lb:function(a,b,c){var e=[];if(a)for(var d=0,l=a.length;d<l;d++)b.call(c,a[d],d)&&e.push(a[d]);return e},Ob:function(a,b){if(b instanceof Array)a.push.apply(a,b);else for(var c=0,e=b.length;c<e;c++)a.push(b[c]);return a},
Pa:function(b,c,e){var d=a.a.A(a.a.bc(b),c);0>d?e&&b.push(c):e||b.splice(d,1)},Ca:g,extend:c,setPrototypeOf:d,Bb:g?d:c,P:b,Ia:function(a,b,c){if(!a)return a;var e={},d;for(d in a)f.call(a,d)&&(e[d]=b.call(c,a[d],d,a));return e},Ub:function(b){for(;b.firstChild;)a.removeNode(b.firstChild)},Zb:function(b){b=a.a.la(b);for(var c=(b[0]&&b[0].ownerDocument||v).createElement("div"),e=0,d=b.length;e<d;e++)c.appendChild(a.pa(b[e]));return c},Da:function(b,c){for(var e=0,d=b.length,l=[];e<d;e++){var k=b[e].cloneNode(!0);
l.push(c?a.pa(k):k)}return l},xa:function(b,c){a.a.Ub(b);if(c)for(var e=0,d=c.length;e<d;e++)b.appendChild(c[e])},Xc:function(b,c){var e=b.nodeType?[b]:b;if(0<e.length){for(var d=e[0],l=d.parentNode,k=0,f=c.length;k<f;k++)l.insertBefore(c[k],d);k=0;for(f=e.length;k<f;k++)a.removeNode(e[k])}},Wa:function(a,b){if(a.length){for(b=8===b.nodeType&&b.parentNode||b;a.length&&a[0].parentNode!==b;)a.splice(0,1);for(;1<a.length&&a[a.length-1].parentNode!==b;)a.length--;if(1<a.length){var c=a[0],e=a[a.length-
1];for(a.length=0;c!==e;)a.push(c),c=c.nextSibling;a.push(e)}}return a},Zc:function(a,b){7>q?a.setAttribute("selected",b):a.selected=b},Eb:function(a){return null===a||a===p?"":a.trim?a.trim():a.toString().replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Ud:function(a,b){a=a||"";return b.length>a.length?!1:a.substring(0,b.length)===b},vd:function(a,b){if(a===b)return!0;if(11===a.nodeType)return!1;if(b.contains)return b.contains(1!==a.nodeType?a.parentNode:a);if(b.compareDocumentPosition)return 16==(b.compareDocumentPosition(a)&
16);for(;a&&a!=b;)a=a.parentNode;return!!a},Tb:function(b){return a.a.vd(b,b.ownerDocument.documentElement)},kd:function(b){return!!a.a.Mb(b,a.a.Tb)},R:function(a){return a&&a.tagName&&a.tagName.toLowerCase()},Ac:function(b){return a.onError?function(){try{return b.apply(this,arguments)}catch(c){throw a.onError&&a.onError(c),c;}}:b},setTimeout:function(b,c){return setTimeout(a.a.Ac(b),c)},Gc:function(b){setTimeout(function(){a.onError&&a.onError(b);throw b;},0)},B:function(b,c,e){var d=a.a.Ac(e);
e=l[c];if(!a.options.useOnlyNativeEvents&&!e&&w)r||(r="function"==typeof w(b).on?"on":"bind"),w(b)[r](c,d);else if(!e&&"function"==typeof b.addEventListener)b.addEventListener(c,d,!1),a.a.J.oa(b,function(){b.removeEventListener(c,d)});else if("undefined"!=typeof b.attachEvent){var k=function(a){d.call(b,a)},f="on"+c;b.attachEvent(f,k);a.a.J.oa(b,function(){b.detachEvent(f,k)})}},Gb:function(b,c){if(!b||!b.nodeType)throw Error("element must be a DOM node when calling triggerEvent");var e;"input"===
a.a.R(b)&&b.type&&"click"==c.toLowerCase()?(e=b.type,e="checkbox"==e||"radio"==e):e=!1;if(a.options.useOnlyNativeEvents||!w||e)if("function"==typeof v.createEvent)if("function"==typeof b.dispatchEvent)e=v.createEvent(k[c]||"HTMLEvents"),e.initEvent(c,!0,!0,z,0,0,0,0,0,!1,!1,!1,!1,0,b),b.dispatchEvent(e);else throw Error("The supplied element doesn't support dispatchEvent");else if(e&&b.click)b.click();else if("undefined"!=typeof b.fireEvent)b.fireEvent("on"+c);else throw Error("Browser doesn't support triggering events");
else w(b).trigger(c)},f:function(b){return a.O(b)?b():b},bc:function(b){return a.O(b)?b.v():b},Fb:function(b,c,d){var l;c&&("object"===typeof b.classList?(l=b.classList[d?"add":"remove"],a.a.D(c.match(n),function(a){l.call(b.classList,a)})):"string"===typeof b.className.baseVal?e(b.className,"baseVal",c,d):e(b,"className",c,d))},Cb:function(b,c){var e=a.a.f(c);if(null===e||e===p)e="";var d=a.h.firstChild(b);!d||3!=d.nodeType||a.h.nextSibling(d)?a.h.xa(b,[b.ownerDocument.createTextNode(e)]):d.data=
e;a.a.Ad(b)},Yc:function(a,b){a.name=b;if(7>=q)try{var c=a.name.replace(/[&<>'"]/g,function(a){return"&#"+a.charCodeAt(0)+";"});a.mergeAttributes(v.createElement("<input name='"+c+"'/>"),!1)}catch(e){}},Ad:function(a){9<=q&&(a=1==a.nodeType?a:a.parentNode,a.style&&(a.style.zoom=a.style.zoom))},wd:function(a){if(q){var b=a.style.width;a.style.width=0;a.style.width=b}},Pd:function(b,c){b=a.a.f(b);c=a.a.f(c);for(var e=[],d=b;d<=c;d++)e.push(d);return e},la:function(a){for(var b=[],c=0,e=a.length;c<e;c++)b.push(a[c]);
return b},Ea:function(a){return h?Symbol(a):a},Zd:6===q,$d:7===q,W:q,Lc:function(b,c){for(var e=a.a.la(b.getElementsByTagName("input")).concat(a.a.la(b.getElementsByTagName("textarea"))),d="string"==typeof c?function(a){return a.name===c}:function(a){return c.test(a.name)},l=[],k=e.length-1;0<=k;k--)d(e[k])&&l.push(e[k]);return l},Nd:function(b){return"string"==typeof b&&(b=a.a.Eb(b))?G&&G.parse?G.parse(b):(new Function("return "+b))():null},hc:function(b,c,e){if(!G||!G.stringify)throw Error("Cannot find JSON.stringify(). Some browsers (e.g., IE < 8) don't support it natively, but you can overcome this by adding a script reference to json2.js, downloadable from http://www.json.org/json2.js");
return G.stringify(a.a.f(b),c,e)},Od:function(c,e,d){d=d||{};var l=d.params||{},k=d.includeFields||this.Jc,f=c;if("object"==typeof c&&"form"===a.a.R(c))for(var f=c.action,h=k.length-1;0<=h;h--)for(var g=a.a.Lc(c,k[h]),m=g.length-1;0<=m;m--)l[g[m].name]=g[m].value;e=a.a.f(e);var n=v.createElement("form");n.style.display="none";n.action=f;n.method="post";for(var q in e)c=v.createElement("input"),c.type="hidden",c.name=q,c.value=a.a.hc(a.a.f(e[q])),n.appendChild(c);b(l,function(a,b){var c=v.createElement("input");
c.type="hidden";c.name=a;c.value=b;n.appendChild(c)});v.body.appendChild(n);d.submitter?d.submitter(n):n.submit();setTimeout(function(){n.parentNode.removeChild(n)},0)}}}();a.b("utils",a.a);a.b("utils.arrayForEach",a.a.D);a.b("utils.arrayFirst",a.a.Mb);a.b("utils.arrayFilter",a.a.lb);a.b("utils.arrayGetDistinctValues",a.a.wc);a.b("utils.arrayIndexOf",a.a.A);a.b("utils.arrayMap",a.a.Nb);a.b("utils.arrayPushAll",a.a.Ob);a.b("utils.arrayRemoveItem",a.a.Ra);a.b("utils.cloneNodes",a.a.Da);a.b("utils.createSymbolOrString",
a.a.Ea);a.b("utils.extend",a.a.extend);a.b("utils.fieldsIncludedWithJsonPost",a.a.Jc);a.b("utils.getFormFields",a.a.Lc);a.b("utils.objectMap",a.a.Ia);a.b("utils.peekObservable",a.a.bc);a.b("utils.postJson",a.a.Od);a.b("utils.parseJson",a.a.Nd);a.b("utils.registerEventHandler",a.a.B);a.b("utils.stringifyJson",a.a.hc);a.b("utils.range",a.a.Pd);a.b("utils.toggleDomNodeCssClass",a.a.Fb);a.b("utils.triggerEvent",a.a.Gb);a.b("utils.unwrapObservable",a.a.f);a.b("utils.objectForEach",a.a.P);a.b("utils.addOrRemoveItem",
a.a.Pa);a.b("utils.setTextContent",a.a.Cb);a.b("unwrap",a.a.f);Function.prototype.bind||(Function.prototype.bind=function(a){var c=this;if(1===arguments.length)return function(){return c.apply(a,arguments)};var d=Array.prototype.slice.call(arguments,1);return function(){var e=d.slice(0);e.push.apply(e,arguments);return c.apply(a,e)}});a.a.g=new function(){var b=0,c="__ko__"+(new Date).getTime(),d={},e,f;a.a.W?(e=function(a,e){var f=a[c];if(!f||"null"===f||!d[f]){if(!e)return p;f=a[c]="ko"+b++;d[f]=
{}}return d[f]},f=function(a){var b=a[c];return b?(delete d[b],a[c]=null,!0):!1}):(e=function(a,b){var e=a[c];!e&&b&&(e=a[c]={});return e},f=function(a){return a[c]?(delete a[c],!0):!1});return{get:function(a,b){var c=e(a,!1);return c&&c[b]},set:function(a,b,c){(a=e(a,c!==p))&&(a[b]=c)},Vb:function(a,b,c){a=e(a,!0);return a[b]||(a[b]=c)},clear:f,Z:function(){return b++ +c}}};a.b("utils.domData",a.a.g);a.b("utils.domData.clear",a.a.g.clear);a.a.J=new function(){function b(b,c){var d=a.a.g.get(b,e);
d===p&&c&&(d=[],a.a.g.set(b,e,d));return d}function c(c){var e=b(c,!1);if(e)for(var e=e.slice(0),k=0;k<e.length;k++)e[k](c);a.a.g.clear(c);a.a.J.cleanExternalData(c);g[c.nodeType]&&d(c.childNodes,!0)}function d(b,e){for(var d=[],l,f=0;f<b.length;f++)if(!e||8===b[f].nodeType)if(c(d[d.length]=l=b[f]),b[f]!==l)for(;f--&&-1==a.a.A(d,b[f]););}var e=a.a.g.Z(),f={1:!0,8:!0,9:!0},g={1:!0,9:!0};return{oa:function(a,c){if("function"!=typeof c)throw Error("Callback must be a function");b(a,!0).push(c)},zb:function(c,
d){var f=b(c,!1);f&&(a.a.Ra(f,d),0==f.length&&a.a.g.set(c,e,p))},pa:function(b){a.u.G(function(){f[b.nodeType]&&(c(b),g[b.nodeType]&&d(b.getElementsByTagName("*")))});return b},removeNode:function(b){a.pa(b);b.parentNode&&b.parentNode.removeChild(b)},cleanExternalData:function(a){w&&"function"==typeof w.cleanData&&w.cleanData([a])}}};a.pa=a.a.J.pa;a.removeNode=a.a.J.removeNode;a.b("cleanNode",a.pa);a.b("removeNode",a.removeNode);a.b("utils.domNodeDisposal",a.a.J);a.b("utils.domNodeDisposal.addDisposeCallback",
a.a.J.oa);a.b("utils.domNodeDisposal.removeDisposeCallback",a.a.J.zb);(function(){var b=[0,"",""],c=[1,"<table>","</table>"],d=[3,"<table><tbody><tr>","</tr></tbody></table>"],e=[1,"<select multiple='multiple'>","</select>"],f={thead:c,tbody:c,tfoot:c,tr:[2,"<table><tbody>","</tbody></table>"],td:d,th:d,option:e,optgroup:e},g=8>=a.a.W;a.a.wa=function(c,e){var d;if(w)if(w.parseHTML)d=w.parseHTML(c,e)||[];else{if((d=w.clean([c],e))&&d[0]){for(var l=d[0];l.parentNode&&11!==l.parentNode.nodeType;)l=l.parentNode;
l.parentNode&&l.parentNode.removeChild(l)}}else{(d=e)||(d=v);var l=d.parentWindow||d.defaultView||z,q=a.a.Eb(c).toLowerCase(),n=d.createElement("div"),r;r=(q=q.match(/^(?:\x3c!--.*?--\x3e\s*?)*?<([a-z]+)[\s>]/))&&f[q[1]]||b;q=r[0];r="ignored<div>"+r[1]+c+r[2]+"</div>";"function"==typeof l.innerShiv?n.appendChild(l.innerShiv(r)):(g&&d.body.appendChild(n),n.innerHTML=H?H.createHTML(r):r,g&&n.parentNode.removeChild(n));for(;q--;)n=n.lastChild;d=a.a.la(n.lastChild.childNodes)}return d};a.a.Md=function(b,
c){var e=a.a.wa(b,c);return e.length&&e[0].parentElement||a.a.Zb(e)};a.a.fc=function(b,c){a.a.Ub(b);c=a.a.f(c);if(null!==c&&c!==p){if("string"!=typeof c){if("undefined"!==typeof trustedTypes&&trustedTypes.isHTML(c)){b.innerHTML=c;return}c=c.toString()}if(w)w(b).html(c);else for(var e=a.a.wa(c,b.ownerDocument),d=0;d<e.length;d++)b.appendChild(e[d])}}})();a.b("utils.parseHtmlFragment",a.a.wa);a.b("utils.setHtml",a.a.fc);a.aa=function(){function b(c,e){if(c)if(8==c.nodeType){var f=a.aa.Uc(c.nodeValue);
null!=f&&e.push({ud:c,Kd:f})}else if(1==c.nodeType)for(var f=0,g=c.childNodes,h=g.length;f<h;f++)b(g[f],e)}var c={};return{Yb:function(a){if("function"!=typeof a)throw Error("You can only pass a function to ko.memoization.memoize()");var b=(4294967296*(1+Math.random())|0).toString(16).substring(1)+(4294967296*(1+Math.random())|0).toString(16).substring(1);c[b]=a;return"\x3c!--[ko_memo:"+b+"]--\x3e"},bd:function(a,b){var f=c[a];if(f===p)throw Error("Couldn't find any memo with ID "+a+". Perhaps it's already been unmemoized.");
try{return f.apply(null,b||[]),!0}finally{delete c[a]}},cd:function(c,e){var f=[];b(c,f);for(var g=0,h=f.length;g<h;g++){var m=f[g].ud,k=[m];e&&a.a.Ob(k,e);a.aa.bd(f[g].Kd,k);m.nodeValue="";m.parentNode&&m.parentNode.removeChild(m)}},Uc:function(a){return(a=a.match(/^\[ko_memo\:(.*?)\]$/))?a[1]:null}}}();a.b("memoization",a.aa);a.b("memoization.memoize",a.aa.Yb);a.b("memoization.unmemoize",a.aa.bd);a.b("memoization.parseMemoText",a.aa.Uc);a.b("memoization.unmemoizeDomNodeAndDescendants",a.aa.cd);
a.na=function(){function b(){if(f)for(var b=f,c=0,d;h<f;)if(d=e[h++]){if(h>b){if(5E3<=++c){h=f;a.a.Gc(Error("'Too much recursion' after processing "+c+" task groups."));break}b=f}try{d()}catch(g){a.a.Gc(g)}}}function c(){b();h=f=e.length=0}var d,e=[],f=0,g=1,h=0;z.MutationObserver?d=function(a){var b=v.createElement("div");(new MutationObserver(a)).observe(b,{attributes:!0});return function(){b.classList.toggle("foo")}}(c):d=v&&"onreadystatechange"in v.createElement("script")?function(a){var b=v.createElement("script");
b.onreadystatechange=function(){b.onreadystatechange=null;v.documentElement.removeChild(b);b=null;a()};v.documentElement.appendChild(b)}:function(a){setTimeout(a,0)};return{scheduler:d,Ab:function(b){f||a.na.scheduler(c);e[f++]=b;return g++},cancel:function(a){a=a-(g-f);a>=h&&a<f&&(e[a]=null)},resetForTesting:function(){var a=f-h;h=f=e.length=0;return a},Sd:b}}();a.b("tasks",a.na);a.b("tasks.schedule",a.na.Ab);a.b("tasks.runEarly",a.na.Sd);a.Va={throttle:function(b,c){b.throttleEvaluation=c;var d=
null;return a.$({read:b,write:function(e){clearTimeout(d);d=a.a.setTimeout(function(){b(e)},c)}})},rateLimit:function(a,c){var d,e,f;"number"==typeof c?d=c:(d=c.timeout,e=c.method);a.Ib=!1;f="function"==typeof e?e:"notifyWhenChangesStop"==e?Z:Y;a.ub(function(a){return f(a,d,c)})},deferred:function(b,c){if(!0!==c)throw Error("The 'deferred' extender only accepts the value 'true', because it is not supported to turn deferral off once enabled.");b.Ib||(b.Ib=!0,b.ub(function(c){var e,f=!1;return function(){if(!f){a.na.cancel(e);
e=a.na.Ab(c);try{f=!0,b.notifySubscribers(p,"dirty")}finally{f=!1}}}}))},notify:function(a,c){a.equalityComparer="always"==c?null:K}};var X={undefined:1,"boolean":1,number:1,string:1};a.b("extenders",a.Va);a.ic=function(b,c,d){this.da=b;this.lc=c;this.mc=d;this.Jb=!1;this.hb=this.Kb=null;a.L(this,"dispose",this.s);a.L(this,"disposeWhenNodeIsRemoved",this.l)};a.ic.prototype.s=function(){this.Jb||(this.hb&&a.a.J.zb(this.Kb,this.hb),this.Jb=!0,this.mc(),this.da=this.lc=this.mc=this.Kb=this.hb=null)};
a.ic.prototype.l=function(b){this.Kb=b;a.a.J.oa(b,this.hb=this.s.bind(this))};a.T=function(){a.a.Bb(this,D);D.rb(this)};var D={rb:function(a){a.U={change:[]};a.sc=1},subscribe:function(b,c,d){var e=this;d=d||"change";var f=new a.ic(e,c?b.bind(c):b,function(){a.a.Ra(e.U[d],f);e.jb&&e.jb(d)});e.Sa&&e.Sa(d);e.U[d]||(e.U[d]=[]);e.U[d].push(f);return f},notifySubscribers:function(b,c){c=c||"change";"change"===c&&this.Hb();if(this.Ya(c)){var d="change"===c&&this.ed||this.U[c].slice(0);try{a.u.xc();for(var e=
0,f;f=d[e];++e)f.Jb||f.lc(b)}finally{a.u.end()}}},qb:function(){return this.sc},Dd:function(a){return this.qb()!==a},Hb:function(){++this.sc},ub:function(b){var c=this,d=a.O(c),e,f,g,h,m;c.ib||(c.ib=c.notifySubscribers,c.notifySubscribers=aa);var k=b(function(){c.La=!1;d&&h===c&&(h=c.nc?c.nc():c());var a=f||m&&c.sb(g,h);m=f=e=!1;a&&c.ib(g=h)});c.qc=function(a,b){b&&c.La||(m=!b);c.ed=c.U.change.slice(0);c.La=e=!0;h=a;k()};c.pc=function(a){e||(g=a,c.ib(a,"beforeChange"))};c.rc=function(){m=!0};c.gd=
function(){c.sb(g,c.v(!0))&&(f=!0)}},Ya:function(a){return this.U[a]&&this.U[a].length},Bd:function(b){if(b)return this.U[b]&&this.U[b].length||0;var c=0;a.a.P(this.U,function(a,b){"dirty"!==a&&(c+=b.length)});return c},sb:function(a,c){return!this.equalityComparer||!this.equalityComparer(a,c)},toString:function(){return"[object Object]"},extend:function(b){var c=this;b&&a.a.P(b,function(b,e){var f=a.Va[b];"function"==typeof f&&(c=f(c,e)||c)});return c}};a.L(D,"init",D.rb);a.L(D,"subscribe",D.subscribe);
a.L(D,"extend",D.extend);a.L(D,"getSubscriptionsCount",D.Bd);a.a.Ca&&a.a.setPrototypeOf(D,Function.prototype);a.T.fn=D;a.Qc=function(a){return null!=a&&"function"==typeof a.subscribe&&"function"==typeof a.notifySubscribers};a.b("subscribable",a.T);a.b("isSubscribable",a.Qc);a.S=a.u=function(){function b(a){d.push(e);e=a}function c(){e=d.pop()}var d=[],e,f=0;return{xc:b,end:c,cc:function(b){if(e){if(!a.Qc(b))throw Error("Only subscribable things can act as dependencies");e.od.call(e.pd,b,b.fd||(b.fd=
++f))}},G:function(a,e,d){try{return b(),a.apply(e,d||[])}finally{c()}},ra:function(){if(e)return e.o.ra()},Xa:function(){if(e)return e.o.Xa()},$a:function(){if(e)return e.$a},o:function(){if(e)return e.o}}}();a.b("computedContext",a.S);a.b("computedContext.getDependenciesCount",a.S.ra);a.b("computedContext.getDependencies",a.S.Xa);a.b("computedContext.isInitial",a.S.$a);a.b("computedContext.registerDependency",a.S.cc);a.b("ignoreDependencies",a.Yd=a.u.G);var I=a.a.Ea("_latestValue");a.va=function(b){function c(){if(0<
arguments.length)return c.sb(c[I],arguments[0])&&(c.Aa(),c[I]=arguments[0],c.za()),this;a.u.cc(c);return c[I]}c[I]=b;a.a.Ca||a.a.extend(c,a.T.fn);a.T.fn.rb(c);a.a.Bb(c,E);a.options.deferUpdates&&a.Va.deferred(c,!0);return c};var E={equalityComparer:K,v:function(){return this[I]},za:function(){this.notifySubscribers(this[I],"spectate");this.notifySubscribers(this[I])},Aa:function(){this.notifySubscribers(this[I],"beforeChange")}};a.a.Ca&&a.a.setPrototypeOf(E,a.T.fn);var J=a.va.Oa="__ko_proto__";E[J]=
a.va;a.O=function(b){if((b="function"==typeof b&&b[J])&&b!==E[J]&&b!==a.o.fn[J])throw Error("Invalid object that looks like an observable; possibly from another Knockout instance");return!!b};a.ab=function(b){return"function"==typeof b&&(b[J]===E[J]||b[J]===a.o.fn[J]&&b.Nc)};a.b("observable",a.va);a.b("isObservable",a.O);a.b("isWriteableObservable",a.ab);a.b("isWritableObservable",a.ab);a.b("observable.fn",E);a.L(E,"peek",E.v);a.L(E,"valueHasMutated",E.za);a.L(E,"valueWillMutate",E.Aa);a.Ja=function(b){b=
b||[];if("object"!=typeof b||!("length"in b))throw Error("The argument passed when initializing an observable array must be an array, or null, or undefined.");b=a.va(b);a.a.Bb(b,a.Ja.fn);return b.extend({trackArrayChanges:!0})};a.Ja.fn={remove:function(b){for(var c=this.v(),d=[],e="function"!=typeof b||a.O(b)?function(a){return a===b}:b,f=0;f<c.length;f++){var g=c[f];if(e(g)){0===d.length&&this.Aa();if(c[f]!==g)throw Error("Array modified during remove; cannot remove item");d.push(g);c.splice(f,1);
f--}}d.length&&this.za();return d},removeAll:function(b){if(b===p){var c=this.v(),d=c.slice(0);this.Aa();c.splice(0,c.length);this.za();return d}return b?this.remove(function(c){return 0<=a.a.A(b,c)}):[]},destroy:function(b){var c=this.v(),d="function"!=typeof b||a.O(b)?function(a){return a===b}:b;this.Aa();for(var e=c.length-1;0<=e;e--){var f=c[e];d(f)&&(f._destroy=!0)}this.za()},destroyAll:function(b){return b===p?this.destroy(function(){return!0}):b?this.destroy(function(c){return 0<=a.a.A(b,c)}):
[]},indexOf:function(b){var c=this();return a.a.A(c,b)},replace:function(a,c){var d=this.indexOf(a);0<=d&&(this.Aa(),this.v()[d]=c,this.za())},sorted:function(a){var c=this().slice(0);return a?c.sort(a):c.sort()},reversed:function(){return this().slice(0).reverse()}};a.a.Ca&&a.a.setPrototypeOf(a.Ja.fn,a.va.fn);a.a.D("pop push reverse shift sort splice unshift".split(" "),function(b){a.Ja.fn[b]=function(){var a=this.v();this.Aa();this.zc(a,b,arguments);var d=a[b].apply(a,arguments);this.za();return d===
a?this:d}});a.a.D(["slice"],function(b){a.Ja.fn[b]=function(){var a=this();return a[b].apply(a,arguments)}});a.Pc=function(b){return a.O(b)&&"function"==typeof b.remove&&"function"==typeof b.push};a.b("observableArray",a.Ja);a.b("isObservableArray",a.Pc);a.Va.trackArrayChanges=function(b,c){function d(){function c(){if(m){var e=[].concat(b.v()||[]),d;if(b.Ya("arrayChange")){if(!f||1<m)f=a.a.Qb(k,e,b.Pb);d=f}k=e;f=null;m=0;d&&d.length&&b.notifySubscribers(d,"arrayChange")}}e?c():(e=!0,h=b.subscribe(function(){++m},
null,"spectate"),k=[].concat(b.v()||[]),f=null,g=b.subscribe(c))}b.Pb={};c&&"object"==typeof c&&a.a.extend(b.Pb,c);b.Pb.sparse=!0;if(!b.zc){var e=!1,f=null,g,h,m=0,k,l=b.Sa,q=b.jb;b.Sa=function(a){l&&l.call(b,a);"arrayChange"===a&&d()};b.jb=function(a){q&&q.call(b,a);"arrayChange"!==a||b.Ya("arrayChange")||(g&&g.s(),h&&h.s(),h=g=null,e=!1,k=p)};b.zc=function(b,c,d){function l(a,b,c){return k[k.length]={status:a,value:b,index:c}}if(e&&!m){var k=[],g=b.length,q=d.length,h=0;switch(c){case "push":h=
g;case "unshift":for(c=0;c<q;c++)l("added",d[c],h+c);break;case "pop":h=g-1;case "shift":g&&l("deleted",b[h],h);break;case "splice":c=Math.min(Math.max(0,0>d[0]?g+d[0]:d[0]),g);for(var g=1===q?g:Math.min(c+(d[1]||0),g),q=c+q-2,h=Math.max(g,q),U=[],V=[],p=2;c<h;++c,++p)c<g&&V.push(l("deleted",b[c],c)),c<q&&U.push(l("added",d[p],c));a.a.Kc(V,U);break;default:return}f=k}}}};var t=a.a.Ea("_state");a.o=a.$=function(b,c,d){function e(){if(0<arguments.length){if("function"===typeof f)f.apply(g.pb,arguments);
else throw Error("Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.");return this}g.ta||a.u.cc(e);(g.ka||g.K&&e.Za())&&e.ha();return g.X}"object"===typeof b?d=b:(d=d||{},b&&(d.read=b));if("function"!=typeof d.read)throw Error("Pass a function that returns the value of the ko.computed");var f=d.write,g={X:p,ua:!0,ka:!0,sa:!1,jc:!1,ta:!1,xb:!1,K:!1,Wc:d.read,pb:c||d.owner,l:d.disposeWhenNodeIsRemoved||d.l||null,
Ua:d.disposeWhen||d.Ua,Sb:null,I:{},V:0,Ic:null};e[t]=g;e.Nc="function"===typeof f;a.a.Ca||a.a.extend(e,a.T.fn);a.T.fn.rb(e);a.a.Bb(e,B);d.pure?(g.xb=!0,g.K=!0,a.a.extend(e,da)):d.deferEvaluation&&a.a.extend(e,ea);a.options.deferUpdates&&a.Va.deferred(e,!0);g.l&&(g.jc=!0,g.l.nodeType||(g.l=null));g.K||d.deferEvaluation||e.ha();g.l&&e.ja()&&a.a.J.oa(g.l,g.Sb=function(){e.s()});return e};var B={equalityComparer:K,ra:function(){return this[t].V},Xa:function(){var b=[];a.a.P(this[t].I,function(a,d){b[d.Ma]=
d.da});return b},Wb:function(b){if(!this[t].V)return!1;var c=this.Xa();return-1!==a.a.A(c,b)?!0:!!a.a.Mb(c,function(a){return a.Wb&&a.Wb(b)})},uc:function(a,c,d){if(this[t].xb&&c===this)throw Error("A 'pure' computed must not be called recursively");this[t].I[a]=d;d.Ma=this[t].V++;d.Na=c.qb()},Za:function(){var a=this[t];if(a.sa)return!1;a.sa=!0;try{var c,d,e=a.I;for(c in e)if(Object.prototype.hasOwnProperty.call(e,c)&&(d=e[c],this.Ka&&d.da.La||d.da.Dd(d.Na)))return!0}finally{a.sa=!1}},Jd:function(){this.Ka&&
!this[t].sa&&this.Ka(!1)},ja:function(){var a=this[t];return a.ka||0<a.V},Rd:function(){this.La?this[t].ka&&(this[t].ua=!0):this.Hc()},$c:function(a){if(a.Ib){var c=a.subscribe(this.Jd,this,"dirty"),d=a.subscribe(this.Rd,this);return{da:a,s:function(){c.s();d.s()}}}return a.subscribe(this.Hc,this)},Hc:function(){var b=this,c=b.throttleEvaluation;c&&0<=c?(clearTimeout(this[t].Ic),this[t].Ic=a.a.setTimeout(function(){b.ha(!0)},c)):b.Ka?b.Ka(!0):b.ha(!0)},ha:function(b){var c=this[t],d=c.Ua,e=!1;if(!c.sa&&
!c.ta){if(c.l&&!a.a.Tb(c.l)||d&&d()){if(!c.jc){this.s();return}}else c.jc=!1;c.sa=!0;try{e=this.zd(b)}finally{c.sa=!1}return e}},zd:function(b){var c=this[t],d=!1,e=c.xb?p:!c.V,d={qd:this,ob:c.I,Rb:c.V};a.u.xc({pd:d,od:ca,o:this,$a:e});c.I={};c.V=0;var f=this.yd(c,d);c.V?d=this.sb(c.X,f):(this.s(),d=!0);d&&(c.K?this.Hb():this.notifySubscribers(c.X,"beforeChange"),c.X=f,this.notifySubscribers(c.X,"spectate"),!c.K&&b&&this.notifySubscribers(c.X),this.rc&&this.rc());e&&this.notifySubscribers(c.X,"awake");
return d},yd:function(b,c){try{var d=b.Wc;return b.pb?d.call(b.pb):d()}finally{a.u.end(),c.Rb&&!b.K&&a.a.P(c.ob,ba),b.ua=b.ka=!1}},v:function(a){var c=this[t];(c.ka&&(a||!c.V)||c.K&&this.Za())&&this.ha();return c.X},ub:function(b){a.T.fn.ub.call(this,b);this.nc=function(){this[t].K||(this[t].ua?this.ha():this[t].ka=!1);return this[t].X};this.Ka=function(a){this.pc(this[t].X);this[t].ka=!0;a&&(this[t].ua=!0);this.qc(this,!a)}},s:function(){var b=this[t];!b.K&&b.I&&a.a.P(b.I,function(a,b){b.s&&b.s()});
b.l&&b.Sb&&a.a.J.zb(b.l,b.Sb);b.I=p;b.V=0;b.ta=!0;b.ua=!1;b.ka=!1;b.K=!1;b.l=p;b.Ua=p;b.Wc=p;this.Nc||(b.pb=p)}},da={Sa:function(b){var c=this,d=c[t];if(!d.ta&&d.K&&"change"==b){d.K=!1;if(d.ua||c.Za())d.I=null,d.V=0,c.ha()&&c.Hb();else{var e=[];a.a.P(d.I,function(a,b){e[b.Ma]=a});a.a.D(e,function(a,b){var e=d.I[a],m=c.$c(e.da);m.Ma=b;m.Na=e.Na;d.I[a]=m});c.Za()&&c.ha()&&c.Hb()}d.ta||c.notifySubscribers(d.X,"awake")}},jb:function(b){var c=this[t];c.ta||"change"!=b||this.Ya("change")||(a.a.P(c.I,function(a,
b){b.s&&(c.I[a]={da:b.da,Ma:b.Ma,Na:b.Na},b.s())}),c.K=!0,this.notifySubscribers(p,"asleep"))},qb:function(){var b=this[t];b.K&&(b.ua||this.Za())&&this.ha();return a.T.fn.qb.call(this)}},ea={Sa:function(a){"change"!=a&&"beforeChange"!=a||this.v()}};a.a.Ca&&a.a.setPrototypeOf(B,a.T.fn);var O=a.va.Oa;B[O]=a.o;a.Oc=function(a){return"function"==typeof a&&a[O]===B[O]};a.Fd=function(b){return a.Oc(b)&&b[t]&&b[t].xb};a.b("computed",a.o);a.b("dependentObservable",a.o);a.b("isComputed",a.Oc);a.b("isPureComputed",
a.Fd);a.b("computed.fn",B);a.L(B,"peek",B.v);a.L(B,"dispose",B.s);a.L(B,"isActive",B.ja);a.L(B,"getDependenciesCount",B.ra);a.L(B,"getDependencies",B.Xa);a.yb=function(b,c){if("function"===typeof b)return a.o(b,c,{pure:!0});b=a.a.extend({},b);b.pure=!0;return a.o(b,c)};a.b("pureComputed",a.yb);(function(){function b(a,f,g){g=g||new d;a=f(a);if("object"!=typeof a||null===a||a===p||a instanceof RegExp||a instanceof Date||a instanceof String||a instanceof Number||a instanceof Boolean)return a;var h=
a instanceof Array?[]:{};g.save(a,h);c(a,function(c){var d=f(a[c]);switch(typeof d){case "boolean":case "number":case "string":case "bigint":case "symbol":case "function":h[c]=d;break;case "object":case "undefined":var l=g.get(d);h[c]=l!==p?l:b(d,f,g)}});return h}function c(a,b){if(a instanceof Array){for(var c=0;c<a.length;c++)b(c);"function"==typeof a.toJSON&&b("toJSON")}else for(c in a)b(c)}function d(){this.keys=[];this.values=[]}a.ad=function(c){if(0==arguments.length)throw Error("When calling ko.toJS, pass the object you want to convert.");
return b(c,function(b){for(var c=0;a.O(b)&&10>c;c++)b=b();return b})};a.toJSON=function(b,c,d){b=a.ad(b);return a.a.hc(b,c,d)};d.prototype={constructor:d,save:function(b,c){var d=a.a.A(this.keys,b);0<=d?this.values[d]=c:(this.keys.push(b),this.values.push(c))},get:function(b){b=a.a.A(this.keys,b);return 0<=b?this.values[b]:p}}})();a.b("toJS",a.ad);a.b("toJSON",a.toJSON);a.Wd=function(b,c,d){function e(c){var e=a.yb(b,d).extend({ma:"always"}),h=e.subscribe(function(a){a&&(h.s(),c(a))});e.notifySubscribers(e.v());
return h}return"function"!==typeof Promise||c?e(c.bind(d)):new Promise(e)};a.b("when",a.Wd);(function(){a.w={M:function(b){switch(a.a.R(b)){case "option":return!0===b.__ko__hasDomDataOptionValue__?a.a.g.get(b,a.c.options.$b):7>=a.a.W?b.getAttributeNode("value")&&b.getAttributeNode("value").specified?b.value:b.text:b.value;case "select":return 0<=b.selectedIndex?a.w.M(b.options[b.selectedIndex]):p;default:return b.value}},fb:function(b,c,d){switch(a.a.R(b)){case "option":"string"===typeof c?(a.a.g.set(b,
a.c.options.$b,p),"__ko__hasDomDataOptionValue__"in b&&delete b.__ko__hasDomDataOptionValue__,b.value=c):(a.a.g.set(b,a.c.options.$b,c),b.__ko__hasDomDataOptionValue__=!0,b.value="number"===typeof c?c:"");break;case "select":if(""===c||null===c)c=p;for(var e=-1,f=0,g=b.options.length,h;f<g;++f)if(h=a.w.M(b.options[f]),h==c||""===h&&c===p){e=f;break}if(d||0<=e||c===p&&1<b.size)b.selectedIndex=e,6===a.a.W&&a.a.setTimeout(function(){b.selectedIndex=e},0);break;default:if(null===c||c===p)c="";b.value=
c}}}})();a.b("selectExtensions",a.w);a.b("selectExtensions.readValue",a.w.M);a.b("selectExtensions.writeValue",a.w.fb);a.m=function(){function b(b){b=a.a.Eb(b);123===b.charCodeAt(0)&&(b=b.slice(1,-1));b+="\n,";var c=[],d=b.match(e),q,n=[],h=0;if(1<d.length){for(var y=0,C;C=d[y];++y){var u=C.charCodeAt(0);if(44===u){if(0>=h){c.push(q&&n.length?{key:q,value:n.join("")}:{unknown:q||n.join("")});q=h=0;n=[];continue}}else if(58===u){if(!h&&!q&&1===n.length){q=n.pop();continue}}else if(47===u&&1<C.length&&
(47===C.charCodeAt(1)||42===C.charCodeAt(1)))continue;else 47===u&&y&&1<C.length?(u=d[y-1].match(f))&&!g[u[0]]&&(b=b.substr(b.indexOf(C)+1),d=b.match(e),y=-1,C="/"):40===u||123===u||91===u?++h:41===u||125===u||93===u?--h:q||n.length||34!==u&&39!==u||(C=C.slice(1,-1));n.push(C)}if(0<h)throw Error("Unbalanced parentheses, braces, or brackets");}return c}var c=["true","false","null","undefined"],d=/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i,e=RegExp("\"(?:\\\\.|[^\"])*\"|'(?:\\\\.|[^'])*'|`(?:\\\\.|[^`])*`|/\\*(?:[^*]|\\*+[^*/])*\\*+/|//.*\n|/(?:\\\\.|[^/])+/w*|[^\\s:,/][^,\"'`{}()/:[\\]]*[^\\s,\"'`{}()/:[\\]]|[^\\s]",
"g"),f=/[\])"'A-Za-z0-9_$]+$/,g={"in":1,"return":1,"typeof":1},h={};return{Ta:[],ya:h,ac:b,wb:function(e,f){function l(b,e){var f;if(!y){var k=a.getBindingHandler(b);if(k&&k.preprocess&&!(e=k.preprocess(e,b,l)))return;if(k=h[b])f=e,0<=a.a.A(c,f)?f=!1:(k=f.match(d),f=null===k?!1:k[1]?"Object("+k[1]+")"+k[2]:f),k=f;k&&n.push("'"+("string"==typeof h[b]?h[b]:b)+"':function(_z){"+f+"=_z}")}g&&(e="function(){return "+e+" }");q.push("'"+b+"':"+e)}f=f||{};var q=[],n=[],g=f.valueAccessors,y=f.bindingParams,
C="string"===typeof e?b(e):e;a.a.D(C,function(a){l(a.key||a.unknown,a.value)});n.length&&l("_ko_property_writers","{"+n.join(",")+" }");return q.join(",")},Id:function(a,b){for(var c=0;c<a.length;c++)if(a[c].key==b)return!0;return!1},gb:function(b,c,e,d,f){if(b&&a.O(b))!a.ab(b)||f&&b.v()===d||b(d);else if((b=c.get("_ko_property_writers"))&&b[e])b[e](d)}}}();a.b("expressionRewriting",a.m);a.b("expressionRewriting.bindingRewriteValidators",a.m.Ta);a.b("expressionRewriting.parseObjectLiteral",a.m.ac);
a.b("expressionRewriting.preProcessBindings",a.m.wb);a.b("expressionRewriting._twoWayBindings",a.m.ya);a.b("jsonExpressionRewriting",a.m);a.b("jsonExpressionRewriting.insertPropertyAccessorsIntoJson",a.m.wb);(function(){function b(a){return 8==a.nodeType&&g.test(f?a.text:a.nodeValue)}function c(a){return 8==a.nodeType&&h.test(f?a.text:a.nodeValue)}function d(e,d){for(var f=e,h=1,g=[];f=f.nextSibling;){if(c(f)&&(a.a.g.set(f,k,!0),h--,0===h))return g;g.push(f);b(f)&&h++}if(!d)throw Error("Cannot find closing comment tag to match: "+
e.nodeValue);return null}function e(a,b){var c=d(a,b);return c?0<c.length?c[c.length-1].nextSibling:a.nextSibling:null}var f=v&&"\x3c!--test--\x3e"===v.createComment("test").text,g=f?/^\x3c!--\s*ko(?:\s+([\s\S]+))?\s*--\x3e$/:/^\s*ko(?:\s+([\s\S]+))?\s*$/,h=f?/^\x3c!--\s*\/ko\s*--\x3e$/:/^\s*\/ko\s*$/,m={ul:!0,ol:!0},k="__ko_matchedEndComment__";a.h={ea:{},childNodes:function(a){return b(a)?d(a):a.childNodes},Fa:function(c){if(b(c)){c=a.h.childNodes(c);for(var e=0,d=c.length;e<d;e++)a.removeNode(c[e])}else a.a.Ub(c)},
xa:function(c,e){if(b(c)){a.h.Fa(c);for(var d=c.nextSibling,f=0,k=e.length;f<k;f++)d.parentNode.insertBefore(e[f],d)}else a.a.xa(c,e)},Vc:function(a,c){var e;b(a)?(e=a.nextSibling,a=a.parentNode):e=a.firstChild;e?c!==e&&a.insertBefore(c,e):a.appendChild(c)},Xb:function(c,e,d){d?(d=d.nextSibling,b(c)&&(c=c.parentNode),d?e!==d&&c.insertBefore(e,d):c.appendChild(e)):a.h.Vc(c,e)},firstChild:function(a){return b(a)?!a.nextSibling||c(a.nextSibling)?null:a.nextSibling:a.firstChild&&c(a.firstChild)?a.firstChild.nextSibling:
a.firstChild},nextSibling:function(d){b(d)&&(d=e(d));return d.nextSibling&&c(d.nextSibling)?(d=d.nextSibling,c(d)&&a.a.g.get(d,k),null):d.nextSibling},Cd:b,Vd:function(a){return(a=(f?a.text:a.nodeValue).match(g))?a[1]:null},Sc:function(d){if(m[a.a.R(d)]){var f=d.firstChild;if(f){do if(1===f.nodeType){var k;k=f.firstChild;var h=null;if(k){do if(h)h.push(k);else if(b(k)){var g=e(k,!0);g?k=g:h=[k]}else c(k)&&(h=[k]);while(k=k.nextSibling)}if(k=h)for(h=f.nextSibling,g=0;g<k.length;g++)h?d.insertBefore(k[g],
h):d.appendChild(k[g])}while(f=f.nextSibling)}}}}})();a.b("virtualElements",a.h);a.b("virtualElements.allowedBindings",a.h.ea);a.b("virtualElements.emptyNode",a.h.Fa);a.b("virtualElements.insertAfter",a.h.Xb);a.b("virtualElements.prepend",a.h.Vc);a.b("virtualElements.setDomNodeChildren",a.h.xa);(function(){function b(b,d){var e="with($context){with($data||{}){return{"+a.m.wb(b,d)+"}}}";return H?(0,eval)(H.createScript("(function($context,$element){"+e+"})")):new Function("$context","$element",e)}
a.ga=function(){this.nd={}};a.a.extend(a.ga.prototype,{nodeHasBindings:function(b){switch(b.nodeType){case 1:return null!=b.getAttribute("data-bind")||a.j.getComponentNameForNode(b);case 8:return a.h.Cd(b);default:return!1}},getBindings:function(b,d){var e=this.getBindingsString(b,d),e=e?this.parseBindingsString(e,d,b):null;return a.j.tc(e,b,d,!1)},getBindingAccessors:function(b,d){var e=this.getBindingsString(b,d),e=e?this.parseBindingsString(e,d,b,{valueAccessors:!0}):null;return a.j.tc(e,b,d,!0)},
getBindingsString:function(b){switch(b.nodeType){case 1:return b.getAttribute("data-bind");case 8:return a.h.Vd(b);default:return null}},parseBindingsString:function(a,d,e,f){try{var g=this.nd,h=a+(f&&f.valueAccessors||"");return(g[h]||(g[h]=b(a,f)))(d,e)}catch(m){throw m.message="Unable to parse bindings.\nBindings value: "+a+"\nMessage: "+m.message,m;}}});a.ga.instance=new a.ga})();a.b("bindingProvider",a.ga);(function(){function b(b){var c=(b=a.a.g.get(b,A))&&b.N;c&&(b.N=null,c.Tc())}function c(c,
d,e){this.node=c;this.yc=d;this.mb=[];this.H=!1;d.N||a.a.J.oa(c,b);e&&e.N&&(e.N.mb.push(c),this.Lb=e)}function d(a){return function(){return a}}function e(a){return a()}function f(b){return a.a.Ia(a.u.G(b),function(a,c){return function(){return b()[c]}})}function g(b,c,e){return"function"===typeof b?f(b.bind(null,c,e)):a.a.Ia(b,d)}function h(a,b){return f(this.getBindings.bind(this,a,b))}function m(b,c){var e=a.h.firstChild(c);if(e){var d,f=a.ga.instance,l=f.preprocessNode;if(l){for(;d=e;)e=a.h.nextSibling(d),
l.call(f,d);e=a.h.firstChild(c)}for(;d=e;)e=a.h.nextSibling(d),k(b,d)}a.i.ma(c,a.i.H)}function k(b,c){var e=b,d=1===c.nodeType;d&&a.h.Sc(c);if(d||a.ga.instance.nodeHasBindings(c))e=q(c,null,b).bindingContextForDescendants;e&&!u[a.a.R(c)]&&m(e,c)}function l(b){var c=[],e={},d=[];a.a.P(b,function x(f){if(!e[f]){var k=a.getBindingHandler(f);k&&(k.after&&(d.push(f),a.a.D(k.after,function(c){if(b[c]){if(-1!==a.a.A(d,c))throw Error("Cannot combine the following bindings, because they have a cyclic dependency: "+
d.join(", "));x(c)}}),d.length--),c.push({key:f,Mc:k}));e[f]=!0}});return c}function q(b,c,d){var f=a.a.g.Vb(b,A,{}),k=f.hd;if(!c){if(k)throw Error("You cannot apply bindings multiple times to the same element.");f.hd=!0}k||(f.context=d);f.vb||(f.vb={});var g;if(c&&"function"!==typeof c)g=c;else{var q=a.ga.instance,n=q.getBindingAccessors||h,m=a.$(function(){if(g=c?c(d,b):n.call(q,b,d)){if(d[r])d[r]();if(d[C])d[C]()}return g},null,{l:b});g&&m.ja()||(m=null)}var y=d,u;if(g){var L=m?function(a){return function(){return e(m()[a])}}:
function(a){return g[a]},t=function(){return a.a.Ia(m?m():g,e)};t.get=function(a){return g[a]&&e(L(a))};t.has=function(a){return a in g};a.i.H in g&&a.i.subscribe(b,a.i.H,function(){var c=(0,g[a.i.H])();if(c){var d=a.h.childNodes(b);d.length&&c(d,a.Ec(d[0]))}});a.i.qa in g&&(y=a.i.Db(b,d),a.i.subscribe(b,a.i.qa,function(){var c=(0,g[a.i.qa])();c&&a.h.firstChild(b)&&c(b)}));f=l(g);a.a.D(f,function(c){var d=c.Mc.init,e=c.Mc.update,f=c.key;if(8===b.nodeType&&!a.h.ea[f])throw Error("The binding '"+f+
"' cannot be used with virtual elements");try{"function"==typeof d&&a.u.G(function(){var a=d(b,L(f),t,y.$data,y);if(a&&a.controlsDescendantBindings){if(u!==p)throw Error("Multiple bindings ("+u+" and "+f+") are trying to control descendant bindings of the same element. You cannot use these bindings together on the same element.");u=f}}),"function"==typeof e&&a.$(function(){e(b,L(f),t,y.$data,y)},null,{l:b})}catch(k){throw k.message='Unable to process binding "'+f+": "+g[f]+'"\nMessage: '+k.message,
k;}})}f=u===p;return{shouldBindDescendants:f,bindingContextForDescendants:f&&y}}function n(b,c){return b&&b instanceof a.fa?b:new a.fa(b,p,p,c)}var r=a.a.Ea("_subscribable"),y=a.a.Ea("_ancestorBindingInfo"),C=a.a.Ea("_dataDependency");a.c={};var u={script:!0,textarea:!0,template:!0};a.getBindingHandler=function(b){return a.c[b]};var L={};a.fa=function(b,c,d,e,f){function k(){var b=q?h():h,f=a.a.f(b);c?(a.a.extend(l,c),y in c&&(l[y]=c[y])):(l.$parents=[],l.$root=f,l.ko=a);l[r]=n;g?f=l.$data:(l.$rawData=
b,l.$data=f);d&&(l[d]=f);e&&e(l,c,f);if(c&&c[r]&&!a.S.o().Wb(c[r]))c[r]();m&&(l[C]=m);return l.$data}var l=this,g=b===L,h=g?p:b,q="function"==typeof h&&!a.O(h),n,m=f&&f.dataDependency;f&&f.exportDependencies?k():(n=a.yb(k),n.v(),n.ja()?n.equalityComparer=null:l[r]=p)};a.fa.prototype.createChildContext=function(b,c,d,e){!e&&c&&"object"==typeof c&&(e=c,c=e.as,d=e.extend);if(c&&e&&e.noChildContext){var f="function"==typeof b&&!a.O(b);return new a.fa(L,this,null,function(a){d&&d(a);a[c]=f?b():b},e)}return new a.fa(b,
this,c,function(a,b){a.$parentContext=b;a.$parent=b.$data;a.$parents=(b.$parents||[]).slice(0);a.$parents.unshift(a.$parent);d&&d(a)},e)};a.fa.prototype.extend=function(b,c){return new a.fa(L,this,null,function(c){a.a.extend(c,"function"==typeof b?b(c):b)},c)};var A=a.a.g.Z();c.prototype.Tc=function(){this.Lb&&this.Lb.N&&this.Lb.N.sd(this.node)};c.prototype.sd=function(b){a.a.Ra(this.mb,b);!this.mb.length&&this.H&&this.Cc()};c.prototype.Cc=function(){this.H=!0;this.yc.N&&!this.mb.length&&(this.yc.N=
null,a.a.J.zb(this.node,b),a.i.ma(this.node,a.i.qa),this.Tc())};a.i={H:"childrenComplete",qa:"descendantsComplete",subscribe:function(b,c,d,e,f){var k=a.a.g.Vb(b,A,{});k.Ga||(k.Ga=new a.T);f&&f.notifyImmediately&&k.vb&&k.vb[c]&&a.u.G(d,e,[b]);return k.Ga.subscribe(d,e,c)},ma:function(b,c){var d=a.a.g.get(b,A);if(d&&(d.vb[c]=!0,d.Ga&&d.Ga.notifySubscribers(b,c),c==a.i.H))if(d.N)d.N.Cc();else if(d.N===p&&d.Ga&&d.Ga.Ya(a.i.qa))throw Error("descendantsComplete event not supported for bindings on this node");
},Db:function(b,d){var e=a.a.g.Vb(b,A,{});e.N||(e.N=new c(b,e,d[y]));return d[y]==e?d:d.extend(function(a){a[y]=e})}};a.Td=function(b){return(b=a.a.g.get(b,A))&&b.context};a.kb=function(b,c,d){1===b.nodeType&&a.h.Sc(b);return q(b,c,n(d))};a.ld=function(b,c,d){d=n(d);return a.kb(b,g(c,d,b),d)};a.Qa=function(a,b){1!==b.nodeType&&8!==b.nodeType||m(n(a),b)};a.vc=function(a,b,c){!w&&z.jQuery&&(w=z.jQuery);if(2>arguments.length){if(b=v.body,!b)throw Error("ko.applyBindings: could not find document.body; has the document been loaded?");
}else if(!b||1!==b.nodeType&&8!==b.nodeType)throw Error("ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node");k(n(a,c),b)};a.Dc=function(b){return!b||1!==b.nodeType&&8!==b.nodeType?p:a.Td(b)};a.Ec=function(b){return(b=a.Dc(b))?b.$data:p};a.b("bindingHandlers",a.c);a.b("bindingEvent",a.i);a.b("bindingEvent.subscribe",a.i.subscribe);a.b("bindingEvent.startPossiblyAsyncContentBinding",a.i.Db);a.b("applyBindings",a.vc);a.b("applyBindingsToDescendants",a.Qa);
a.b("applyBindingAccessorsToNode",a.kb);a.b("applyBindingsToNode",a.ld);a.b("contextFor",a.Dc);a.b("dataFor",a.Ec)})();(function(b){function c(c,e){var k=Object.prototype.hasOwnProperty.call(f,c)?f[c]:b,l;k?k.subscribe(e):(k=f[c]=new a.T,k.subscribe(e),d(c,function(b,d){var e=!(!d||!d.synchronous);g[c]={definition:b,Gd:e};delete f[c];l||e?k.notifySubscribers(b):a.na.Ab(function(){k.notifySubscribers(b)})}),l=!0)}function d(a,b){e("getConfig",[a],function(c){c?e("loadComponent",[a,c],function(a){b(a,
c)}):b(null,null)})}function e(c,d,f,l){l||(l=a.j.loaders.slice(0));var g=l.shift();if(g){var n=g[c];if(n){var r=!1;if(n.apply(g,d.concat(function(a){r?f(null):null!==a?f(a):e(c,d,f,l)}))!==b&&(r=!0,!g.suppressLoaderExceptions))throw Error("Component loaders must supply values by invoking the callback, not by returning values synchronously.");}else e(c,d,f,l)}else f(null)}var f={},g={};a.j={get:function(d,e){var f=Object.prototype.hasOwnProperty.call(g,d)?g[d]:b;f?f.Gd?a.u.G(function(){e(f.definition)}):
a.na.Ab(function(){e(f.definition)}):c(d,e)},Bc:function(a){delete g[a]},oc:e};a.j.loaders=[];a.b("components",a.j);a.b("components.get",a.j.get);a.b("components.clearCachedDefinition",a.j.Bc)})();(function(){function b(b,c,d,e){function g(){0===--C&&e(h)}var h={},C=2,u=d.template;d=d.viewModel;u?f(c,u,function(c){a.j.oc("loadTemplate",[b,c],function(a){h.template=a;g()})}):g();d?f(c,d,function(c){a.j.oc("loadViewModel",[b,c],function(a){h[m]=a;g()})}):g()}function c(a,b,d){if("function"===typeof b)d(function(a){return new b(a)});
else if("function"===typeof b[m])d(b[m]);else if("instance"in b){var e=b.instance;d(function(){return e})}else"viewModel"in b?c(a,b.viewModel,d):a("Unknown viewModel value: "+b)}function d(b){switch(a.a.R(b)){case "script":return a.a.wa(b.text);case "textarea":return a.a.wa(b.value);case "template":if(e(b.content))return a.a.Da(b.content.childNodes)}return a.a.Da(b.childNodes)}function e(a){return z.DocumentFragment?a instanceof DocumentFragment:a&&11===a.nodeType}function f(a,b,c){"string"===typeof b.require?
T||z.require?(T||z.require)([b.require],function(a){a&&"object"===typeof a&&a.Xd&&a["default"]&&(a=a["default"]);c(a)}):a("Uses require, but no AMD loader is present"):c(b)}function g(a){return function(b){throw Error("Component '"+a+"': "+b);}}var h={};a.j.register=function(b,c){if(!c)throw Error("Invalid configuration for "+b);if(a.j.tb(b))throw Error("Component "+b+" is already registered");h[b]=c};a.j.tb=function(a){return Object.prototype.hasOwnProperty.call(h,a)};a.j.unregister=function(b){delete h[b];
a.j.Bc(b)};a.j.Fc={getConfig:function(b,c){c(a.j.tb(b)?h[b]:null)},loadComponent:function(a,c,d){var e=g(a);f(e,c,function(c){b(a,e,c,d)})},loadTemplate:function(b,c,f){b=g(b);if("string"===typeof c)f(a.a.wa(c));else if(c instanceof Array)f(c);else if(e(c))f(a.a.la(c.childNodes));else if(c.element)if(c=c.element,z.HTMLElement?c instanceof HTMLElement:c&&c.tagName&&1===c.nodeType)f(d(c));else if("string"===typeof c){var h=v.getElementById(c);h?f(d(h)):b("Cannot find element with ID "+c)}else b("Unknown element type: "+
c);else b("Unknown template value: "+c)},loadViewModel:function(a,b,d){c(g(a),b,d)}};var m="createViewModel";a.b("components.register",a.j.register);a.b("components.isRegistered",a.j.tb);a.b("components.unregister",a.j.unregister);a.b("components.defaultLoader",a.j.Fc);a.j.loaders.push(a.j.Fc);a.j.dd=h})();(function(){function b(b,e){var f=b.getAttribute("params");if(f){var f=c.parseBindingsString(f,e,b,{valueAccessors:!0,bindingParams:!0}),f=a.a.Ia(f,function(c){return a.o(c,null,{l:b})}),g=a.a.Ia(f,
function(c){var e=c.v();return c.ja()?a.o({read:function(){return a.a.f(c())},write:a.ab(e)&&function(a){c()(a)},l:b}):e});Object.prototype.hasOwnProperty.call(g,"$raw")||(g.$raw=f);return g}return{$raw:{}}}a.j.getComponentNameForNode=function(b){var c=a.a.R(b);if(a.j.tb(c)&&(-1!=c.indexOf("-")||"[object HTMLUnknownElement]"==""+b||8>=a.a.W&&b.tagName===c))return c};a.j.tc=function(c,e,f,g){if(1===e.nodeType){var h=a.j.getComponentNameForNode(e);if(h){c=c||{};if(c.component)throw Error('Cannot use the "component" binding on a custom element matching a component');
var m={name:h,params:b(e,f)};c.component=g?function(){return m}:m}}return c};var c=new a.ga;9>a.a.W&&(a.j.register=function(a){return function(b){return a.apply(this,arguments)}}(a.j.register),v.createDocumentFragment=function(b){return function(){var c=b(),f=a.j.dd,g;for(g in f);return c}}(v.createDocumentFragment))})();(function(){function b(b,c,d){c=c.template;if(!c)throw Error("Component '"+b+"' has no template");b=a.a.Da(c);a.h.xa(d,b)}function c(a,b,c){var d=a.createViewModel;return d?d.call(a,
b,c):b}var d=0;a.c.component={init:function(e,f,g,h,m){function k(){var a=l&&l.dispose;"function"===typeof a&&a.call(l);n&&n.s();q=l=n=null}var l,q,n,r=a.a.la(a.h.childNodes(e));a.h.Fa(e);a.a.J.oa(e,k);a.o(function(){var g=a.a.f(f()),h,u;"string"===typeof g?h=g:(h=a.a.f(g.name),u=a.a.f(g.params));if(!h)throw Error("No component name specified");var p=a.i.Db(e,m),A=q=++d;a.j.get(h,function(d){if(q===A){k();if(!d)throw Error("Unknown component '"+h+"'");b(h,d,e);var f=c(d,u,{element:e,templateNodes:r});
d=p.createChildContext(f,{extend:function(a){a.$component=f;a.$componentTemplateNodes=r}});f&&f.koDescendantsComplete&&(n=a.i.subscribe(e,a.i.qa,f.koDescendantsComplete,f));l=f;a.Qa(d,e)}})},null,{l:e});return{controlsDescendantBindings:!0}}};a.h.ea.component=!0})();var W={"class":"className","for":"htmlFor"};a.c.attr={update:function(b,c){var d=a.a.f(c())||{};a.a.P(d,function(c,d){d=a.a.f(d);var g=c.indexOf(":"),g="lookupNamespaceURI"in b&&0<g&&b.lookupNamespaceURI(c.substr(0,g)),h=!1===d||null===
d||d===p;h?g?b.removeAttributeNS(g,c):b.removeAttribute(c):d=d.toString();8>=a.a.W&&c in W?(c=W[c],h?b.removeAttribute(c):b[c]=d):h||(g?b.setAttributeNS(g,c,d):b.setAttribute(c,d));"name"===c&&a.a.Yc(b,h?"":d)})}};(function(){a.c.checked={after:["value","attr"],init:function(b,c,d){function e(){var e=b.checked,f=g();if(!a.S.$a()&&(e||!m&&!a.S.ra())){var k=a.u.G(c);if(l){var n=q?k.v():k,A=r;r=f;A!==f?e&&(a.a.Pa(n,f,!0),a.a.Pa(n,A,!1)):a.a.Pa(n,f,e);q&&a.ab(k)&&k(n)}else h&&(f===p?f=e:e||(f=p)),a.m.gb(k,
d,"checked",f,!0)}}function f(){var d=a.a.f(c()),e=g();l?(b.checked=null!=d&&0<=a.a.A(d,e),r=e):b.checked=h&&e===p?!!d:g()===d}var g=a.yb(function(){if(d.has("checkedValue"))return a.a.f(d.get("checkedValue"));if(n)return d.has("value")?a.a.f(d.get("value")):b.value}),h="checkbox"==b.type,m="radio"==b.type;if(h||m){var k=c(),l=h&&a.a.f(k)instanceof Array,q=!(l&&k.push&&k.splice),n=m||l,r=l?g():p;m&&!b.name&&a.c.uniqueName.init(b,function(){return!0});a.o(e,null,{l:b});a.a.B(b,"click",e);a.o(f,null,
{l:b});k=p}}};a.m.ya.checked=!0;a.c.checkedValue={update:function(b,c){b.value=a.a.f(c())}}})();a.c["class"]={update:function(b,c){var d=a.a.Eb(a.a.f(c()));a.a.Fb(b,b.__ko__cssValue,!1);b.__ko__cssValue=d;a.a.Fb(b,d,!0)}};a.c.css={update:function(b,c){var d=a.a.f(c());null!==d&&"object"==typeof d?a.a.P(d,function(c,d){d=a.a.f(d);a.a.Fb(b,c,d)}):a.c["class"].update(b,c)}};a.c.enable={update:function(b,c){var d=a.a.f(c());d&&b.disabled?b.removeAttribute("disabled"):d||b.disabled||(b.disabled=!0)}};
a.c.disable={update:function(b,c){a.c.enable.update(b,function(){return!a.a.f(c())})}};a.c.event={init:function(b,c,d,e,f){var g=c()||{};a.a.P(g,function(g){"string"==typeof g&&a.a.B(b,g,function(b){var k,l=c()[g];if(l){try{var q=a.a.la(arguments);e=f.$data;q.unshift(e);k=l.apply(e,q)}finally{!0!==k&&(b.preventDefault?b.preventDefault():b.returnValue=!1)}!1===d.get(g+"Bubble")&&(b.cancelBubble=!0,b.stopPropagation&&b.stopPropagation())}})})}};a.c.foreach={Rc:function(b){return function(){var c=b(),
d=a.a.bc(c);if(!d||"number"==typeof d.length)return{foreach:c,templateEngine:a.ba.Oa};a.a.f(c);return{foreach:d.data,as:d.as,noChildContext:d.noChildContext,includeDestroyed:d.includeDestroyed,afterAdd:d.afterAdd,beforeRemove:d.beforeRemove,afterRender:d.afterRender,beforeMove:d.beforeMove,afterMove:d.afterMove,templateEngine:a.ba.Oa}}},init:function(b,c){return a.c.template.init(b,a.c.foreach.Rc(c))},update:function(b,c,d,e,f){return a.c.template.update(b,a.c.foreach.Rc(c),d,e,f)}};a.m.Ta.foreach=
!1;a.h.ea.foreach=!0;a.c.hasfocus={init:function(b,c,d){function e(e){b.__ko_hasfocusUpdating=!0;var f=b.ownerDocument;if("activeElement"in f){var g;try{g=f.activeElement}catch(l){g=f.body}e=g===b}f=c();a.m.gb(f,d,"hasfocus",e,!0);b.__ko_hasfocusLastValue=e;b.__ko_hasfocusUpdating=!1}var f=e.bind(null,!0),g=e.bind(null,!1);a.a.B(b,"focus",f);a.a.B(b,"focusin",f);a.a.B(b,"blur",g);a.a.B(b,"focusout",g);b.__ko_hasfocusLastValue=!1},update:function(b,c){var d=!!a.a.f(c());b.__ko_hasfocusUpdating||b.__ko_hasfocusLastValue===
d||(d?b.focus():b.blur(),!d&&b.__ko_hasfocusLastValue&&b.ownerDocument.body.focus(),a.u.G(a.a.Gb,null,[b,d?"focusin":"focusout"]))}};a.m.ya.hasfocus=!0;a.c.hasFocus=a.c.hasfocus;a.m.ya.hasFocus="hasfocus";a.c.html={init:function(){return{controlsDescendantBindings:!0}},update:function(b,c){a.a.fc(b,c())}};(function(){function b(b,d,e){a.c[b]={init:function(b,c,h,m,k){var l,q,n={},r,y,p;if(d){m=h.get("as");var u=h.get("noChildContext");p=!(m&&u);n={as:m,noChildContext:u,exportDependencies:p}}y=(r=
"render"==h.get("completeOn"))||h.has(a.i.qa);a.o(function(){var h=a.a.f(c()),m=!e!==!h,u=!q,t;if(p||m!==l){y&&(k=a.i.Db(b,k));if(m){if(!d||p)n.dataDependency=a.S.o();t=d?k.createChildContext("function"==typeof h?h:c,n):a.S.ra()?k.extend(null,n):k}u&&a.S.ra()&&(q=a.a.Da(a.h.childNodes(b),!0));m?(u||a.h.xa(b,a.a.Da(q)),a.Qa(t,b)):(a.h.Fa(b),r||a.i.ma(b,a.i.H));l=m}},null,{l:b});return{controlsDescendantBindings:!0}}};a.m.Ta[b]=!1;a.h.ea[b]=!0}b("if");b("ifnot",!1,!0);b("with",!0)})();a.c.let={init:function(b,
c,d,e,f){c=f.extend(c);a.Qa(c,b);return{controlsDescendantBindings:!0}}};a.h.ea.let=!0;var Q={};a.c.options={init:function(b){if("select"!==a.a.R(b))throw Error("options binding applies only to SELECT elements");for(;0<b.length;)b.remove(0);return{controlsDescendantBindings:!0}},update:function(b,c,d){function e(){return a.a.lb(b.options,function(a){return a.selected})}function f(a,b,c){var d=typeof b;return"function"==d?b(a):"string"==d?a[b]:c}function g(c,d){if(y&&l)a.i.ma(b,a.i.H);else if(r.length){var e=
0<=a.a.A(r,a.w.M(d[0]));a.a.Zc(d[0],e);y&&!e&&a.u.G(a.a.Gb,null,[b,"change"])}}var h=b.multiple,m=0!=b.length&&h?b.scrollTop:null,k=a.a.f(c()),l=d.get("valueAllowUnset")&&d.has("value"),q=d.get("optionsIncludeDestroyed");c={};var n,r=[];l||(h?r=a.a.Nb(e(),a.w.M):0<=b.selectedIndex&&r.push(a.w.M(b.options[b.selectedIndex])));k&&("undefined"==typeof k.length&&(k=[k]),n=a.a.lb(k,function(b){return q||b===p||null===b||!a.a.f(b._destroy)}),d.has("optionsCaption")&&(k=a.a.f(d.get("optionsCaption")),null!==
k&&k!==p&&n.unshift(Q)));var y=!1;c.beforeRemove=function(a){b.removeChild(a)};k=g;d.has("optionsAfterRender")&&"function"==typeof d.get("optionsAfterRender")&&(k=function(b,c){g(0,c);a.u.G(d.get("optionsAfterRender"),null,[c[0],b!==Q?b:p])});a.a.ec(b,n,function(c,e,g){g.length&&(r=!l&&g[0].selected?[a.w.M(g[0])]:[],y=!0);e=b.ownerDocument.createElement("option");c===Q?(a.a.Cb(e,d.get("optionsCaption")),a.w.fb(e,p)):(g=f(c,d.get("optionsValue"),c),a.w.fb(e,a.a.f(g)),c=f(c,d.get("optionsText"),g),
a.a.Cb(e,c));return[e]},c,k);if(!l){var C;h?C=r.length&&e().length<r.length:C=r.length&&0<=b.selectedIndex?a.w.M(b.options[b.selectedIndex])!==r[0]:r.length||0<=b.selectedIndex;C&&a.u.G(a.a.Gb,null,[b,"change"])}(l||a.S.$a())&&a.i.ma(b,a.i.H);a.a.wd(b);m&&20<Math.abs(m-b.scrollTop)&&(b.scrollTop=m)}};a.c.options.$b=a.a.g.Z();a.c.selectedOptions={init:function(b,c,d){function e(){var e=c(),f=[];a.a.D(b.getElementsByTagName("option"),function(b){b.selected&&f.push(a.w.M(b))});a.m.gb(e,d,"selectedOptions",
f)}function f(){var d=a.a.f(c()),e=b.scrollTop;d&&"number"==typeof d.length&&a.a.D(b.getElementsByTagName("option"),function(b){var c=0<=a.a.A(d,a.w.M(b));b.selected!=c&&a.a.Zc(b,c)});b.scrollTop=e}if("select"!=a.a.R(b))throw Error("selectedOptions binding applies only to SELECT elements");var g;a.i.subscribe(b,a.i.H,function(){g?e():(a.a.B(b,"change",e),g=a.o(f,null,{l:b}))},null,{notifyImmediately:!0})},update:function(){}};a.m.ya.selectedOptions=!0;a.c.style={update:function(b,c){var d=a.a.f(c()||
{});a.a.P(d,function(c,d){d=a.a.f(d);if(null===d||d===p||!1===d)d="";if(w)w(b).css(c,d);else if(/^--/.test(c))b.style.setProperty(c,d);else{c=c.replace(/-(\w)/g,function(a,b){return b.toUpperCase()});var g=b.style[c];b.style[c]=d;d===g||b.style[c]!=g||isNaN(d)||(b.style[c]=d+"px")}})}};a.c.submit={init:function(b,c,d,e,f){if("function"!=typeof c())throw Error("The value for a submit binding must be a function");a.a.B(b,"submit",function(a){var d,e=c();try{d=e.call(f.$data,b)}finally{!0!==d&&(a.preventDefault?
a.preventDefault():a.returnValue=!1)}})}};a.c.text={init:function(){return{controlsDescendantBindings:!0}},update:function(b,c){a.a.Cb(b,c())}};a.h.ea.text=!0;(function(){if(z&&z.navigator){var b=function(a){if(a)return parseFloat(a[1])},c=z.navigator.userAgent,d,e,f,g,h;(d=z.opera&&z.opera.version&&parseInt(z.opera.version()))||(h=b(c.match(/Edge\/([^ ]+)$/)))||b(c.match(/Chrome\/([^ ]+)/))||(e=b(c.match(/Version\/([^ ]+) Safari/)))||(f=b(c.match(/Firefox\/([^ ]+)/)))||(g=a.a.W||b(c.match(/MSIE ([^ ]+)/)))||
(g=b(c.match(/rv:([^ )]+)/)))}if(8<=g&&10>g)var m=a.a.g.Z(),k=a.a.g.Z(),l=function(b){var c=this.activeElement;(c=c&&a.a.g.get(c,k))&&c(b)},q=function(b,c){var d=b.ownerDocument;a.a.g.get(d,m)||(a.a.g.set(d,m,!0),a.a.B(d,"selectionchange",l));a.a.g.set(b,k,c)};a.c.textInput={init:function(b,c,k){function l(c,d){a.a.B(b,c,d)}function m(){var d=a.a.f(c());if(null===d||d===p)d="";z!==p&&d===z?a.a.setTimeout(m,4):b.value!==d&&(D=!0,b.value=d,D=!1,w=b.value)}function t(){v||(z=b.value,v=a.a.setTimeout(A,
4))}function A(){clearTimeout(v);z=v=p;var d=b.value;w!==d&&(w=d,a.m.gb(c(),k,"textInput",d))}var w=b.value,v,z,B=9==a.a.W?t:A,D=!1;g&&l("keypress",A);11>g&&l("propertychange",function(a){D||"value"!==a.propertyName||B(a)});8==g&&(l("keyup",A),l("keydown",A));q&&(q(b,B),l("dragend",t));(!g||9<=g)&&l("input",B);5>e&&"textarea"===a.a.R(b)?(l("keydown",t),l("paste",t),l("cut",t)):11>d?l("keydown",t):4>f?(l("DOMAutoComplete",A),l("dragdrop",A),l("drop",A)):h&&"number"===b.type&&l("keydown",t);l("change",
A);l("blur",A);a.o(m,null,{l:b})}};a.m.ya.textInput=!0;a.c.textinput={preprocess:function(a,b,c){c("textInput",a)}}})();a.c.uniqueName={init:function(b,c){if(c()){var d="ko_unique_"+ ++a.c.uniqueName.rd;a.a.Yc(b,d)}}};a.c.uniqueName.rd=0;a.c.using={init:function(b,c,d,e,f){var g;d.has("as")&&(g={as:d.get("as"),noChildContext:d.get("noChildContext")});c=f.createChildContext(c,g);a.Qa(c,b);return{controlsDescendantBindings:!0}}};a.h.ea.using=!0;a.c.value={init:function(b,c,d){var e=a.a.R(b),f="input"==
e;if(!f||"checkbox"!=b.type&&"radio"!=b.type){var g=[],h=d.get("valueUpdate"),m=!1,k=null;h&&("string"==typeof h?g=[h]:g=a.a.wc(h),a.a.Ra(g,"change"));var l=function(){k=null;m=!1;var e=c(),f=a.w.M(b);a.m.gb(e,d,"value",f)};!a.a.W||!f||"text"!=b.type||"off"==b.autocomplete||b.form&&"off"==b.form.autocomplete||-1!=a.a.A(g,"propertychange")||(a.a.B(b,"propertychange",function(){m=!0}),a.a.B(b,"focus",function(){m=!1}),a.a.B(b,"blur",function(){m&&l()}));a.a.D(g,function(c){var d=l;a.a.Ud(c,"after")&&
(d=function(){k=a.w.M(b);a.a.setTimeout(l,0)},c=c.substring(5));a.a.B(b,c,d)});var q;q=f&&"file"==b.type?function(){var d=a.a.f(c());null===d||d===p||""===d?b.value="":a.u.G(l)}:function(){var f=a.a.f(c()),g=a.w.M(b);if(null!==k&&f===k)a.a.setTimeout(q,0);else if(f!==g||g===p)"select"===e?(g=d.get("valueAllowUnset"),a.w.fb(b,f,g),g||f===a.w.M(b)||a.u.G(l)):a.w.fb(b,f)};if("select"===e){var n;a.a.B(b,"change",function(){n&&l()});a.i.subscribe(b,a.i.H,function(){n?d.get("valueAllowUnset")?q():l():n=
a.o(q,null,{l:b})},null,{notifyImmediately:!0})}else a.a.B(b,"change",l),a.o(q,null,{l:b})}else a.kb(b,{checkedValue:c})},update:function(){}};a.m.ya.value=!0;a.c.visible={update:function(b,c){var d=a.a.f(c()),e="none"!=b.style.display;d&&!e?b.style.display="":!d&&e&&(b.style.display="none")}};a.c.hidden={update:function(b,c){a.c.visible.update(b,function(){return!a.a.f(c())})}};(function(b){a.c[b]={init:function(c,d,e,f,g){return a.c.event.init.call(this,c,function(){var a={};a[b]=d();return a},
e,f,g)}}})("click");a.ca=function(){};a.ca.prototype.renderTemplateSource=function(){throw Error("Override renderTemplateSource");};a.ca.prototype.createJavaScriptEvaluatorBlock=function(){throw Error("Override createJavaScriptEvaluatorBlock");};a.ca.prototype.makeTemplateSource=function(b,c){if("string"==typeof b){c=c||v;var d=c.getElementById(b);if(!d)throw Error("Cannot find template with ID "+b);return new a.C.F(d)}if(1==b.nodeType||8==b.nodeType)return new a.C.ia(b);throw Error("Unknown template type: "+
b);};a.ca.prototype.renderTemplate=function(a,c,d,e){a=this.makeTemplateSource(a,e);return this.renderTemplateSource(a,c,d,e)};a.ca.prototype.isTemplateRewritten=function(a,c){return!1===this.allowTemplateRewriting?!0:this.makeTemplateSource(a,c).data("isRewritten")};a.ca.prototype.rewriteTemplate=function(a,c,d){a=this.makeTemplateSource(a,d);c=c(a.text());a.text(c);a.data("isRewritten",!0)};a.b("templateEngine",a.ca);a.kc=function(){function b(b,c,d,h){b=a.m.ac(b);for(var m=a.m.Ta,k=0;k<b.length;k++){var l=
b[k].key;if(Object.prototype.hasOwnProperty.call(m,l)){var q=m[l];if("function"===typeof q){if(l=q(b[k].value))throw Error(l);}else if(!q)throw Error("This template engine does not support the '"+l+"' binding within its templates");}}d="ko.__tr_ambtns(function($context,$element){return(function(){return{ "+a.m.wb(b,{valueAccessors:!0})+" } })()},'"+d.toLowerCase()+"')";return h.createJavaScriptEvaluatorBlock(d)+c}var c=/(<([a-z]+\d*)(?:\s+(?!data-bind\s*=\s*)[a-z0-9\-]+(?:=(?:\"[^\"]*\"|\'[^\']*\'|[^>]*))?)*\s+)data-bind\s*=\s*(["'])([\s\S]*?)\3/gi,
d=/\x3c!--\s*ko\b\s*([\s\S]*?)\s*--\x3e/g;return{xd:function(b,c,d){c.isTemplateRewritten(b,d)||c.rewriteTemplate(b,function(b){return a.kc.Ld(b,c)},d)},Ld:function(a,f){return a.replace(c,function(a,c,d,e,l){return b(l,c,d,f)}).replace(d,function(a,c){return b(c,"\x3c!-- ko --\x3e","#comment",f)})},md:function(b,c){return a.aa.Yb(function(d,h){var m=d.nextSibling;m&&m.nodeName.toLowerCase()===c&&a.kb(m,b,h)})}}}();a.b("__tr_ambtns",a.kc.md);(function(){a.C={};a.C.F=function(b){if(this.F=b){var c=
a.a.R(b);this.cb="script"===c?1:"textarea"===c?2:"template"==c&&b.content&&11===b.content.nodeType?3:4}};a.C.F.prototype.text=function(){var b=1===this.cb?"text":2===this.cb?"value":"innerHTML";if(0==arguments.length)return this.F[b];var c=arguments[0];"innerHTML"===b?a.a.fc(this.F,c):this.F[b]=c};var b=a.a.g.Z()+"_";a.C.F.prototype.data=function(c){if(1===arguments.length)return a.a.g.get(this.F,b+c);a.a.g.set(this.F,b+c,arguments[1])};var c=a.a.g.Z();a.C.F.prototype.nodes=function(){var b=this.F;
if(0==arguments.length){var e=a.a.g.get(b,c)||{},f=e.nb||(3===this.cb?b.content:4===this.cb?b:p);if(!f||e.jd){var g=this.text();g&&g!==e.eb&&(f=a.a.Md(g,b.ownerDocument),a.a.g.set(b,c,{nb:f,eb:g,jd:!0}))}return f}e=arguments[0];this.cb!==p&&this.text("");a.a.g.set(b,c,{nb:e})};a.C.ia=function(a){this.F=a};a.C.ia.prototype=new a.C.F;a.C.ia.prototype.constructor=a.C.ia;a.C.ia.prototype.text=function(){if(0==arguments.length){var b=a.a.g.get(this.F,c)||{};b.eb===p&&b.nb&&(b.eb=b.nb.innerHTML);return b.eb}a.a.g.set(this.F,
c,{eb:arguments[0]})};a.b("templateSources",a.C);a.b("templateSources.domElement",a.C.F);a.b("templateSources.anonymousTemplate",a.C.ia)})();(function(){function b(b,c,d){var e;for(c=a.h.nextSibling(c);b&&(e=b)!==c;)b=a.h.nextSibling(e),d(e,b)}function c(c,d){if(c.length){var e=c[0],f=c[c.length-1],g=e.parentNode,h=a.ga.instance,m=h.preprocessNode;if(m){b(e,f,function(a,b){var c=a.previousSibling,d=m.call(h,a);d&&(a===e&&(e=d[0]||b),a===f&&(f=d[d.length-1]||c))});c.length=0;if(!e)return;e===f?c.push(e):
(c.push(e,f),a.a.Wa(c,g))}b(e,f,function(b){1!==b.nodeType&&8!==b.nodeType||a.vc(d,b)});b(e,f,function(b){1!==b.nodeType&&8!==b.nodeType||a.aa.cd(b,[d])});a.a.Wa(c,g)}}function d(a){return a.nodeType?a:0<a.length?a[0]:null}function e(b,e,f,h,m){m=m||{};var p=(b&&d(b)||f||{}).ownerDocument,C=m.templateEngine||g;a.kc.xd(f,C,p);f=C.renderTemplate(f,h,m,p);if("number"!=typeof f.length||0<f.length&&"number"!=typeof f[0].nodeType)throw Error("Template engine must return an array of DOM nodes");p=!1;switch(e){case "replaceChildren":a.h.xa(b,
f);p=!0;break;case "replaceNode":a.a.Xc(b,f);p=!0;break;case "ignoreTargetNode":break;default:throw Error("Unknown renderMode: "+e);}p&&(c(f,h),m.afterRender&&a.u.G(m.afterRender,null,[f,h[m.as||"$data"]]),"replaceChildren"==e&&a.i.ma(b,a.i.H));return f}function f(b,c,d){return a.O(b)?b():"function"===typeof b?b(c,d):b}var g;a.gc=function(b){if(b!=p&&!(b instanceof a.ca))throw Error("templateEngine must inherit from ko.templateEngine");g=b};a.dc=function(b,c,h,n,m){h=h||{};if((h.templateEngine||g)==
p)throw Error("Set a template engine before calling renderTemplate");m=m||"replaceChildren";if(n){var y=d(n);return a.$(function(){var g=c&&c instanceof a.fa?c:new a.fa(c,null,null,null,{exportDependencies:!0}),p=f(b,g.$data,g),g=e(n,m,p,g,h);"replaceNode"==m&&(n=g,y=d(n))},null,{Ua:function(){return!y||!a.a.Tb(y)},l:y&&"replaceNode"==m?y.parentNode:y})}return a.aa.Yb(function(d){a.dc(b,c,h,d,"replaceNode")})};a.Qd=function(b,d,g,h,m){function y(a){B.push(a);if(!D){D=!0;try{for(;B.length;)try{t(d.v(),
B[0])}finally{B.shift()}}finally{D=!1}}}function t(b,c){a.u.G(a.a.ec,null,[h,b,w,g,u,c]);a.i.ma(h,a.i.H)}function u(a,b){c(b,A);g.afterRender&&g.afterRender(b,a);A=null}function w(a,c){A=m.createChildContext(a,{as:v,noChildContext:g.noChildContext,extend:function(a){a.$index=c;v&&(a[v+"Index"]=c)}});var d=f(b,a,A);return e(h,"ignoreTargetNode",d,A,g)}var A,v=g.as,z=!1===g.includeDestroyed||a.options.foreachHidesDestroyed&&!g.includeDestroyed;if(z||g.beforeRemove||!a.Pc(d))return a.$(function(){var b=
a.a.f(d)||[];"undefined"==typeof b.length&&(b=[b]);z&&(b=a.a.lb(b,function(b){return b===p||null===b||!a.a.f(b._destroy)}));t(b)},null,{l:h});var B=[],D=!1,E=d.subscribe(y,null,"arrayChange");E.l(h);y();return E};var h=a.a.g.Z(),m=a.a.g.Z();a.c.template={init:function(b,c){var d=a.a.f(c());if("string"==typeof d||"name"in d)a.h.Fa(b);else if("nodes"in d){d=d.nodes||[];if(a.O(d))throw Error('The "nodes" option must be a plain, non-observable array.');var e=d[0]&&d[0].parentNode;e&&a.a.g.get(e,m)||(e=
a.a.Zb(d),a.a.g.set(e,m,!0));(new a.C.ia(b)).nodes(e)}else if(d=a.h.childNodes(b),0<d.length)e=a.a.Zb(d),(new a.C.ia(b)).nodes(e);else throw Error("Anonymous template defined, but no template content was provided");return{controlsDescendantBindings:!0}},update:function(b,c,d,e,f){var g=c();c=a.a.f(g);d=!0;e=null;"string"==typeof c?c={}:(g="name"in c?c.name:b,"if"in c&&(d=a.a.f(c["if"])),d&&"ifnot"in c&&(d=!a.a.f(c.ifnot)));d&&!g&&(d=!1);var m=a.a.g.get(b,h);m&&"function"==typeof m.s&&m.s();"foreach"in
c?e=a.Qd(g,d&&c.foreach||[],c,b,f):d?(d=f,"data"in c&&(d=f.createChildContext(c.data,{as:c.as,noChildContext:c.noChildContext,exportDependencies:!0})),e=a.dc(g,d,c,b)):a.h.Fa(b);a.a.g.set(b,h,!e||e.ja&&!e.ja()?p:e)}};a.m.Ta.template=function(b){b=a.m.ac(b);return 1==b.length&&b[0].unknown||a.m.Id(b,"name")?null:"This template engine does not support anonymous templates nested within its templates"};a.h.ea.template=!0})();a.b("setTemplateEngine",a.gc);a.b("renderTemplate",a.dc);a.a.Kc=function(a,c,
d){if(a.length&&c.length){var e,f,g,h,m;for(e=f=0;(!d||e<d)&&(h=a[f]);++f){for(g=0;m=c[g];++g)if(h.value===m.value){h.moved=m.index;m.moved=h.index;c.splice(g,1);e=g=0;break}e+=g}}};a.a.Qb=function(){function b(b,d,e,f,g){var h=Math.min,m=Math.max,k=[],l,p=b.length,n,r=d.length,t=r-p||1,C=p+r+1,u,v,w;for(l=0;l<=p;l++)for(v=u,k.push(u=[]),w=h(r,l+t),n=m(0,l-1);n<=w;n++)u[n]=n?l?b[l-1]===d[n-1]?v[n-1]:h(v[n]||C,u[n-1]||C)+1:n+1:l+1;h=[];m=[];t=[];l=p;for(n=r;l||n;)r=k[l][n]-1,n&&r===k[l][n-1]?m.push(h[h.length]=
{status:e,value:d[--n],index:n}):l&&r===k[l-1][n]?t.push(h[h.length]={status:f,value:b[--l],index:l}):(--n,--l,g.sparse||h.push({status:"retained",value:d[n]}));a.a.Kc(t,m,!g.dontLimitMoves&&10*p);return h.reverse()}return function(a,d,e){e="boolean"===typeof e?{dontLimitMoves:e}:e||{};a=a||[];d=d||[];return a.length<d.length?b(a,d,"added","deleted",e):b(d,a,"deleted","added",e)}}();a.b("utils.compareArrays",a.a.Qb);(function(){function b(b,c,d,h,m){var k=[],l=a.$(function(){var l=c(d,m,a.a.Wa(k,
b))||[];0<k.length&&(a.a.Xc(k,l),h&&a.u.G(h,null,[d,l,m]));k.length=0;a.a.Ob(k,l)},null,{l:b,Ua:function(){return!a.a.kd(k)}});return{Y:k,$:l.ja()?l:p}}var c=a.a.g.Z(),d=a.a.g.Z();a.a.ec=function(e,f,g,h,m,k){function l(b){x={Ba:b,Ha:a.va(w++)};v.push(x);t||(I[w-1]=x)}function q(b){x=r[b];w!==x.Ha.v()&&(D[x.Ha.v()]=x,E[w]=x);x.Ha(w++);a.a.Wa(x.Y,e);v.push(x)}function n(b,c){if(b)for(var d=0,e=c.length;d<e;d++)c[d]&&a.a.D(c[d].Y,function(a){b(a,d,c[d].Ba)})}f=f||[];"undefined"==typeof f.length&&(f=
[f]);h=h||{};var r=a.a.g.get(e,c),t=!r,v=[],u=0,w=0,A=[],z=[],B=[],D=[],E=[],I=[],x,J=0;if(t)a.a.D(f,l);else{if(!k||r&&r._countWaitingForRemove){var F=a.a.Nb(r,function(a){return a.Ba});k=a.a.Qb(F,f,{dontLimitMoves:h.dontLimitMoves,sparse:!0})}for(var F=0,G,H,K;G=k[F];F++)switch(H=G.moved,K=G.index,G.status){case "deleted":for(;u<K;)q(u++);H===p&&(x=r[u],x.$&&(x.$.s(),x.$=p),a.a.Wa(x.Y,e).length&&(h.beforeRemove&&(v.push(x),J++,x.Ba===d?x=null:B[x.Ha.v()]=x),x&&A.push.apply(A,x.Y)));u++;break;case "added":for(;w<
K;)q(u++);H!==p?(z.push(v.length),q(H)):l(G.value)}for(;w<f.length;)q(u++);v._countWaitingForRemove=J}a.a.g.set(e,c,v);n(h.beforeMove,D);a.a.D(A,h.beforeRemove?a.pa:a.removeNode);var M,P,N;try{N=e.ownerDocument.activeElement}catch(O){}if(z.length)for(;(F=z.shift())!=p;){x=v[F];for(M=p;F;)if((P=v[--F].Y)&&P.length){M=P[P.length-1];break}for(f=0;u=x.Y[f];M=u,f++)a.h.Xb(e,u,M)}for(F=0;x=v[F];F++){x.Y||a.a.extend(x,b(e,g,x.Ba,m,x.Ha));for(f=0;u=x.Y[f];M=u,f++)a.h.Xb(e,u,M);!x.Ed&&m&&(m(x.Ba,x.Y,x.Ha),
x.Ed=!0,M=x.Y[x.Y.length-1])}N&&e.ownerDocument.activeElement!=N&&"function"===typeof N.focus&&N.focus();n(h.beforeRemove,B);for(F=0;F<B.length;++F)B[F]&&(B[F].Ba=d);n(h.afterMove,E);n(h.afterAdd,I)}})();a.b("utils.setDomNodeChildrenFromArrayMapping",a.a.ec);a.ba=function(){this.allowTemplateRewriting=!1};a.ba.prototype=new a.ca;a.ba.prototype.constructor=a.ba;a.ba.prototype.renderTemplateSource=function(b,c,d,e){if(c=(9>a.a.W?0:b.nodes)?b.nodes():null)return a.a.la(c.cloneNode(!0).childNodes);b=
b.text();return a.a.wa(b,e)};a.ba.Oa=new a.ba;a.gc(a.ba.Oa);a.b("nativeTemplateEngine",a.ba);(function(){a.bb=function(){var a=this.Hd=function(){if(!w||!w.tmpl)return 0;try{if(0<=w.tmpl.tag.tmpl.open.toString().indexOf("__"))return 2}catch(a){}return 1}();this.renderTemplateSource=function(b,e,f,g){g=g||v;f=f||{};if(2>a)throw Error("Your version of jQuery.tmpl is too old. Please upgrade to jQuery.tmpl 1.0.0pre or later.");var h=b.data("precompiled");h||(h=b.text()||"",h=w.template(null,"{{ko_with $item.koBindingContext}}"+
h+"{{/ko_with}}"),b.data("precompiled",h));b=[e.$data];e=w.extend({koBindingContext:e},f.templateOptions);e=w.tmpl(h,b,e);e.appendTo(g.createElement("div"));w.fragments={};return e};this.createJavaScriptEvaluatorBlock=function(a){return"{{ko_code ((function() { return "+a+" })()) }}"};this.addTemplate=function(a,b){v.write("<script type='text/html' id='"+a+"'>"+b+"\x3c/script>")};0<a&&(w.tmpl.tag.ko_code={open:"__.push($1 || '');"},w.tmpl.tag.ko_with={open:"with($1) {",close:"} "})};a.bb.prototype=
new a.ca;a.bb.prototype.constructor=a.bb;var b=new a.bb;0<b.Hd&&a.gc(b);a.b("jqueryTmplTemplateEngine",a.bb)})()})})();})();
