/*!
 * Knockout JavaScript library v3.3.0-alpha
 * (c) Steven Sanderson - http://knockoutjs.com/
 * License: MIT (http://www.opensource.org/licenses/mit-license.php)
 */

(function() {(function(n){var v=this||(0,eval)("this"),w=v.document,O=v.navigator,t=v.jQuery,D=v.JSON;(function(n){"function"===typeof define&&define.amd?define(["exports","require"],n):"function"===typeof require&&"object"===typeof exports&&"object"===typeof module?n(module.exports||exports):n(v.ko={})})(function(P,Q){function K(a,d){return null===a||typeof a in T?a===d:!1}function U(a,d){var c;return function(){c||(c=setTimeout(function(){c=n;a()},d))}}function V(a,d){var c;return function(){clearTimeout(c);
c=setTimeout(a,d)}}function L(b,d,c,e){a.d[b]={init:function(b,k,h,l,f){var m,y;a.w(function(){var p=a.a.c(k()),q=!c!==!p,h=!y;if(h||d||q!==m)h&&a.Z.oa()&&(y=a.a.la(a.e.childNodes(b),!0)),q?(h||a.e.T(b,a.a.la(y)),a.Ja(e?e(f,p):f,b)):a.e.ma(b),m=q},null,{q:b});return{controlsDescendantBindings:!0}}};a.h.ka[b]=!1;a.e.R[b]=!0}var a="undefined"!==typeof P?P:{};a.b=function(b,d){for(var c=b.split("."),e=a,g=0;g<c.length-1;g++)e=e[c[g]];e[c[c.length-1]]=d};a.F=function(a,d,c){a[d]=c};a.version="3.3.0-alpha";
a.b("version",a.version);a.a=function(){function b(a,b){for(var f in a)a.hasOwnProperty(f)&&b(f,a[f])}function d(a,b){if(b)for(var f in b)b.hasOwnProperty(f)&&(a[f]=b[f]);return a}function c(a,b){a.__proto__=b;return a}function e(b,f,c,d){var e=b[f].match(m)||[];a.a.o(c.match(m),function(b){a.a.ga(e,b,d)});b[f]=e.join(" ")}var g={__proto__:[]}instanceof Array,k={},h={};k[O&&/Firefox\/2/i.test(O.userAgent)?"KeyboardEvent":"UIEvents"]=["keyup","keydown","keypress"];k.MouseEvents="click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave".split(" ");
b(k,function(a,b){if(b.length)for(var f=0,c=b.length;f<c;f++)h[b[f]]=a});var l={propertychange:!0},f=w&&function(){for(var a=3,b=w.createElement("div"),f=b.getElementsByTagName("i");b.innerHTML="\x3c!--[if gt IE "+ ++a+"]><i></i><![endif]--\x3e",f[0];);return 4<a?a:n}(),m=/\S+/g;return{Bb:["authenticity_token",/^__RequestVerificationToken(_.*)?$/],o:function(a,b){for(var f=0,c=a.length;f<c;f++)b(a[f],f)},m:function(a,b){if("function"==typeof Array.prototype.indexOf)return Array.prototype.indexOf.call(a,
b);for(var f=0,c=a.length;f<c;f++)if(a[f]===b)return f;return-1},vb:function(a,b,f){for(var c=0,d=a.length;c<d;c++)if(b.call(f,a[c],c))return a[c];return null},ya:function(b,f){var c=a.a.m(b,f);0<c?b.splice(c,1):0===c&&b.shift()},wb:function(b){b=b||[];for(var f=[],c=0,d=b.length;c<d;c++)0>a.a.m(f,b[c])&&f.push(b[c]);return f},Ka:function(a,b){a=a||[];for(var f=[],c=0,d=a.length;c<d;c++)f.push(b(a[c],c));return f},xa:function(a,b){a=a||[];for(var f=[],c=0,d=a.length;c<d;c++)b(a[c],c)&&f.push(a[c]);
return f},ia:function(a,b){if(b instanceof Array)a.push.apply(a,b);else for(var f=0,c=b.length;f<c;f++)a.push(b[f]);return a},ga:function(b,f,c){var d=a.a.m(a.a.cb(b),f);0>d?c&&b.push(f):c||b.splice(d,1)},za:g,extend:d,Fa:c,Ga:g?c:d,B:b,pa:function(a,b){if(!a)return a;var f={},c;for(c in a)a.hasOwnProperty(c)&&(f[c]=b(a[c],c,a));return f},Ra:function(b){for(;b.firstChild;)a.removeNode(b.firstChild)},Jb:function(b){b=a.a.O(b);for(var f=(b[0]&&b[0].ownerDocument||w).createElement("div"),c=0,d=b.length;c<
d;c++)f.appendChild(a.S(b[c]));return f},la:function(b,f){for(var c=0,d=b.length,e=[];c<d;c++){var m=b[c].cloneNode(!0);e.push(f?a.S(m):m)}return e},T:function(b,f){a.a.Ra(b);if(f)for(var c=0,d=f.length;c<d;c++)b.appendChild(f[c])},Qb:function(b,f){var c=b.nodeType?[b]:b;if(0<c.length){for(var d=c[0],e=d.parentNode,m=0,h=f.length;m<h;m++)e.insertBefore(f[m],d);m=0;for(h=c.length;m<h;m++)a.removeNode(c[m])}},na:function(a,b){if(a.length){for(b=8===b.nodeType&&b.parentNode||b;a.length&&a[0].parentNode!==
b;)a.splice(0,1);if(1<a.length){var f=a[0],c=a[a.length-1];for(a.length=0;f!==c;)if(a.push(f),f=f.nextSibling,!f)return;a.push(c)}}return a},Sb:function(a,b){7>f?a.setAttribute("selected",b):a.selected=b},ib:function(a){return null===a||a===n?"":a.trim?a.trim():a.toString().replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Ec:function(a,b){a=a||"";return b.length>a.length?!1:a.substring(0,b.length)===b},jc:function(a,b){if(a===b)return!0;if(11===a.nodeType)return!1;if(b.contains)return b.contains(3===a.nodeType?
a.parentNode:a);if(b.compareDocumentPosition)return 16==(b.compareDocumentPosition(a)&16);for(;a&&a!=b;)a=a.parentNode;return!!a},Qa:function(b){return a.a.jc(b,b.ownerDocument.documentElement)},tb:function(b){return!!a.a.vb(b,a.a.Qa)},v:function(a){return a&&a.tagName&&a.tagName.toLowerCase()},n:function(b,c,d){var e=f&&l[c];if(!e&&t)t(b).bind(c,d);else if(e||"function"!=typeof b.addEventListener)if("undefined"!=typeof b.attachEvent){var m=function(a){d.call(b,a)},h="on"+c;b.attachEvent(h,m);a.a.D.fa(b,
function(){b.detachEvent(h,m)})}else throw Error("Browser doesn't support addEventListener or attachEvent");else b.addEventListener(c,d,!1)},qa:function(b,f){if(!b||!b.nodeType)throw Error("element must be a DOM node when calling triggerEvent");var c;"input"===a.a.v(b)&&b.type&&"click"==f.toLowerCase()?(c=b.type,c="checkbox"==c||"radio"==c):c=!1;if(t&&!c)t(b).trigger(f);else if("function"==typeof w.createEvent)if("function"==typeof b.dispatchEvent)c=w.createEvent(h[f]||"HTMLEvents"),c.initEvent(f,
!0,!0,v,0,0,0,0,0,!1,!1,!1,!1,0,b),b.dispatchEvent(c);else throw Error("The supplied element doesn't support dispatchEvent");else if(c&&b.click)b.click();else if("undefined"!=typeof b.fireEvent)b.fireEvent("on"+f);else throw Error("Browser doesn't support triggering events");},c:function(b){return a.A(b)?b():b},cb:function(b){return a.A(b)?b.C():b},Ia:function(b,f,c){var d;f&&("object"===typeof b.classList?(d=b.classList[c?"add":"remove"],a.a.o(f.match(m),function(a){d.call(b.classList,a)})):"string"===
typeof b.className.baseVal?e(b.className,"baseVal",f,c):e(b,"className",f,c))},Ha:function(b,f){var c=a.a.c(f);if(null===c||c===n)c="";var d=a.e.firstChild(b);!d||3!=d.nodeType||a.e.nextSibling(d)?a.e.T(b,[b.ownerDocument.createTextNode(c)]):d.data=c;a.a.mc(b)},Rb:function(a,b){a.name=b;if(7>=f)try{a.mergeAttributes(w.createElement("<input name='"+a.name+"'/>"),!1)}catch(c){}},mc:function(a){9<=f&&(a=1==a.nodeType?a:a.parentNode,a.style&&(a.style.zoom=a.style.zoom))},kc:function(a){if(f){var b=a.style.width;
a.style.width=0;a.style.width=b}},Bc:function(b,f){b=a.a.c(b);f=a.a.c(f);for(var c=[],d=b;d<=f;d++)c.push(d);return c},O:function(a){for(var b=[],f=0,c=a.length;f<c;f++)b.push(a[f]);return b},Ic:6===f,Jc:7===f,M:f,Db:function(b,f){for(var c=a.a.O(b.getElementsByTagName("input")).concat(a.a.O(b.getElementsByTagName("textarea"))),d="string"==typeof f?function(a){return a.name===f}:function(a){return f.test(a.name)},e=[],m=c.length-1;0<=m;m--)d(c[m])&&e.push(c[m]);return e},yc:function(b){return"string"==
typeof b&&(b=a.a.ib(b))?D&&D.parse?D.parse(b):(new Function("return "+b))():null},jb:function(b,f,c){if(!D||!D.stringify)throw Error("Cannot find JSON.stringify(). Some browsers (e.g., IE < 8) don't support it natively, but you can overcome this by adding a script reference to json2.js, downloadable from http://www.json.org/json2.js");return D.stringify(a.a.c(b),f,c)},zc:function(f,c,d){d=d||{};var e=d.params||{},m=d.includeFields||this.Bb,h=f;if("object"==typeof f&&"form"===a.a.v(f))for(var h=f.action,
g=m.length-1;0<=g;g--)for(var k=a.a.Db(f,m[g]),l=k.length-1;0<=l;l--)e[k[l].name]=k[l].value;c=a.a.c(c);var r=w.createElement("form");r.style.display="none";r.action=h;r.method="post";for(var n in c)f=w.createElement("input"),f.type="hidden",f.name=n,f.value=a.a.jb(a.a.c(c[n])),r.appendChild(f);b(e,function(a,b){var f=w.createElement("input");f.type="hidden";f.name=a;f.value=b;r.appendChild(f)});w.body.appendChild(r);d.submitter?d.submitter(r):r.submit();setTimeout(function(){r.parentNode.removeChild(r)},
0)}}}();a.b("utils",a.a);a.b("utils.arrayForEach",a.a.o);a.b("utils.arrayFirst",a.a.vb);a.b("utils.arrayFilter",a.a.xa);a.b("utils.arrayGetDistinctValues",a.a.wb);a.b("utils.arrayIndexOf",a.a.m);a.b("utils.arrayMap",a.a.Ka);a.b("utils.arrayPushAll",a.a.ia);a.b("utils.arrayRemoveItem",a.a.ya);a.b("utils.extend",a.a.extend);a.b("utils.fieldsIncludedWithJsonPost",a.a.Bb);a.b("utils.getFormFields",a.a.Db);a.b("utils.peekObservable",a.a.cb);a.b("utils.postJson",a.a.zc);a.b("utils.parseJson",a.a.yc);a.b("utils.registerEventHandler",
a.a.n);a.b("utils.stringifyJson",a.a.jb);a.b("utils.range",a.a.Bc);a.b("utils.toggleDomNodeCssClass",a.a.Ia);a.b("utils.triggerEvent",a.a.qa);a.b("utils.unwrapObservable",a.a.c);a.b("utils.objectForEach",a.a.B);a.b("utils.addOrRemoveItem",a.a.ga);a.b("utils.setTextContent",a.a.Ha);a.b("unwrap",a.a.c);Function.prototype.bind||(Function.prototype.bind=function(a){var d=this;if(1===arguments.length)return function(){return d.apply(a,arguments)};var c=Array.prototype.slice.call(arguments,1);return function(){var e=
c.slice(0);e.push.apply(e,arguments);return d.apply(a,e)}});a.a.f=new function(){function a(b,k){var h=b[c];if(!h||"null"===h||!e[h]){if(!k)return n;h=b[c]="ko"+d++;e[h]={}}return e[h]}var d=0,c="__ko__"+(new Date).getTime(),e={};return{get:function(c,d){var e=a(c,!1);return e===n?n:e[d]},set:function(c,d,e){if(e!==n||a(c,!1)!==n)a(c,!0)[d]=e},clear:function(a){var b=a[c];return b?(delete e[b],a[c]=null,!0):!1},I:function(){return d++ +c}}};a.b("utils.domData",a.a.f);a.b("utils.domData.clear",a.a.f.clear);
a.a.D=new function(){function b(b,d){var e=a.a.f.get(b,c);e===n&&d&&(e=[],a.a.f.set(b,c,e));return e}function d(c){var e=b(c,!1);if(e)for(var e=e.slice(0),l=0;l<e.length;l++)e[l](c);a.a.f.clear(c);a.a.D.cleanExternalData(c);if(g[c.nodeType])for(e=c.firstChild;c=e;)e=c.nextSibling,8===c.nodeType&&d(c)}var c=a.a.f.I(),e={1:!0,8:!0,9:!0},g={1:!0,9:!0};return{fa:function(a,c){if("function"!=typeof c)throw Error("Callback must be a function");b(a,!0).push(c)},Pb:function(d,e){var g=b(d,!1);g&&(a.a.ya(g,
e),0==g.length&&a.a.f.set(d,c,n))},S:function(b){if(e[b.nodeType]&&(d(b),g[b.nodeType])){var c=[];a.a.ia(c,b.getElementsByTagName("*"));for(var l=0,f=c.length;l<f;l++)d(c[l])}return b},removeNode:function(b){a.S(b);b.parentNode&&b.parentNode.removeChild(b)},cleanExternalData:function(a){t&&"function"==typeof t.cleanData&&t.cleanData([a])}}};a.S=a.a.D.S;a.removeNode=a.a.D.removeNode;a.b("cleanNode",a.S);a.b("removeNode",a.removeNode);a.b("utils.domNodeDisposal",a.a.D);a.b("utils.domNodeDisposal.addDisposeCallback",
a.a.D.fa);a.b("utils.domNodeDisposal.removeDisposeCallback",a.a.D.Pb);(function(){a.a.ca=function(b,d){var c;if(t)if(t.parseHTML)c=t.parseHTML(b,d)||[];else{if((c=t.clean([b],d))&&c[0]){for(var e=c[0];e.parentNode&&11!==e.parentNode.nodeType;)e=e.parentNode;e.parentNode&&e.parentNode.removeChild(e)}}else{(e=d)||(e=w);c=e.parentWindow||e.defaultView||v;var g=a.a.ib(b).toLowerCase(),e=e.createElement("div"),g=g.match(/^<(thead|tbody|tfoot)/)&&[1,"<table>","</table>"]||!g.indexOf("<tr")&&[2,"<table><tbody>",
"</tbody></table>"]||(!g.indexOf("<td")||!g.indexOf("<th"))&&[3,"<table><tbody><tr>","</tr></tbody></table>"]||[0,"",""],k="ignored<div>"+g[1]+b+g[2]+"</div>";for("function"==typeof c.innerShiv?e.appendChild(c.innerShiv(k)):e.innerHTML=k;g[0]--;)e=e.lastChild;c=a.a.O(e.lastChild.childNodes)}return c};a.a.gb=function(b,d){a.a.Ra(b);d=a.a.c(d);if(null!==d&&d!==n)if("string"!=typeof d&&(d=d.toString()),t)t(b).html(d);else for(var c=a.a.ca(d,b.ownerDocument),e=0;e<c.length;e++)b.appendChild(c[e])}})();
a.b("utils.parseHtmlFragment",a.a.ca);a.b("utils.setHtml",a.a.gb);a.H=function(){function b(c,d){if(c)if(8==c.nodeType){var g=a.H.Lb(c.nodeValue);null!=g&&d.push({ic:c,wc:g})}else if(1==c.nodeType)for(var g=0,k=c.childNodes,h=k.length;g<h;g++)b(k[g],d)}var d={};return{$a:function(a){if("function"!=typeof a)throw Error("You can only pass a function to ko.memoization.memoize()");var b=(4294967296*(1+Math.random())|0).toString(16).substring(1)+(4294967296*(1+Math.random())|0).toString(16).substring(1);
d[b]=a;return"\x3c!--[ko_memo:"+b+"]--\x3e"},Wb:function(a,b){var g=d[a];if(g===n)throw Error("Couldn't find any memo with ID "+a+". Perhaps it's already been unmemoized.");try{return g.apply(null,b||[]),!0}finally{delete d[a]}},Xb:function(c,d){var g=[];b(c,g);for(var k=0,h=g.length;k<h;k++){var l=g[k].ic,f=[l];d&&a.a.ia(f,d);a.H.Wb(g[k].wc,f);l.nodeValue="";l.parentNode&&l.parentNode.removeChild(l)}},Lb:function(a){return(a=a.match(/^\[ko_memo\:(.*?)\]$/))?a[1]:null}}}();a.b("memoization",a.H);
a.b("memoization.memoize",a.H.$a);a.b("memoization.unmemoize",a.H.Wb);a.b("memoization.parseMemoText",a.H.Lb);a.b("memoization.unmemoizeDomNodeAndDescendants",a.H.Xb);a.Sa={throttle:function(b,d){b.throttleEvaluation=d;var c=null;return a.j({read:b,write:function(a){clearTimeout(c);c=setTimeout(function(){b(a)},d)}})},rateLimit:function(a,d){var c,e,g;"number"==typeof d?c=d:(c=d.timeout,e=d.method);g="notifyWhenChangesStop"==e?V:U;a.Za(function(a){return g(a,c)})},notify:function(a,d){a.equalityComparer=
"always"==d?null:K}};var T={undefined:1,"boolean":1,number:1,string:1};a.b("extenders",a.Sa);a.Ub=function(b,d,c){this.da=b;this.La=d;this.hc=c;this.Gb=!1;a.F(this,"dispose",this.p)};a.Ub.prototype.p=function(){this.Gb=!0;this.hc()};a.Q=function(){a.a.Ga(this,a.Q.fn);this.G={};this.rb=1};var H="change",z={U:function(b,d,c){var e=this;c=c||H;var g=new a.Ub(e,d?b.bind(d):b,function(){a.a.ya(e.G[c],g);e.ua&&e.ua(c)});e.ja&&e.ja(c);e.G[c]||(e.G[c]=[]);e.G[c].push(g);return g},notifySubscribers:function(b,
d){d=d||H;d===H&&this.Yb();if(this.Ba(d))try{a.k.xb();for(var c=this.G[d].slice(0),e=0,g;g=c[e];++e)g.Gb||g.La(b)}finally{a.k.end()}},Aa:function(){return this.rb},pc:function(a){return this.Aa()!==a},Yb:function(){++this.rb},Za:function(b){var d=this,c=a.A(d),e,g,k;d.ta||(d.ta=d.notifySubscribers,d.notifySubscribers=function(a,b){b&&b!==H?"beforeChange"===b?d.pb(a):d.ta(a,b):d.qb(a)});var h=b(function(){c&&k===d&&(k=d());e=!1;d.Wa(g,k)&&d.ta(g=k)});d.qb=function(a){e=!0;k=a;h()};d.pb=function(a){e||
(g=a,d.ta(a,"beforeChange"))}},Ba:function(a){return this.G[a]&&this.G[a].length},nc:function(b){if(b)return this.G[b]&&this.G[b].length||0;var d=0;a.a.B(this.G,function(a,b){d+=b.length});return d},Wa:function(a,d){return!this.equalityComparer||!this.equalityComparer(a,d)},extend:function(b){var d=this;b&&a.a.B(b,function(b,e){var g=a.Sa[b];"function"==typeof g&&(d=g(d,e)||d)});return d}};a.F(z,"subscribe",z.U);a.F(z,"extend",z.extend);a.F(z,"getSubscriptionsCount",z.nc);a.a.za&&a.a.Fa(z,Function.prototype);
a.Q.fn=z;a.Hb=function(a){return null!=a&&"function"==typeof a.U&&"function"==typeof a.notifySubscribers};a.b("subscribable",a.Q);a.b("isSubscribable",a.Hb);a.Z=a.k=function(){function b(a){c.push(e);e=a}function d(){e=c.pop()}var c=[],e,g=0;return{xb:b,end:d,Ob:function(b){if(e){if(!a.Hb(b))throw Error("Only subscribable things can act as dependencies");e.La(b,b.ac||(b.ac=++g))}},u:function(a,c,e){try{return b(),a.apply(c,e||[])}finally{d()}},oa:function(){if(e)return e.w.oa()},Ca:function(){if(e)return e.Ca}}}();
a.b("computedContext",a.Z);a.b("computedContext.getDependenciesCount",a.Z.oa);a.b("computedContext.isInitial",a.Z.Ca);a.b("computedContext.isSleeping",a.Z.Kc);a.b("ignoreDependencies",a.Hc=a.k.u);a.r=function(b){function d(){if(0<arguments.length)return d.Wa(c,arguments[0])&&(d.X(),c=arguments[0],d.W()),this;a.k.Ob(d);return c}var c=b;a.Q.call(d);a.a.Ga(d,a.r.fn);d.C=function(){return c};d.W=function(){d.notifySubscribers(c)};d.X=function(){d.notifySubscribers(c,"beforeChange")};a.F(d,"peek",d.C);
a.F(d,"valueHasMutated",d.W);a.F(d,"valueWillMutate",d.X);return d};a.r.fn={equalityComparer:K};var E=a.r.Ac="__ko_proto__";a.r.fn[E]=a.r;a.a.za&&a.a.Fa(a.r.fn,a.Q.fn);a.Ta=function(b,d){return null===b||b===n||b[E]===n?!1:b[E]===d?!0:a.Ta(b[E],d)};a.A=function(b){return a.Ta(b,a.r)};a.Da=function(b){return"function"==typeof b&&b[E]===a.r||"function"==typeof b&&b[E]===a.j&&b.qc?!0:!1};a.b("observable",a.r);a.b("isObservable",a.A);a.b("isWriteableObservable",a.Da);a.b("isWritableObservable",a.Da);
a.ba=function(b){b=b||[];if("object"!=typeof b||!("length"in b))throw Error("The argument passed when initializing an observable array must be an array, or null, or undefined.");b=a.r(b);a.a.Ga(b,a.ba.fn);return b.extend({trackArrayChanges:!0})};a.ba.fn={remove:function(b){for(var d=this.C(),c=[],e="function"!=typeof b||a.A(b)?function(a){return a===b}:b,g=0;g<d.length;g++){var k=d[g];e(k)&&(0===c.length&&this.X(),c.push(k),d.splice(g,1),g--)}c.length&&this.W();return c},removeAll:function(b){if(b===
n){var d=this.C(),c=d.slice(0);this.X();d.splice(0,d.length);this.W();return c}return b?this.remove(function(c){return 0<=a.a.m(b,c)}):[]},destroy:function(b){var d=this.C(),c="function"!=typeof b||a.A(b)?function(a){return a===b}:b;this.X();for(var e=d.length-1;0<=e;e--)c(d[e])&&(d[e]._destroy=!0);this.W()},destroyAll:function(b){return b===n?this.destroy(function(){return!0}):b?this.destroy(function(d){return 0<=a.a.m(b,d)}):[]},indexOf:function(b){var d=this();return a.a.m(d,b)},replace:function(a,
d){var c=this.indexOf(a);0<=c&&(this.X(),this.C()[c]=d,this.W())}};a.a.o("pop push reverse shift sort splice unshift".split(" "),function(b){a.ba.fn[b]=function(){var a=this.C();this.X();this.yb(a,b,arguments);a=a[b].apply(a,arguments);this.W();return a}});a.a.o(["slice"],function(b){a.ba.fn[b]=function(){var a=this();return a[b].apply(a,arguments)}});a.a.za&&a.a.Fa(a.ba.fn,a.r.fn);a.b("observableArray",a.ba);var J="arrayChange";a.Sa.trackArrayChanges=function(b){function d(){if(!c){c=!0;var f=b.notifySubscribers;
b.notifySubscribers=function(a,b){b&&b!==H||++k;return f.apply(this,arguments)};var d=[].concat(b.C()||[]);e=null;g=b.U(function(c){c=[].concat(c||[]);if(b.Ba(J)){var f;if(!e||1<k)e=a.a.Ma(d,c,{sparse:!0});f=e}d=c;e=null;k=0;f&&f.length&&b.notifySubscribers(f,J)})}}if(!b.yb){var c=!1,e=null,g,k=0,h=b.ja,l=b.ua;b.ja=function(a){h&&h.call(b,a);a===J&&d()};b.ua=function(a){l&&l.call(b,a);a!==J||b.Ba(J)||(g.p(),c=!1)};b.yb=function(b,d,g){function h(a,b,c){return l[l.length]={status:a,value:b,index:c}}
if(c&&!k){var l=[],u=b.length,x=g.length,s=0;switch(d){case "push":s=u;case "unshift":for(d=0;d<x;d++)h("added",g[d],s+d);break;case "pop":s=u-1;case "shift":u&&h("deleted",b[s],s);break;case "splice":d=Math.min(Math.max(0,0>g[0]?u+g[0]:g[0]),u);for(var u=1===x?u:Math.min(d+(g[1]||0),u),x=d+x-2,s=Math.max(u,x),G=[],A=[],n=2;d<s;++d,++n)d<u&&A.push(h("deleted",b[d],d)),d<x&&G.push(h("added",g[n],d));a.a.Cb(A,G);break;default:return}e=l}}}};a.w=a.j=function(b,d,c){function e(a,b,c){if(M&&b===f)throw Error("A 'pure' computed must not be called recursively");
B[a]=c;c.sa=F++;c.ea=b.Aa()}function g(){var a,b;for(a in B)if(B.hasOwnProperty(a)&&(b=B[a],b.da.pc(b.ea)))return!0}function k(){!r&&B&&a.a.B(B,function(a,b){b.p&&b.p()});B=null;F=0;G=!0;r=u=!1}function h(){var a=f.throttleEvaluation;a&&0<=a?(clearTimeout(R),R=setTimeout(function(){l(!0)},a)):f.nb?f.nb():l(!0)}function l(b){if(!x&&!G){if(w&&w()){if(!s){I();return}}else s=!1;x=!0;try{var c=B,m=F,g=M?n:!F;a.k.xb({La:function(a,b){G||(m&&c[b]?(e(b,a,c[b]),delete c[b],--m):B[b]||e(b,a,r?{da:a}:a.U(h)))},
w:f,Ca:g});B={};F=0;try{var l=d?A.call(d):A()}finally{a.k.end(),m&&!r&&a.a.B(c,function(a,b){b.p&&b.p()}),u=!1}f.Wa(q,l)&&(r||p(q,"beforeChange"),q=l,r?f.Yb():b&&p(q));g&&p(q,"awake")}finally{x=!1}F||I()}}function f(){if(0<arguments.length){if("function"===typeof C)C.apply(d,arguments);else throw Error("Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.");return this}a.k.Ob(f);(u||r&&g())&&l();return q}function m(){(u&&
!F||r&&g())&&l();return q}function y(){return u||0<F}function p(a,b){f.notifySubscribers(a,b)}var q,u=!0,x=!1,s=!1,G=!1,A=b,M=!1,r=!1;A&&"object"==typeof A?(c=A,A=c.read):(c=c||{},A||(A=c.read));if("function"!=typeof A)throw Error("Pass a function that returns the value of the ko.computed");var C=c.write,t=c.disposeWhenNodeIsRemoved||c.q||null,v=c.disposeWhen||c.Pa,w=v,I=k,B={},F=0,R=null;d||(d=c.owner);a.Q.call(f);a.a.Ga(f,a.j.fn);f.C=m;f.oa=function(){return F};f.qc="function"===typeof C;f.p=function(){I()};
f.$=y;var z=f.Za;f.Za=function(a){z.call(f,a);f.nb=function(){f.pb(q);u=!0;f.qb(f)}};c.pure?(r=M=!0,f.ja=function(b){if(!G&&r&&"change"==b){r=!1;if(u||g())B=null,F=0,u=!0,l();else{var c=[];a.a.B(B,function(a,b){c[b.sa]=a});a.a.o(c,function(a,b){var c=B[a],f=c.da.U(h);f.sa=b;f.ea=c.ea;B[a]=f})}G||p(q,"awake")}},f.ua=function(b){G||"change"!=b||f.Ba("change")||(a.a.B(B,function(a,b){b.p&&(B[a]={da:b.da,sa:b.sa,ea:b.ea},b.p())}),r=!0,p(n,"asleep"))},f.bc=f.Aa,f.Aa=function(){r&&(u||g())&&l();return f.bc()}):
c.deferEvaluation&&(f.ja=function(a){"change"!=a&&"beforeChange"!=a||m()});a.F(f,"peek",f.C);a.F(f,"dispose",f.p);a.F(f,"isActive",f.$);a.F(f,"getDependenciesCount",f.oa);t&&(s=!0,t.nodeType&&(w=function(){return!a.a.Qa(t)||v&&v()}));r||c.deferEvaluation||l();t&&y()&&t.nodeType&&(I=function(){a.a.D.Pb(t,I);k()},a.a.D.fa(t,I));return f};a.sc=function(b){return a.Ta(b,a.j)};z=a.r.Ac;a.j[z]=a.r;a.j.fn={equalityComparer:K};a.j.fn[z]=a.j;a.a.za&&a.a.Fa(a.j.fn,a.Q.fn);a.b("dependentObservable",a.j);a.b("computed",
a.j);a.b("isComputed",a.sc);a.Nb=function(b,d){if("function"===typeof b)return a.w(b,d,{pure:!0});b=a.a.extend({},b);b.pure=!0;return a.w(b,d)};a.b("pureComputed",a.Nb);(function(){function b(a,g,k){k=k||new c;a=g(a);if("object"!=typeof a||null===a||a===n||a instanceof Date||a instanceof String||a instanceof Number||a instanceof Boolean)return a;var h=a instanceof Array?[]:{};k.save(a,h);d(a,function(c){var f=g(a[c]);switch(typeof f){case "boolean":case "number":case "string":case "function":h[c]=
f;break;case "object":case "undefined":var d=k.get(f);h[c]=d!==n?d:b(f,g,k)}});return h}function d(a,b){if(a instanceof Array){for(var c=0;c<a.length;c++)b(c);"function"==typeof a.toJSON&&b("toJSON")}else for(c in a)b(c)}function c(){this.keys=[];this.mb=[]}a.Vb=function(c){if(0==arguments.length)throw Error("When calling ko.toJS, pass the object you want to convert.");return b(c,function(b){for(var c=0;a.A(b)&&10>c;c++)b=b();return b})};a.toJSON=function(b,c,d){b=a.Vb(b);return a.a.jb(b,c,d)};c.prototype=
{save:function(b,c){var d=a.a.m(this.keys,b);0<=d?this.mb[d]=c:(this.keys.push(b),this.mb.push(c))},get:function(b){b=a.a.m(this.keys,b);return 0<=b?this.mb[b]:n}}})();a.b("toJS",a.Vb);a.b("toJSON",a.toJSON);(function(){a.i={s:function(b){switch(a.a.v(b)){case "option":return!0===b.__ko__hasDomDataOptionValue__?a.a.f.get(b,a.d.options.ab):7>=a.a.M?b.getAttributeNode("value")&&b.getAttributeNode("value").specified?b.value:b.text:b.value;case "select":return 0<=b.selectedIndex?a.i.s(b.options[b.selectedIndex]):
n;default:return b.value}},Y:function(b,d,c){switch(a.a.v(b)){case "option":switch(typeof d){case "string":a.a.f.set(b,a.d.options.ab,n);"__ko__hasDomDataOptionValue__"in b&&delete b.__ko__hasDomDataOptionValue__;b.value=d;break;default:a.a.f.set(b,a.d.options.ab,d),b.__ko__hasDomDataOptionValue__=!0,b.value="number"===typeof d?d:""}break;case "select":if(""===d||null===d)d=n;for(var e=-1,g=0,k=b.options.length,h;g<k;++g)if(h=a.i.s(b.options[g]),h==d||""==h&&d===n){e=g;break}if(c||0<=e||d===n&&1<
b.size)b.selectedIndex=e;break;default:if(null===d||d===n)d="";b.value=d}}}})();a.b("selectExtensions",a.i);a.b("selectExtensions.readValue",a.i.s);a.b("selectExtensions.writeValue",a.i.Y);a.h=function(){function b(b){b=a.a.ib(b);123===b.charCodeAt(0)&&(b=b.slice(1,-1));var c=[],d=b.match(e),h,p=[],q=0;if(d){d.push(",");for(var u=0,x;x=d[u];++u){var s=x.charCodeAt(0);if(44===s){if(0>=q){c.push(h&&p.length?{key:h,value:p.join("")}:{unknown:h||p.join("")});h=q=0;p=[];continue}}else if(58===s){if(!q&&
!h&&1===p.length){h=p.pop();continue}}else 47===s&&u&&1<x.length?(s=d[u-1].match(g))&&!k[s[0]]&&(b=b.substr(b.indexOf(x)+1),d=b.match(e),d.push(","),u=-1,x="/"):40===s||123===s||91===s?++q:41===s||125===s||93===s?--q:h||p.length||34!==s&&39!==s||(x=x.slice(1,-1));p.push(x)}}return c}var d=["true","false","null","undefined"],c=/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i,e=RegExp("\"(?:[^\"\\\\]|\\\\.)*\"|'(?:[^'\\\\]|\\\\.)*'|/(?:[^/\\\\]|\\\\.)*/w*|[^\\s:,/][^,\"'{}()/:[\\]]*[^\\s,\"'{}()/:[\\]]|[^\\s]",
"g"),g=/[\])"'A-Za-z0-9_$]+$/,k={"in":1,"return":1,"typeof":1},h={};return{ka:[],V:h,bb:b,Ea:function(e,f){function m(b,f){var e;if(!u){var l=a.getBindingHandler(b);if(l&&l.preprocess&&!(f=l.preprocess(f,b,m)))return;if(l=h[b])e=f,0<=a.a.m(d,e)?e=!1:(l=e.match(c),e=null===l?!1:l[1]?"Object("+l[1]+")"+l[2]:e),l=e;l&&k.push("'"+b+"':function(_z){"+e+"=_z}")}q&&(f="function(){return "+f+" }");g.push("'"+b+"':"+f)}f=f||{};var g=[],k=[],q=f.valueAccessors,u=f.bindingParams,x="string"===typeof e?b(e):e;
a.a.o(x,function(a){m(a.key||a.unknown,a.value)});k.length&&m("_ko_property_writers","{"+k.join(",")+" }");return g.join(",")},vc:function(a,b){for(var c=0;c<a.length;c++)if(a[c].key==b)return!0;return!1},ra:function(b,c,d,e,h){if(b&&a.A(b))!a.Da(b)||h&&b.C()===e||b(e);else if((b=c.get("_ko_property_writers"))&&b[d])b[d](e)}}}();a.b("expressionRewriting",a.h);a.b("expressionRewriting.bindingRewriteValidators",a.h.ka);a.b("expressionRewriting.parseObjectLiteral",a.h.bb);a.b("expressionRewriting.preProcessBindings",
a.h.Ea);a.b("expressionRewriting._twoWayBindings",a.h.V);a.b("jsonExpressionRewriting",a.h);a.b("jsonExpressionRewriting.insertPropertyAccessorsIntoJson",a.h.Ea);(function(){function b(a){return 8==a.nodeType&&k.test(g?a.text:a.nodeValue)}function d(a){return 8==a.nodeType&&h.test(g?a.text:a.nodeValue)}function c(a,c){for(var e=a,h=1,g=[];e=e.nextSibling;){if(d(e)&&(h--,0===h))return g;g.push(e);b(e)&&h++}if(!c)throw Error("Cannot find closing comment tag to match: "+a.nodeValue);return null}function e(a,
b){var d=c(a,b);return d?0<d.length?d[d.length-1].nextSibling:a.nextSibling:null}var g=w&&"\x3c!--test--\x3e"===w.createComment("test").text,k=g?/^\x3c!--\s*ko(?:\s+([\s\S]+))?\s*--\x3e$/:/^\s*ko(?:\s+([\s\S]+))?\s*$/,h=g?/^\x3c!--\s*\/ko\s*--\x3e$/:/^\s*\/ko\s*$/,l={ul:!0,ol:!0};a.e={R:{},childNodes:function(a){return b(a)?c(a):a.childNodes},ma:function(c){if(b(c)){c=a.e.childNodes(c);for(var d=0,e=c.length;d<e;d++)a.removeNode(c[d])}else a.a.Ra(c)},T:function(c,d){if(b(c)){a.e.ma(c);for(var e=c.nextSibling,
h=0,g=d.length;h<g;h++)e.parentNode.insertBefore(d[h],e)}else a.a.T(c,d)},Mb:function(a,c){b(a)?a.parentNode.insertBefore(c,a.nextSibling):a.firstChild?a.insertBefore(c,a.firstChild):a.appendChild(c)},Fb:function(c,d,e){e?b(c)?c.parentNode.insertBefore(d,e.nextSibling):e.nextSibling?c.insertBefore(d,e.nextSibling):c.appendChild(d):a.e.Mb(c,d)},firstChild:function(a){return b(a)?!a.nextSibling||d(a.nextSibling)?null:a.nextSibling:a.firstChild},nextSibling:function(a){b(a)&&(a=e(a));return a.nextSibling&&
d(a.nextSibling)?null:a.nextSibling},oc:b,Gc:function(a){return(a=(g?a.text:a.nodeValue).match(k))?a[1]:null},Kb:function(c){if(l[a.a.v(c)]){var h=c.firstChild;if(h){do if(1===h.nodeType){var g;g=h.firstChild;var k=null;if(g){do if(k)k.push(g);else if(b(g)){var q=e(g,!0);q?g=q:k=[g]}else d(g)&&(k=[g]);while(g=g.nextSibling)}if(g=k)for(k=h.nextSibling,q=0;q<g.length;q++)k?c.insertBefore(g[q],k):c.appendChild(g[q])}while(h=h.nextSibling)}}}}})();a.b("virtualElements",a.e);a.b("virtualElements.allowedBindings",
a.e.R);a.b("virtualElements.emptyNode",a.e.ma);a.b("virtualElements.insertAfter",a.e.Fb);a.b("virtualElements.prepend",a.e.Mb);a.b("virtualElements.setDomNodeChildren",a.e.T);(function(){a.L=function(){this.ec={}};a.a.extend(a.L.prototype,{nodeHasBindings:function(b){switch(b.nodeType){case 1:return null!=b.getAttribute("data-bind")||a.g.getComponentNameForNode(b);case 8:return a.e.oc(b);default:return!1}},getBindings:function(b,d){var c=this.getBindingsString(b,d),c=c?this.parseBindingsString(c,
d,b):null;return a.g.sb(c,b,d,!1)},getBindingAccessors:function(b,d){var c=this.getBindingsString(b,d),c=c?this.parseBindingsString(c,d,b,{valueAccessors:!0}):null;return a.g.sb(c,b,d,!0)},getBindingsString:function(b){switch(b.nodeType){case 1:return b.getAttribute("data-bind");case 8:return a.e.Gc(b);default:return null}},parseBindingsString:function(b,d,c,e){try{var g=this.ec,k=b+(e&&e.valueAccessors||""),h;if(!(h=g[k])){var l,f="with($context){with($data||{}){return{"+a.h.Ea(b,e)+"}}}";l=new Function("$context",
"$element",f);h=g[k]=l}return h(d,c)}catch(m){throw m.message="Unable to parse bindings.\nBindings value: "+b+"\nMessage: "+m.message,m;}}});a.L.instance=new a.L})();a.b("bindingProvider",a.L);(function(){function b(a){return function(){return a}}function d(a){return a()}function c(b){return a.a.pa(a.k.u(b),function(a,c){return function(){return b()[c]}})}function e(a,b){return c(this.getBindings.bind(this,a,b))}function g(b,c,d){var f,e=a.e.firstChild(c),h=a.L.instance,g=h.preprocessNode;if(g){for(;f=
e;)e=a.e.nextSibling(f),g.call(h,f);e=a.e.firstChild(c)}for(;f=e;)e=a.e.nextSibling(f),k(b,f,d)}function k(b,c,d){var f=!0,e=1===c.nodeType;e&&a.e.Kb(c);if(e&&d||a.L.instance.nodeHasBindings(c))f=l(c,null,b,d).shouldBindDescendants;f&&!m[a.a.v(c)]&&g(b,c,!e)}function h(b){var c=[],d={},f=[];a.a.B(b,function A(e){if(!d[e]){var h=a.getBindingHandler(e);h&&(h.after&&(f.push(e),a.a.o(h.after,function(c){if(b[c]){if(-1!==a.a.m(f,c))throw Error("Cannot combine the following bindings, because they have a cyclic dependency: "+
f.join(", "));A(c)}}),f.length--),c.push({key:e,Eb:h}));d[e]=!0}});return c}function l(b,c,f,g){var m=a.a.f.get(b,y);if(!c){if(m)throw Error("You cannot apply bindings multiple times to the same element.");a.a.f.set(b,y,!0)}!m&&g&&a.Tb(b,f);var l;if(c&&"function"!==typeof c)l=c;else{var k=a.L.instance,p=k.getBindingAccessors||e,t=a.j(function(){(l=c?c(f,b):p.call(k,b,f))&&f.K&&f.K();return l},null,{q:b});l&&t.$()||(t=null)}var v;if(l){var w=t?function(a){return function(){return d(t()[a])}}:function(a){return l[a]},
z=function(){return a.a.pa(t?t():l,d)};z.get=function(a){return l[a]&&d(w(a))};z.has=function(a){return a in l};g=h(l);a.a.o(g,function(c){var d=c.Eb.init,e=c.Eb.update,h=c.key;if(8===b.nodeType&&!a.e.R[h])throw Error("The binding '"+h+"' cannot be used with virtual elements");try{"function"==typeof d&&a.k.u(function(){var a=d(b,w(h),z,f.$data,f);if(a&&a.controlsDescendantBindings){if(v!==n)throw Error("Multiple bindings ("+v+" and "+h+") are trying to control descendant bindings of the same element. You cannot use these bindings together on the same element.");
v=h}}),"function"==typeof e&&a.j(function(){e(b,w(h),z,f.$data,f)},null,{q:b})}catch(g){throw g.message='Unable to process binding "'+h+": "+l[h]+'"\nMessage: '+g.message,g;}})}return{shouldBindDescendants:v===n}}function f(b){return b&&b instanceof a.N?b:new a.N(b)}a.d={};var m={script:!0,textarea:!0};a.getBindingHandler=function(b){return a.d[b]};a.N=function(b,c,d,f){var e=this,h="function"==typeof b&&!a.A(b),g,m=a.j(function(){var g=h?b():b,l=a.a.c(g);c?(c.K&&c.K(),a.a.extend(e,c),m&&(e.K=m)):
(e.$parents=[],e.$root=l,e.ko=a);e.$rawData=g;e.$data=l;d&&(e[d]=l);f&&f(e,c,l);return e.$data},null,{Pa:function(){return g&&!a.a.tb(g)},q:!0});m.$()&&(e.K=m,m.equalityComparer=null,g=[],m.Zb=function(b){g.push(b);a.a.D.fa(b,function(b){a.a.ya(g,b);g.length||(m.p(),e.K=m=n)})})};a.N.prototype.createChildContext=function(b,c,d){return new a.N(b,this,c,function(a,b){a.$parentContext=b;a.$parent=b.$data;a.$parents=(b.$parents||[]).slice(0);a.$parents.unshift(a.$parent);d&&d(a)})};a.N.prototype.extend=
function(b){return new a.N(this.K||this.$data,this,null,function(c,d){c.$rawData=d.$rawData;a.a.extend(c,"function"==typeof b?b():b)})};var y=a.a.f.I(),p=a.a.f.I();a.Tb=function(b,c){if(2==arguments.length)a.a.f.set(b,p,c),c.K&&c.K.Zb(b);else return a.a.f.get(b,p)};a.va=function(b,c,d){1===b.nodeType&&a.e.Kb(b);return l(b,c,f(d),!0)};a.cc=function(d,e,h){h=f(h);return a.va(d,"function"===typeof e?c(e.bind(null,h,d)):a.a.pa(e,b),h)};a.Ja=function(a,b){1!==b.nodeType&&8!==b.nodeType||g(f(a),b,!0)};
a.ub=function(a,b){!t&&v.jQuery&&(t=v.jQuery);if(b&&1!==b.nodeType&&8!==b.nodeType)throw Error("ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node");b=b||v.document.body;k(f(a),b,!0)};a.Oa=function(b){switch(b.nodeType){case 1:case 8:var c=a.Tb(b);if(c)return c;if(b.parentNode)return a.Oa(b.parentNode)}return n};a.gc=function(b){return(b=a.Oa(b))?b.$data:n};a.b("bindingHandlers",a.d);a.b("applyBindings",a.ub);a.b("applyBindingsToDescendants",a.Ja);a.b("applyBindingAccessorsToNode",
a.va);a.b("applyBindingsToNode",a.cc);a.b("contextFor",a.Oa);a.b("dataFor",a.gc)})();(function(b){function d(d,e){var f=g.hasOwnProperty(d)?g[d]:b,m;f?f.U(e):(f=g[d]=new a.Q,f.U(e),c(d,function(a,b){var c=!(!b||!b.synchronous);k[d]={definition:a,tc:c};delete g[d];m||c?f.notifySubscribers(a):setTimeout(function(){f.notifySubscribers(a)},0)}),m=!0)}function c(a,b){e("getConfig",[a],function(c){c?e("loadComponent",[a,c],function(a){b(a,c)}):b(null,null)})}function e(c,d,f,g){g||(g=a.g.loaders.slice(0));
var k=g.shift();if(k){var p=k[c];if(p){var q=!1;if(p.apply(k,d.concat(function(a){q?f(null):null!==a?f(a):e(c,d,f,g)}))!==b&&(q=!0,!k.suppressLoaderExceptions))throw Error("Component loaders must supply values by invoking the callback, not by returning values synchronously.");}else e(c,d,f,g)}else f(null)}var g={},k={};a.g={get:function(c,e){var f=k.hasOwnProperty(c)?k[c]:b;f?f.tc?a.k.u(function(){e(f.definition)}):setTimeout(function(){e(f.definition)},0):d(c,e)},zb:function(a){delete k[a]},ob:e};
a.g.loaders=[];a.b("components",a.g);a.b("components.get",a.g.get);a.b("components.clearCachedDefinition",a.g.zb)})();(function(){function b(b,c,d,e){function h(){0===--x&&e(k)}var k={},x=2,s=d.template;d=d.viewModel;s?g(c,s,function(c){a.g.ob("loadTemplate",[b,c],function(a){k.template=a;h()})}):h();d?g(c,d,function(c){a.g.ob("loadViewModel",[b,c],function(a){k[l]=a;h()})}):h()}function d(a,b,c){if("function"===typeof b)c(function(a){return new b(a)});else if("function"===typeof b[l])c(b[l]);else if("instance"in
b){var e=b.instance;c(function(){return e})}else"viewModel"in b?d(a,b.viewModel,c):a("Unknown viewModel value: "+b)}function c(b){switch(a.a.v(b)){case "script":return a.a.ca(b.text);case "textarea":return a.a.ca(b.value);case "template":if(e(b.content))return a.a.la(b.content.childNodes)}return a.a.la(b.childNodes)}function e(a){return v.DocumentFragment?a instanceof DocumentFragment:a&&11===a.nodeType}function g(a,b,c){"string"===typeof b.require?Q||v.require?(Q||v.require)([b.require],c):a("Uses require, but no AMD loader is present"):
c(b)}function k(a){return function(b){throw Error("Component '"+a+"': "+b);}}var h={};a.g.Cc=function(b,c){if(!c)throw Error("Invalid configuration for "+b);if(a.g.Xa(b))throw Error("Component "+b+" is already registered");h[b]=c};a.g.Xa=function(a){return a in h};a.g.Fc=function(b){delete h[b];a.g.zb(b)};a.g.Ab={getConfig:function(a,b){b(h.hasOwnProperty(a)?h[a]:null)},loadComponent:function(a,c,d){var e=k(a);g(e,c,function(c){b(a,e,c,d)})},loadTemplate:function(b,d,g){b=k(b);if("string"===typeof d)g(a.a.ca(d));
else if(d instanceof Array)g(d);else if(e(d))g(a.a.O(d.childNodes));else if(d.element)if(d=d.element,v.HTMLElement?d instanceof HTMLElement:d&&d.tagName&&1===d.nodeType)g(c(d));else if("string"===typeof d){var h=w.getElementById(d);h?g(c(h)):b("Cannot find element with ID "+d)}else b("Unknown element type: "+d);else b("Unknown template value: "+d)},loadViewModel:function(a,b,c){d(k(a),b,c)}};var l="createViewModel";a.b("components.register",a.g.Cc);a.b("components.isRegistered",a.g.Xa);a.b("components.unregister",
a.g.Fc);a.b("components.defaultLoader",a.g.Ab);a.g.loaders.push(a.g.Ab);a.g.$b=h})();(function(){function b(b,e){var g=b.getAttribute("params");if(g){var g=d.parseBindingsString(g,e,b,{valueAccessors:!0,bindingParams:!0}),g=a.a.pa(g,function(d){return a.w(d,null,{q:b})}),k=a.a.pa(g,function(d){var e=d.C();return d.$()?a.w({read:function(){return a.a.c(d())},write:a.Da(e)&&function(a){d()(a)},q:b}):e});k.hasOwnProperty("$raw")||(k.$raw=g);return k}return{$raw:{}}}a.g.getComponentNameForNode=function(b){b=
a.a.v(b);return a.g.Xa(b)&&b};a.g.sb=function(c,d,g,k){if(1===d.nodeType){var h=a.g.getComponentNameForNode(d);if(h){c=c||{};if(c.component)throw Error('Cannot use the "component" binding on a custom element matching a component');var l={name:h,params:b(d,g)};c.component=k?function(){return l}:l}}return c};var d=new a.L;9>a.a.M&&(a.g.register=function(a){return function(b){w.createElement(b);return a.apply(this,arguments)}}(a.g.register),w.createDocumentFragment=function(b){return function(){var d=
b(),g=a.g.$b,k;for(k in g)g.hasOwnProperty(k)&&d.createElement(k);return d}}(w.createDocumentFragment))})();(function(b){function d(b,c,d){c=c.template;if(!c)throw Error("Component '"+b+"' has no template");b=a.a.la(c);a.e.T(d,b)}function c(a,b,c,d){var f=a.createViewModel;return f?f.call(a,d,{element:b,templateNodes:c}):d}var e=0;a.d.component={init:function(g,k,h,l,f){function m(){var a=y&&y.dispose;"function"===typeof a&&a.call(y);p=null}var y,p,q=a.a.O(a.e.childNodes(g));a.a.D.fa(g,m);a.w(function(){var h=
a.a.c(k()),l,s;"string"===typeof h?l=h:(l=a.a.c(h.name),s=a.a.c(h.params));if(!l)throw Error("No component name specified");var n=p=++e;a.g.get(l,function(e){if(p===n){m();if(!e)throw Error("Unknown component '"+l+"'");d(l,e,g);var h=c(e,g,q,s);e=f.createChildContext(h,b,function(a){a.$component=h;a.$componentTemplateNodes=q});y=h;a.Ja(e,g)}})},null,{q:g});return{controlsDescendantBindings:!0}}};a.e.R.component=!0})();var S={"class":"className","for":"htmlFor"};a.d.attr={update:function(b,d){var c=
a.a.c(d())||{};a.a.B(c,function(c,d){d=a.a.c(d);var k=!1===d||null===d||d===n;k&&b.removeAttribute(c);8>=a.a.M&&c in S?(c=S[c],k?b.removeAttribute(c):b[c]=d):k||b.setAttribute(c,d.toString());"name"===c&&a.a.Rb(b,k?"":d.toString())})}};(function(){a.d.checked={after:["value","attr"],init:function(b,d,c){function e(){var e=b.checked,h=y?k():e;if(!a.Z.Ca()&&(!l||e)){var g=a.k.u(d);f?m!==h?(e&&(a.a.ga(g,h,!0),a.a.ga(g,m,!1)),m=h):a.a.ga(g,h,e):a.h.ra(g,c,"checked",h,!0)}}function g(){var c=a.a.c(d());
b.checked=f?0<=a.a.m(c,k()):h?c:k()===c}var k=a.Nb(function(){return c.has("checkedValue")?a.a.c(c.get("checkedValue")):c.has("value")?a.a.c(c.get("value")):b.value}),h="checkbox"==b.type,l="radio"==b.type;if(h||l){var f=h&&a.a.c(d())instanceof Array,m=f?k():n,y=l||f;l&&!b.name&&a.d.uniqueName.init(b,function(){return!0});a.w(e,null,{q:b});a.a.n(b,"click",e);a.w(g,null,{q:b})}}};a.h.V.checked=!0;a.d.checkedValue={update:function(b,d){b.value=a.a.c(d())}}})();a.d.css={update:function(b,d){var c=a.a.c(d());
null!==c&&"object"==typeof c?a.a.B(c,function(c,d){d=a.a.c(d);a.a.Ia(b,c,d)}):(c=String(c||""),a.a.Ia(b,b.__ko__cssValue,!1),b.__ko__cssValue=c,a.a.Ia(b,c,!0))}};a.d.enable={update:function(b,d){var c=a.a.c(d());c&&b.disabled?b.removeAttribute("disabled"):c||b.disabled||(b.disabled=!0)}};a.d.disable={update:function(b,d){a.d.enable.update(b,function(){return!a.a.c(d())})}};a.d.event={init:function(b,d,c,e,g){var k=d()||{};a.a.B(k,function(h){"string"==typeof h&&a.a.n(b,h,function(b){var f,k=d()[h];
if(k){try{var y=a.a.O(arguments);e=g.$data;y.unshift(e);f=k.apply(e,y)}finally{!0!==f&&(b.preventDefault?b.preventDefault():b.returnValue=!1)}!1===c.get(h+"Bubble")&&(b.cancelBubble=!0,b.stopPropagation&&b.stopPropagation())}})})}};a.d.foreach={Ib:function(b){return function(){var d=b(),c=a.a.cb(d);if(!c||"number"==typeof c.length)return{foreach:d,templateEngine:a.P.Va};a.a.c(d);return{foreach:c.data,as:c.as,includeDestroyed:c.includeDestroyed,afterAdd:c.afterAdd,beforeRemove:c.beforeRemove,afterRender:c.afterRender,
beforeMove:c.beforeMove,afterMove:c.afterMove,templateEngine:a.P.Va}}},init:function(b,d){return a.d.template.init(b,a.d.foreach.Ib(d))},update:function(b,d,c,e,g){return a.d.template.update(b,a.d.foreach.Ib(d),c,e,g)}};a.h.ka.foreach=!1;a.e.R.foreach=!0;a.d.hasfocus={init:function(b,d,c){function e(e){b.__ko_hasfocusUpdating=!0;var g=b.ownerDocument;if("activeElement"in g){var f;try{f=g.activeElement}catch(k){f=g.body}e=f===b}g=d();a.h.ra(g,c,"hasfocus",e,!0);b.__ko_hasfocusLastValue=e;b.__ko_hasfocusUpdating=
!1}var g=e.bind(null,!0),k=e.bind(null,!1);a.a.n(b,"focus",g);a.a.n(b,"focusin",g);a.a.n(b,"blur",k);a.a.n(b,"focusout",k)},update:function(b,d){var c=!!a.a.c(d());b.__ko_hasfocusUpdating||b.__ko_hasfocusLastValue===c||(c?b.focus():b.blur(),a.k.u(a.a.qa,null,[b,c?"focusin":"focusout"]))}};a.h.V.hasfocus=!0;a.d.hasFocus=a.d.hasfocus;a.h.V.hasFocus=!0;a.d.html={init:function(){return{controlsDescendantBindings:!0}},update:function(b,d){a.a.gb(b,d())}};L("if");L("ifnot",!1,!0);L("with",!0,!1,function(a,
d){return a.createChildContext(d)});var N={};a.d.options={init:function(b){if("select"!==a.a.v(b))throw Error("options binding applies only to SELECT elements");for(;0<b.length;)b.remove(0);return{controlsDescendantBindings:!0}},update:function(b,d,c){function e(){return a.a.xa(b.options,function(a){return a.selected})}function g(a,b,c){var d=typeof b;return"function"==d?b(a):"string"==d?a[b]:c}function k(d,f){if(u&&m)a.i.Y(b,a.a.c(c.get("value")),!0);else if(q.length){var e=0<=a.a.m(q,a.i.s(f[0]));
a.a.Sb(f[0],e);u&&!e&&a.k.u(a.a.qa,null,[b,"change"])}}var h=b.multiple,l=0!=b.length&&h?b.scrollTop:null,f=a.a.c(d()),m=c.get("valueAllowUnset")&&c.has("value"),y=c.get("optionsIncludeDestroyed");d={};var p,q=[];m||(h?q=a.a.Ka(e(),a.i.s):0<=b.selectedIndex&&q.push(a.i.s(b.options[b.selectedIndex])));f&&("undefined"==typeof f.length&&(f=[f]),p=a.a.xa(f,function(b){return y||b===n||null===b||!a.a.c(b._destroy)}),c.has("optionsCaption")&&(f=a.a.c(c.get("optionsCaption")),null!==f&&f!==n&&p.unshift(N)));
var u=!1;d.beforeRemove=function(a){b.removeChild(a)};f=k;c.has("optionsAfterRender")&&"function"==typeof c.get("optionsAfterRender")&&(f=function(b,d){k(0,d);a.k.u(c.get("optionsAfterRender"),null,[d[0],b!==N?b:n])});a.a.fb(b,p,function(d,f,e){e.length&&(q=!m&&e[0].selected?[a.i.s(e[0])]:[],u=!0);f=b.ownerDocument.createElement("option");d===N?(a.a.Ha(f,c.get("optionsCaption")),a.i.Y(f,n)):(e=g(d,c.get("optionsValue"),d),a.i.Y(f,a.a.c(e)),d=g(d,c.get("optionsText"),e),a.a.Ha(f,d));return[f]},d,f);
a.k.u(function(){m?a.i.Y(b,a.a.c(c.get("value")),!0):(h?q.length&&e().length<q.length:q.length&&0<=b.selectedIndex?a.i.s(b.options[b.selectedIndex])!==q[0]:q.length||0<=b.selectedIndex)&&a.a.qa(b,"change")});a.a.kc(b);l&&20<Math.abs(l-b.scrollTop)&&(b.scrollTop=l)}};a.d.options.ab=a.a.f.I();a.d.selectedOptions={after:["options","foreach"],init:function(b,d,c){a.a.n(b,"change",function(){var e=d(),g=[];a.a.o(b.getElementsByTagName("option"),function(b){b.selected&&g.push(a.i.s(b))});a.h.ra(e,c,"selectedOptions",
g)})},update:function(b,d){if("select"!=a.a.v(b))throw Error("values binding applies only to SELECT elements");var c=a.a.c(d());c&&"number"==typeof c.length&&a.a.o(b.getElementsByTagName("option"),function(b){var d=0<=a.a.m(c,a.i.s(b));a.a.Sb(b,d)})}};a.h.V.selectedOptions=!0;a.d.style={update:function(b,d){var c=a.a.c(d()||{});a.a.B(c,function(c,d){d=a.a.c(d);if(null===d||d===n||!1===d)d="";b.style[c]=d})}};a.d.submit={init:function(b,d,c,e,g){if("function"!=typeof d())throw Error("The value for a submit binding must be a function");
a.a.n(b,"submit",function(a){var c,e=d();try{c=e.call(g.$data,b)}finally{!0!==c&&(a.preventDefault?a.preventDefault():a.returnValue=!1)}})}};a.d.text={init:function(){return{controlsDescendantBindings:!0}},update:function(b,d){a.a.Ha(b,d())}};a.e.R.text=!0;(function(){if(v&&v.navigator)var b=function(a){if(a)return parseFloat(a[1])},d=v.opera&&v.opera.version&&parseInt(v.opera.version()),c=v.navigator.userAgent,e=b(c.match(/^(?:(?!chrome).)*version\/([^ ]*) safari/i)),g=b(c.match(/Firefox\/([^ ]*)/));
if(10>a.a.M)var k=a.a.f.I(),h=a.a.f.I(),l=function(b){var c=this.activeElement;(c=c&&a.a.f.get(c,h))&&c(b)},f=function(b,c){var d=b.ownerDocument;a.a.f.get(d,k)||(a.a.f.set(d,k,!0),a.a.n(d,"selectionchange",l));a.a.f.set(b,h,c)};a.d.textInput={init:function(b,c,h){function k(c,d){a.a.n(b,c,d)}function l(){var d=a.a.c(c());if(null===d||d===n)d="";w!==n&&d===w?setTimeout(l,4):b.value!==d&&(t=d,b.value=d)}function x(){v||(w=b.value,v=setTimeout(s,4))}function s(){clearTimeout(v);w=v=n;var d=b.value;
t!==d&&(t=d,a.h.ra(c(),h,"textInput",d))}var t=b.value,v,w;10>a.a.M?(k("propertychange",function(a){"value"===a.propertyName&&s()}),8==a.a.M&&(k("keyup",s),k("keydown",s)),8<=a.a.M&&(f(b,s),k("dragend",x))):(k("input",s),5>e&&"textarea"===a.a.v(b)?(k("keydown",x),k("paste",x),k("cut",x)):11>d?k("keydown",x):4>g&&(k("DOMAutoComplete",s),k("dragdrop",s),k("drop",s)));k("change",s);a.w(l,null,{q:b})}};a.h.V.textInput=!0;a.d.textinput={preprocess:function(a,b,c){c("textInput",a)}}})();a.d.uniqueName=
{init:function(b,d){if(d()){var c="ko_unique_"+ ++a.d.uniqueName.fc;a.a.Rb(b,c)}}};a.d.uniqueName.fc=0;a.d.value={after:["options","foreach"],init:function(b,d,c){if("input"!=b.tagName.toLowerCase()||"checkbox"!=b.type&&"radio"!=b.type){var e=["change"],g=c.get("valueUpdate"),k=!1,h=null;g&&("string"==typeof g&&(g=[g]),a.a.ia(e,g),e=a.a.wb(e));var l=function(){h=null;k=!1;var f=d(),e=a.i.s(b);a.h.ra(f,c,"value",e)};!a.a.M||"input"!=b.tagName.toLowerCase()||"text"!=b.type||"off"==b.autocomplete||b.form&&
"off"==b.form.autocomplete||-1!=a.a.m(e,"propertychange")||(a.a.n(b,"propertychange",function(){k=!0}),a.a.n(b,"focus",function(){k=!1}),a.a.n(b,"blur",function(){k&&l()}));a.a.o(e,function(c){var d=l;a.a.Ec(c,"after")&&(d=function(){h=a.i.s(b);setTimeout(l,0)},c=c.substring(5));a.a.n(b,c,d)});var f=function(){var e=a.a.c(d()),g=a.i.s(b);if(null!==h&&e===h)setTimeout(f,0);else if(e!==g)if("select"===a.a.v(b)){var k=c.get("valueAllowUnset"),g=function(){a.i.Y(b,e,k)};g();k||e===a.i.s(b)?setTimeout(g,
0):a.k.u(a.a.qa,null,[b,"change"])}else a.i.Y(b,e)};a.w(f,null,{q:b})}else a.va(b,{checkedValue:d})},update:function(){}};a.h.V.value=!0;a.d.visible={update:function(b,d){var c=a.a.c(d()),e="none"!=b.style.display;c&&!e?b.style.display="":!c&&e&&(b.style.display="none")}};(function(b){a.d[b]={init:function(d,c,e,g,k){return a.d.event.init.call(this,d,function(){var a={};a[b]=c();return a},e,g,k)}}})("click");a.J=function(){};a.J.prototype.renderTemplateSource=function(){throw Error("Override renderTemplateSource");
};a.J.prototype.createJavaScriptEvaluatorBlock=function(){throw Error("Override createJavaScriptEvaluatorBlock");};a.J.prototype.makeTemplateSource=function(b,d){if("string"==typeof b){d=d||w;var c=d.getElementById(b);if(!c)throw Error("Cannot find template with ID "+b);return new a.t.l(c)}if(1==b.nodeType||8==b.nodeType)return new a.t.ha(b);throw Error("Unknown template type: "+b);};a.J.prototype.renderTemplate=function(a,d,c,e){a=this.makeTemplateSource(a,e);return this.renderTemplateSource(a,d,
c,e)};a.J.prototype.isTemplateRewritten=function(a,d){return!1===this.allowTemplateRewriting?!0:this.makeTemplateSource(a,d).data("isRewritten")};a.J.prototype.rewriteTemplate=function(a,d,c){a=this.makeTemplateSource(a,c);d=d(a.text());a.text(d);a.data("isRewritten",!0)};a.b("templateEngine",a.J);a.kb=function(){function b(b,c,d,h){b=a.h.bb(b);for(var l=a.h.ka,f=0;f<b.length;f++){var m=b[f].key;if(l.hasOwnProperty(m)){var n=l[m];if("function"===typeof n){if(m=n(b[f].value))throw Error(m);}else if(!n)throw Error("This template engine does not support the '"+
m+"' binding within its templates");}}d="ko.__tr_ambtns(function($context,$element){return(function(){return{ "+a.h.Ea(b,{valueAccessors:!0})+" } })()},'"+d.toLowerCase()+"')";return h.createJavaScriptEvaluatorBlock(d)+c}var d=/(<([a-z]+\d*)(?:\s+(?!data-bind\s*=\s*)[a-z0-9\-]+(?:=(?:\"[^\"]*\"|\'[^\']*\'|[^>]*))?)*\s+)data-bind\s*=\s*(["'])([\s\S]*?)\3/gi,c=/\x3c!--\s*ko\b\s*([\s\S]*?)\s*--\x3e/g;return{lc:function(b,c,d){c.isTemplateRewritten(b,d)||c.rewriteTemplate(b,function(b){return a.kb.xc(b,
c)},d)},xc:function(a,g){return a.replace(d,function(a,c,d,f,e){return b(e,c,d,g)}).replace(c,function(a,c){return b(c,"\x3c!-- ko --\x3e","#comment",g)})},dc:function(b,c){return a.H.$a(function(d,h){var l=d.nextSibling;l&&l.nodeName.toLowerCase()===c&&a.va(l,b,h)})}}}();a.b("__tr_ambtns",a.kb.dc);(function(){a.t={};a.t.l=function(a){this.l=a};a.t.l.prototype.text=function(){var b=a.a.v(this.l),b="script"===b?"text":"textarea"===b?"value":"innerHTML";if(0==arguments.length)return this.l[b];var d=
arguments[0];"innerHTML"===b?a.a.gb(this.l,d):this.l[b]=d};var b=a.a.f.I()+"_";a.t.l.prototype.data=function(c){if(1===arguments.length)return a.a.f.get(this.l,b+c);a.a.f.set(this.l,b+c,arguments[1])};var d=a.a.f.I();a.t.ha=function(a){this.l=a};a.t.ha.prototype=new a.t.l;a.t.ha.prototype.text=function(){if(0==arguments.length){var b=a.a.f.get(this.l,d)||{};b.lb===n&&b.Na&&(b.lb=b.Na.innerHTML);return b.lb}a.a.f.set(this.l,d,{lb:arguments[0]})};a.t.l.prototype.nodes=function(){if(0==arguments.length)return(a.a.f.get(this.l,
d)||{}).Na;a.a.f.set(this.l,d,{Na:arguments[0]})};a.b("templateSources",a.t);a.b("templateSources.domElement",a.t.l);a.b("templateSources.anonymousTemplate",a.t.ha)})();(function(){function b(b,c,d){var e;for(c=a.e.nextSibling(c);b&&(e=b)!==c;)b=a.e.nextSibling(e),d(e,b)}function d(c,d){if(c.length){var f=c[0],e=c[c.length-1],g=f.parentNode,k=a.L.instance,q=k.preprocessNode;if(q){b(f,e,function(a,b){var c=a.previousSibling,d=q.call(k,a);d&&(a===f&&(f=d[0]||b),a===e&&(e=d[d.length-1]||c))});c.length=
0;if(!f)return;f===e?c.push(f):(c.push(f,e),a.a.na(c,g))}b(f,e,function(b){1!==b.nodeType&&8!==b.nodeType||a.ub(d,b)});b(f,e,function(b){1!==b.nodeType&&8!==b.nodeType||a.H.Xb(b,[d])});a.a.na(c,g)}}function c(a){return a.nodeType?a:0<a.length?a[0]:null}function e(b,e,f,k,n){n=n||{};var p=(b&&c(b)||f||{}).ownerDocument,q=n.templateEngine||g;a.kb.lc(f,q,p);f=q.renderTemplate(f,k,n,p);if("number"!=typeof f.length||0<f.length&&"number"!=typeof f[0].nodeType)throw Error("Template engine must return an array of DOM nodes");
p=!1;switch(e){case "replaceChildren":a.e.T(b,f);p=!0;break;case "replaceNode":a.a.Qb(b,f);p=!0;break;case "ignoreTargetNode":break;default:throw Error("Unknown renderMode: "+e);}p&&(d(f,k),n.afterRender&&a.k.u(n.afterRender,null,[f,k.$data]));return f}var g;a.hb=function(b){if(b!=n&&!(b instanceof a.J))throw Error("templateEngine must inherit from ko.templateEngine");g=b};a.eb=function(b,d,f,k,y){f=f||{};if((f.templateEngine||g)==n)throw Error("Set a template engine before calling renderTemplate");
y=y||"replaceChildren";if(k){var p=c(k);return a.j(function(){var g=d&&d instanceof a.N?d:new a.N(a.a.c(d)),n=a.A(b)?b():"function"===typeof b?b(g.$data,g):b,g=e(k,y,n,g,f);"replaceNode"==y&&(k=g,p=c(k))},null,{Pa:function(){return!p||!a.a.Qa(p)},q:p&&"replaceNode"==y?p.parentNode:p})}return a.H.$a(function(c){a.eb(b,d,f,c,"replaceNode")})};a.Dc=function(b,c,f,g,k){function p(a,b){d(b,u);f.afterRender&&f.afterRender(b,a);u=null}function q(c,d){u=k.createChildContext(c,f.as,function(a){a.$index=d});
var g=a.A(b)?b():"function"===typeof b?b(c,u):b;return e(null,"ignoreTargetNode",g,u,f)}var u;return a.j(function(){var b=a.a.c(c)||[];"undefined"==typeof b.length&&(b=[b]);b=a.a.xa(b,function(b){return f.includeDestroyed||b===n||null===b||!a.a.c(b._destroy)});a.k.u(a.a.fb,null,[g,b,q,f,p])},null,{q:g})};var k=a.a.f.I();a.d.template={init:function(b,c){var d=a.a.c(c());if("string"==typeof d||d.name)a.e.ma(b);else{if("nodes"in d){if(d=d.nodes||[],a.A(d))throw Error('The "nodes" option must be a plain, non-observable array.');
}else d=a.e.childNodes(b);d=a.a.Jb(d);(new a.t.ha(b)).nodes(d)}return{controlsDescendantBindings:!0}},update:function(b,c,d,e,g){var p=c(),q;c=a.a.c(p);d=!0;e=null;"string"==typeof c?c={}:(p=c.name,"if"in c&&(d=a.a.c(c["if"])),d&&"ifnot"in c&&(d=!a.a.c(c.ifnot)),q=a.a.c(c.data));"foreach"in c?e=a.Dc(p||b,d&&c.foreach||[],c,b,g):d?(g="data"in c?g.createChildContext(q,c.as):g,e=a.eb(p||b,g,c,b)):a.e.ma(b);g=e;(q=a.a.f.get(b,k))&&"function"==typeof q.p&&q.p();a.a.f.set(b,k,g&&g.$()?g:n)}};a.h.ka.template=
function(b){b=a.h.bb(b);return 1==b.length&&b[0].unknown||a.h.vc(b,"name")?null:"This template engine does not support anonymous templates nested within its templates"};a.e.R.template=!0})();a.b("setTemplateEngine",a.hb);a.b("renderTemplate",a.eb);a.a.Cb=function(a,d,c){if(a.length&&d.length){var e,g,k,h,l;for(e=g=0;(!c||e<c)&&(h=a[g]);++g){for(k=0;l=d[k];++k)if(h.value===l.value){h.moved=l.index;l.moved=h.index;d.splice(k,1);e=k=0;break}e+=k}}};a.a.Ma=function(){function b(b,c,e,g,k){var h=Math.min,
l=Math.max,f=[],m,n=b.length,p,q=c.length,u=q-n||1,t=n+q+1,s,v,w;for(m=0;m<=n;m++)for(v=s,f.push(s=[]),w=h(q,m+u),p=l(0,m-1);p<=w;p++)s[p]=p?m?b[m-1]===c[p-1]?v[p-1]:h(v[p]||t,s[p-1]||t)+1:p+1:m+1;h=[];l=[];u=[];m=n;for(p=q;m||p;)q=f[m][p]-1,p&&q===f[m][p-1]?l.push(h[h.length]={status:e,value:c[--p],index:p}):m&&q===f[m-1][p]?u.push(h[h.length]={status:g,value:b[--m],index:m}):(--p,--m,k.sparse||h.push({status:"retained",value:c[p]}));a.a.Cb(l,u,10*n);return h.reverse()}return function(a,c,e){e="boolean"===
typeof e?{dontLimitMoves:e}:e||{};a=a||[];c=c||[];return a.length<=c.length?b(a,c,"added","deleted",e):b(c,a,"deleted","added",e)}}();a.b("utils.compareArrays",a.a.Ma);(function(){function b(b,d,g,k,h){var l=[],f=a.j(function(){var f=d(g,h,a.a.na(l,b))||[];0<l.length&&(a.a.Qb(l,f),k&&a.k.u(k,null,[g,f,h]));l.length=0;a.a.ia(l,f)},null,{q:b,Pa:function(){return!a.a.tb(l)}});return{aa:l,j:f.$()?f:n}}var d=a.a.f.I();a.a.fb=function(c,e,g,k,h){function l(b,d){r=t[d];s!==d&&(z[b]=r);r.Ua(s++);a.a.na(r.aa,
c);u.push(r);A.push(r)}function f(b,c){if(b)for(var d=0,e=c.length;d<e;d++)c[d]&&a.a.o(c[d].aa,function(a){b(a,d,c[d].wa)})}e=e||[];k=k||{};var m=a.a.f.get(c,d)===n,t=a.a.f.get(c,d)||[],p=a.a.Ka(t,function(a){return a.wa}),q=a.a.Ma(p,e,k.dontLimitMoves),u=[],v=0,s=0,w=[],A=[];e=[];for(var z=[],p=[],r,C=0,D,E;D=q[C];C++)switch(E=D.moved,D.status){case "deleted":E===n&&(r=t[v],r.j&&r.j.p(),w.push.apply(w,a.a.na(r.aa,c)),k.beforeRemove&&(e[C]=r,A.push(r)));v++;break;case "retained":l(C,v++);break;case "added":E!==
n?l(C,E):(r={wa:D.value,Ua:a.r(s++)},u.push(r),A.push(r),m||(p[C]=r))}f(k.beforeMove,z);a.a.o(w,k.beforeRemove?a.S:a.removeNode);for(var C=0,m=a.e.firstChild(c),H;r=A[C];C++){r.aa||a.a.extend(r,b(c,g,r.wa,h,r.Ua));for(v=0;q=r.aa[v];m=q.nextSibling,H=q,v++)q!==m&&a.e.Fb(c,q,H);!r.rc&&h&&(h(r.wa,r.aa,r.Ua),r.rc=!0)}f(k.beforeRemove,e);f(k.afterMove,z);f(k.afterAdd,p);a.a.f.set(c,d,u)}})();a.b("utils.setDomNodeChildrenFromArrayMapping",a.a.fb);a.P=function(){this.allowTemplateRewriting=!1};a.P.prototype=
new a.J;a.P.prototype.renderTemplateSource=function(b,d,c,e){if(d=(9>a.a.M?0:b.nodes)?b.nodes():null)return a.a.O(d.cloneNode(!0).childNodes);b=b.text();return a.a.ca(b,e)};a.P.Va=new a.P;a.hb(a.P.Va);a.b("nativeTemplateEngine",a.P);(function(){a.Ya=function(){var a=this.uc=function(){if(!t||!t.tmpl)return 0;try{if(0<=t.tmpl.tag.tmpl.open.toString().indexOf("__"))return 2}catch(a){}return 1}();this.renderTemplateSource=function(b,e,g,k){k=k||w;g=g||{};if(2>a)throw Error("Your version of jQuery.tmpl is too old. Please upgrade to jQuery.tmpl 1.0.0pre or later.");
var h=b.data("precompiled");h||(h=b.text()||"",h=t.template(null,"{{ko_with $item.koBindingContext}}"+h+"{{/ko_with}}"),b.data("precompiled",h));b=[e.$data];e=t.extend({koBindingContext:e},g.templateOptions);e=t.tmpl(h,b,e);e.appendTo(k.createElement("div"));t.fragments={};return e};this.createJavaScriptEvaluatorBlock=function(a){return"{{ko_code ((function() { return "+a+" })()) }}"};this.addTemplate=function(a,b){w.write("<script type='text/html' id='"+a+"'>"+b+"\x3c/script>")};0<a&&(t.tmpl.tag.ko_code=
{open:"__.push($1 || '');"},t.tmpl.tag.ko_with={open:"with($1) {",close:"} "})};a.Ya.prototype=new a.J;var b=new a.Ya;0<b.uc&&a.hb(b);a.b("jqueryTmplTemplateEngine",a.Ya)})()})})();})();
