/*!
 * Knockout JavaScript library v3.2.0-beta
 * (c) Steven Sanderson - http://knockoutjs.com/
 * License: MIT (http://www.opensource.org/licenses/mit-license.php)
 */

(function() {(function(q){var x=this||(0,eval)("this"),v=x.document,L=x.navigator,s=x.jQuery,D=x.JSON;(function(q){"function"===typeof require&&"object"===typeof exports&&"object"===typeof module?q(module.exports||exports,require):"function"===typeof define&&define.amd?define(["exports","require"],q):q(x.ko={})})(function(M,N){function H(a,d){return null===a||typeof a in R?a===d:!1}function S(a,d){var c;return function(){c||(c=setTimeout(function(){c=q;a()},d))}}function T(a,d){var c;return function(){clearTimeout(c);
c=setTimeout(a,d)}}function I(b,d,c,f){a.d[b]={init:function(b,k,h,e,m){var n,p;a.t(function(){var e=a.a.c(k()),h=!c!==!e,y=!p;if(y||d||h!==n)y&&a.W.ja()&&(p=a.a.ga(a.e.childNodes(b),!0)),h?(y||a.e.S(b,a.a.ga(p)),a.Da(f?f(m,e):m,b)):a.e.ha(b),n=h},null,{q:b});return{controlsDescendantBindings:!0}}};a.h.fa[b]=!1;a.e.P[b]=!0}var a="undefined"!==typeof M?M:{};a.b=function(b,d){for(var c=b.split("."),f=a,g=0;g<c.length-1;g++)f=f[c[g]];f[c[c.length-1]]=d};a.w=function(a,d,c){a[d]=c};a.version="3.2.0-beta";
a.b("version",a.version);a.a=function(){function b(a,b){for(var c in a)a.hasOwnProperty(c)&&b(c,a[c])}function d(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a}function c(a,b){a.__proto__=b;return a}var f={__proto__:[]}instanceof Array,g={},k={};g[L&&/Firefox\/2/i.test(L.userAgent)?"KeyboardEvent":"UIEvents"]=["keyup","keydown","keypress"];g.MouseEvents="click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave".split(" ");b(g,function(a,b){if(b.length)for(var c=
0,e=b.length;c<e;c++)k[b[c]]=a});var h={propertychange:!0},e=v&&function(){for(var a=3,b=v.createElement("div"),c=b.getElementsByTagName("i");b.innerHTML="\x3c!--[if gt IE "+ ++a+"]><i></i><![endif]--\x3e",c[0];);return 4<a?a:q}();return{ub:["authenticity_token",/^__RequestVerificationToken(_.*)?$/],s:function(a,b){for(var c=0,e=a.length;c<e;c++)b(a[c],c)},m:function(a,b){if("function"==typeof Array.prototype.indexOf)return Array.prototype.indexOf.call(a,b);for(var c=0,e=a.length;c<e;c++)if(a[c]===
b)return c;return-1},pb:function(a,b,c){for(var e=0,d=a.length;e<d;e++)if(b.call(c,a[e],e))return a[e];return null},sa:function(m,b){var c=a.a.m(m,b);0<c?m.splice(c,1):0===c&&m.shift()},qb:function(m){m=m||[];for(var b=[],c=0,e=m.length;c<e;c++)0>a.a.m(b,m[c])&&b.push(m[c]);return b},Ea:function(a,b){a=a||[];for(var c=[],e=0,d=a.length;e<d;e++)c.push(b(a[e],e));return c},ra:function(a,b){a=a||[];for(var c=[],e=0,d=a.length;e<d;e++)b(a[e],e)&&c.push(a[e]);return c},ea:function(a,b){if(b instanceof
Array)a.push.apply(a,b);else for(var c=0,e=b.length;c<e;c++)a.push(b[c]);return a},ca:function(b,c,e){var d=a.a.m(a.a.Xa(b),c);0>d?e&&b.push(c):e||b.splice(d,1)},va:f,extend:d,ya:c,za:f?c:d,F:b,ma:function(a,b){if(!a)return a;var c={},e;for(e in a)a.hasOwnProperty(e)&&(c[e]=b(a[e],e,a));return c},La:function(b){for(;b.firstChild;)a.removeNode(b.firstChild)},oc:function(b){b=a.a.R(b);for(var c=v.createElement("div"),e=0,d=b.length;e<d;e++)c.appendChild(a.Q(b[e]));return c},ga:function(b,c){for(var e=
0,d=b.length,h=[];e<d;e++){var f=b[e].cloneNode(!0);h.push(c?a.Q(f):f)}return h},S:function(b,c){a.a.La(b);if(c)for(var e=0,d=c.length;e<d;e++)b.appendChild(c[e])},Lb:function(b,c){var e=b.nodeType?[b]:b;if(0<e.length){for(var d=e[0],h=d.parentNode,f=0,g=c.length;f<g;f++)h.insertBefore(c[f],d);f=0;for(g=e.length;f<g;f++)a.removeNode(e[f])}},ia:function(a,b){if(a.length){for(b=8===b.nodeType&&b.parentNode||b;a.length&&a[0].parentNode!==b;)a.shift();if(1<a.length){var c=a[0],e=a[a.length-1];for(a.length=
0;c!==e;)if(a.push(c),c=c.nextSibling,!c)return;a.push(e)}}return a},Nb:function(a,b){7>e?a.setAttribute("selected",b):a.selected=b},Aa:function(a){return null===a||a===q?"":a.trim?a.trim():a.toString().replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Bc:function(b,c){for(var e=[],d=(b||"").split(c),h=0,f=d.length;h<f;h++){var g=a.a.Aa(d[h]);""!==g&&e.push(g)}return e},vc:function(a,b){a=a||"";return b.length>a.length?!1:a.substring(0,b.length)===b},cc:function(a,b){if(a===b)return!0;if(11===a.nodeType)return!1;
if(b.contains)return b.contains(3===a.nodeType?a.parentNode:a);if(b.compareDocumentPosition)return 16==(b.compareDocumentPosition(a)&16);for(;a&&a!=b;)a=a.parentNode;return!!a},Ka:function(b){return a.a.cc(b,b.ownerDocument.documentElement)},nb:function(b){return!!a.a.pb(b,a.a.Ka)},C:function(a){return a&&a.tagName&&a.tagName.toLowerCase()},r:function(b,c,d){var f=e&&h[c];if(!f&&s)s(b).bind(c,d);else if(f||"function"!=typeof b.addEventListener)if("undefined"!=typeof b.attachEvent){var g=function(a){d.call(b,
a)},k="on"+c;b.attachEvent(k,g);a.a.v.ba(b,function(){b.detachEvent(k,g)})}else throw Error("Browser doesn't support addEventListener or attachEvent");else b.addEventListener(c,d,!1)},na:function(b,c){if(!b||!b.nodeType)throw Error("element must be a DOM node when calling triggerEvent");var e;"input"===a.a.C(b)&&b.type&&"click"==c.toLowerCase()?(e=b.type,e="checkbox"==e||"radio"==e):e=!1;if(s&&!e)s(b).trigger(c);else if("function"==typeof v.createEvent)if("function"==typeof b.dispatchEvent)e=v.createEvent(k[c]||
"HTMLEvents"),e.initEvent(c,!0,!0,x,0,0,0,0,0,!1,!1,!1,!1,0,b),b.dispatchEvent(e);else throw Error("The supplied element doesn't support dispatchEvent");else if(e&&b.click)b.click();else if("undefined"!=typeof b.fireEvent)b.fireEvent("on"+c);else throw Error("Browser doesn't support triggering events");},c:function(b){return a.B(b)?b():b},Xa:function(b){return a.B(b)?b.u():b},Ba:function(b,c,e){if(c){var d=/\S+/g,h=b.className.match(d)||[];a.a.s(c.match(d),function(b){a.a.ca(h,b,e)});b.className=
h.join(" ")}},bb:function(b,c){var e=a.a.c(c);if(null===e||e===q)e="";var d=a.e.firstChild(b);!d||3!=d.nodeType||a.e.nextSibling(d)?a.e.S(b,[b.ownerDocument.createTextNode(e)]):d.data=e;a.a.fc(b)},Mb:function(a,b){a.name=b;if(7>=e)try{a.mergeAttributes(v.createElement("<input name='"+a.name+"'/>"),!1)}catch(c){}},fc:function(a){9<=e&&(a=1==a.nodeType?a:a.parentNode,a.style&&(a.style.zoom=a.style.zoom))},dc:function(a){if(e){var b=a.style.width;a.style.width=0;a.style.width=b}},sc:function(b,c){b=
a.a.c(b);c=a.a.c(c);for(var e=[],d=b;d<=c;d++)e.push(d);return e},R:function(a){for(var b=[],c=0,e=a.length;c<e;c++)b.push(a[c]);return b},yc:6===e,zc:7===e,ka:e,wb:function(b,c){for(var e=a.a.R(b.getElementsByTagName("input")).concat(a.a.R(b.getElementsByTagName("textarea"))),d="string"==typeof c?function(a){return a.name===c}:function(a){return c.test(a.name)},h=[],f=e.length-1;0<=f;f--)d(e[f])&&h.push(e[f]);return h},pc:function(b){return"string"==typeof b&&(b=a.a.Aa(b))?D&&D.parse?D.parse(b):
(new Function("return "+b))():null},cb:function(b,c,e){if(!D||!D.stringify)throw Error("Cannot find JSON.stringify(). Some browsers (e.g., IE < 8) don't support it natively, but you can overcome this by adding a script reference to json2.js, downloadable from http://www.json.org/json2.js");return D.stringify(a.a.c(b),c,e)},qc:function(c,e,d){d=d||{};var h=d.params||{},f=d.includeFields||this.ub,g=c;if("object"==typeof c&&"form"===a.a.C(c))for(var g=c.action,k=f.length-1;0<=k;k--)for(var u=a.a.wb(c,
f[k]),E=u.length-1;0<=E;E--)h[u[E].name]=u[E].value;e=a.a.c(e);var A=v.createElement("form");A.style.display="none";A.action=g;A.method="post";for(var q in e)c=v.createElement("input"),c.type="hidden",c.name=q,c.value=a.a.cb(a.a.c(e[q])),A.appendChild(c);b(h,function(a,b){var c=v.createElement("input");c.type="hidden";c.name=a;c.value=b;A.appendChild(c)});v.body.appendChild(A);d.submitter?d.submitter(A):A.submit();setTimeout(function(){A.parentNode.removeChild(A)},0)}}}();a.b("utils",a.a);a.b("utils.arrayForEach",
a.a.s);a.b("utils.arrayFirst",a.a.pb);a.b("utils.arrayFilter",a.a.ra);a.b("utils.arrayGetDistinctValues",a.a.qb);a.b("utils.arrayIndexOf",a.a.m);a.b("utils.arrayMap",a.a.Ea);a.b("utils.arrayPushAll",a.a.ea);a.b("utils.arrayRemoveItem",a.a.sa);a.b("utils.extend",a.a.extend);a.b("utils.fieldsIncludedWithJsonPost",a.a.ub);a.b("utils.getFormFields",a.a.wb);a.b("utils.peekObservable",a.a.Xa);a.b("utils.postJson",a.a.qc);a.b("utils.parseJson",a.a.pc);a.b("utils.registerEventHandler",a.a.r);a.b("utils.stringifyJson",
a.a.cb);a.b("utils.range",a.a.sc);a.b("utils.toggleDomNodeCssClass",a.a.Ba);a.b("utils.triggerEvent",a.a.na);a.b("utils.unwrapObservable",a.a.c);a.b("utils.objectForEach",a.a.F);a.b("utils.addOrRemoveItem",a.a.ca);a.b("unwrap",a.a.c);Function.prototype.bind||(Function.prototype.bind=function(a){var d=this,c=Array.prototype.slice.call(arguments);a=c.shift();return function(){return d.apply(a,c.concat(Array.prototype.slice.call(arguments)))}});a.a.f=new function(){function a(b,k){var h=b[c];if(!h||
"null"===h||!f[h]){if(!k)return q;h=b[c]="ko"+d++;f[h]={}}return f[h]}var d=0,c="__ko__"+(new Date).getTime(),f={};return{get:function(c,d){var h=a(c,!1);return h===q?q:h[d]},set:function(c,d,h){if(h!==q||a(c,!1)!==q)a(c,!0)[d]=h},clear:function(a){var b=a[c];return b?(delete f[b],a[c]=null,!0):!1},N:function(){return d++ +c}}};a.b("utils.domData",a.a.f);a.b("utils.domData.clear",a.a.f.clear);a.a.v=new function(){function b(b,d){var e=a.a.f.get(b,c);e===q&&d&&(e=[],a.a.f.set(b,c,e));return e}function d(c){var h=
b(c,!1);if(h)for(var h=h.slice(0),e=0;e<h.length;e++)h[e](c);a.a.f.clear(c);a.a.v.cleanExternalData(c);if(g[c.nodeType])for(h=c.firstChild;c=h;)h=c.nextSibling,8===c.nodeType&&d(c)}var c=a.a.f.N(),f={1:!0,8:!0,9:!0},g={1:!0,9:!0};return{ba:function(a,c){if("function"!=typeof c)throw Error("Callback must be a function");b(a,!0).push(c)},Kb:function(d,h){var e=b(d,!1);e&&(a.a.sa(e,h),0==e.length&&a.a.f.set(d,c,q))},Q:function(b){if(f[b.nodeType]&&(d(b),g[b.nodeType])){var c=[];a.a.ea(c,b.getElementsByTagName("*"));
for(var e=0,m=c.length;e<m;e++)d(c[e])}return b},removeNode:function(b){a.Q(b);b.parentNode&&b.parentNode.removeChild(b)},cleanExternalData:function(a){s&&"function"==typeof s.cleanData&&s.cleanData([a])}}};a.Q=a.a.v.Q;a.removeNode=a.a.v.removeNode;a.b("cleanNode",a.Q);a.b("removeNode",a.removeNode);a.b("utils.domNodeDisposal",a.a.v);a.b("utils.domNodeDisposal.addDisposeCallback",a.a.v.ba);a.b("utils.domNodeDisposal.removeDisposeCallback",a.a.v.Kb);(function(){a.a.wa=function(b){var d;if(s)if(s.parseHTML)d=
s.parseHTML(b)||[];else{if((d=s.clean([b]))&&d[0]){for(b=d[0];b.parentNode&&11!==b.parentNode.nodeType;)b=b.parentNode;b.parentNode&&b.parentNode.removeChild(b)}}else{var c=a.a.Aa(b).toLowerCase();d=v.createElement("div");c=c.match(/^<(thead|tbody|tfoot)/)&&[1,"<table>","</table>"]||!c.indexOf("<tr")&&[2,"<table><tbody>","</tbody></table>"]||(!c.indexOf("<td")||!c.indexOf("<th"))&&[3,"<table><tbody><tr>","</tr></tbody></table>"]||[0,"",""];b="ignored<div>"+c[1]+b+c[2]+"</div>";for("function"==typeof x.innerShiv?
d.appendChild(x.innerShiv(b)):d.innerHTML=b;c[0]--;)d=d.lastChild;d=a.a.R(d.lastChild.childNodes)}return d};a.a.$a=function(b,d){a.a.La(b);d=a.a.c(d);if(null!==d&&d!==q)if("string"!=typeof d&&(d=d.toString()),s)s(b).html(d);else for(var c=a.a.wa(d),f=0;f<c.length;f++)b.appendChild(c[f])}})();a.b("utils.parseHtmlFragment",a.a.wa);a.b("utils.setHtml",a.a.$a);a.D=function(){function b(c,d){if(c)if(8==c.nodeType){var g=a.D.Gb(c.nodeValue);null!=g&&d.push({bc:c,mc:g})}else if(1==c.nodeType)for(var g=0,
k=c.childNodes,h=k.length;g<h;g++)b(k[g],d)}var d={};return{Ua:function(a){if("function"!=typeof a)throw Error("You can only pass a function to ko.memoization.memoize()");var b=(4294967296*(1+Math.random())|0).toString(16).substring(1)+(4294967296*(1+Math.random())|0).toString(16).substring(1);d[b]=a;return"\x3c!--[ko_memo:"+b+"]--\x3e"},Rb:function(a,b){var g=d[a];if(g===q)throw Error("Couldn't find any memo with ID "+a+". Perhaps it's already been unmemoized.");try{return g.apply(null,b||[]),!0}finally{delete d[a]}},
Sb:function(c,d){var g=[];b(c,g);for(var k=0,h=g.length;k<h;k++){var e=g[k].bc,m=[e];d&&a.a.ea(m,d);a.D.Rb(g[k].mc,m);e.nodeValue="";e.parentNode&&e.parentNode.removeChild(e)}},Gb:function(a){return(a=a.match(/^\[ko_memo\:(.*?)\]$/))?a[1]:null}}}();a.b("memoization",a.D);a.b("memoization.memoize",a.D.Ua);a.b("memoization.unmemoize",a.D.Rb);a.b("memoization.parseMemoText",a.D.Gb);a.b("memoization.unmemoizeDomNodeAndDescendants",a.D.Sb);a.Ma={throttle:function(b,d){b.throttleEvaluation=d;var c=null;
return a.j({read:b,write:function(a){clearTimeout(c);c=setTimeout(function(){b(a)},d)}})},rateLimit:function(a,d){var c,f,g;"number"==typeof d?c=d:(c=d.timeout,f=d.method);g="notifyWhenChangesStop"==f?T:S;a.Ta(function(a){return g(a,c)})},notify:function(a,d){a.equalityComparer="always"==d?null:H}};var R={undefined:1,"boolean":1,number:1,string:1};a.b("extenders",a.Ma);a.Pb=function(b,d,c){this.target=b;this.ua=d;this.ac=c;this.Bb=!1;a.w(this,"dispose",this.J)};a.Pb.prototype.J=function(){this.Bb=
!0;this.ac()};a.O=function(){a.a.za(this,a.O.fn);this.K={}};var G="change",z={T:function(b,d,c){var f=this;c=c||G;var g=new a.Pb(f,d?b.bind(d):b,function(){a.a.sa(f.K[c],g);f.mb&&f.mb()});f.ta&&f.ta(c);f.K[c]||(f.K[c]=[]);f.K[c].push(g);return g},notifySubscribers:function(b,d){d=d||G;if(this.zb(d))try{a.k.Fa();for(var c=this.K[d].slice(0),f=0,g;g=c[f];++f)g.Bb||g.ua(b)}finally{a.k.end()}},Ta:function(b){var d=this,c=a.B(d),f,g,k;d.oa||(d.oa=d.notifySubscribers,d.notifySubscribers=function(a,b){b&&
b!==G?"beforeChange"===b?d.jb(a):d.oa(a,b):d.kb(a)});var h=b(function(){c&&k===d&&(k=d());f=!1;d.Qa(g,k)&&d.oa(g=k)});d.kb=function(a){f=!0;k=a;h()};d.jb=function(a){f||(g=a,d.oa(a,"beforeChange"))}},zb:function(a){return this.K[a]&&this.K[a].length},xb:function(){var b=0;a.a.F(this.K,function(a,c){b+=c.length});return b},Qa:function(a,d){return!this.equalityComparer||!this.equalityComparer(a,d)},extend:function(b){var d=this;b&&a.a.F(b,function(b,f){var g=a.Ma[b];"function"==typeof g&&(d=g(d,f)||
d)});return d}};a.w(z,"subscribe",z.T);a.w(z,"extend",z.extend);a.w(z,"getSubscriptionsCount",z.xb);a.a.va&&a.a.ya(z,Function.prototype);a.O.fn=z;a.Cb=function(a){return null!=a&&"function"==typeof a.T&&"function"==typeof a.notifySubscribers};a.b("subscribable",a.O);a.b("isSubscribable",a.Cb);a.W=a.k=function(){function b(a){c.push(f);f=a}function d(){f=c.pop()}var c=[],f,g=0;return{Fa:b,end:d,Jb:function(b){if(f){if(!a.Cb(b))throw Error("Only subscribable things can act as dependencies");f.ua(b,
b.Vb||(b.Vb=++g))}},A:function(a,c,e){try{return b(),a.apply(c,e||[])}finally{d()}},ja:function(){if(f)return f.t.ja()},la:function(){if(f)return f.la}}}();a.b("computedContext",a.W);a.b("computedContext.getDependenciesCount",a.W.ja);a.b("computedContext.isInitial",a.W.la);a.b("computedContext.isSleeping",a.W.Ac);a.n=function(b){function d(){if(0<arguments.length)return d.Qa(c,arguments[0])&&(d.V(),c=arguments[0],d.U()),this;a.k.Jb(d);return c}var c=b;a.O.call(d);a.a.za(d,a.n.fn);d.u=function(){return c};
d.U=function(){d.notifySubscribers(c)};d.V=function(){d.notifySubscribers(c,"beforeChange")};a.w(d,"peek",d.u);a.w(d,"valueHasMutated",d.U);a.w(d,"valueWillMutate",d.V);return d};a.n.fn={equalityComparer:H};var F=a.n.rc="__ko_proto__";a.n.fn[F]=a.n;a.a.va&&a.a.ya(a.n.fn,a.O.fn);a.Na=function(b,d){return null===b||b===q||b[F]===q?!1:b[F]===d?!0:a.Na(b[F],d)};a.B=function(b){return a.Na(b,a.n)};a.Db=function(b){return"function"==typeof b&&b[F]===a.n||"function"==typeof b&&b[F]===a.j&&b.hc?!0:!1};a.b("observable",
a.n);a.b("isObservable",a.B);a.b("isWriteableObservable",a.Db);a.Z=function(b){b=b||[];if("object"!=typeof b||!("length"in b))throw Error("The argument passed when initializing an observable array must be an array, or null, or undefined.");b=a.n(b);a.a.za(b,a.Z.fn);return b.extend({trackArrayChanges:!0})};a.Z.fn={remove:function(b){for(var d=this.u(),c=[],f="function"!=typeof b||a.B(b)?function(a){return a===b}:b,g=0;g<d.length;g++){var k=d[g];f(k)&&(0===c.length&&this.V(),c.push(k),d.splice(g,1),
g--)}c.length&&this.U();return c},removeAll:function(b){if(b===q){var d=this.u(),c=d.slice(0);this.V();d.splice(0,d.length);this.U();return c}return b?this.remove(function(c){return 0<=a.a.m(b,c)}):[]},destroy:function(b){var d=this.u(),c="function"!=typeof b||a.B(b)?function(a){return a===b}:b;this.V();for(var f=d.length-1;0<=f;f--)c(d[f])&&(d[f]._destroy=!0);this.U()},destroyAll:function(b){return b===q?this.destroy(function(){return!0}):b?this.destroy(function(d){return 0<=a.a.m(b,d)}):[]},indexOf:function(b){var d=
this();return a.a.m(d,b)},replace:function(a,d){var c=this.indexOf(a);0<=c&&(this.V(),this.u()[c]=d,this.U())}};a.a.s("pop push reverse shift sort splice unshift".split(" "),function(b){a.Z.fn[b]=function(){var a=this.u();this.V();this.rb(a,b,arguments);a=a[b].apply(a,arguments);this.U();return a}});a.a.s(["slice"],function(b){a.Z.fn[b]=function(){var a=this();return a[b].apply(a,arguments)}});a.a.va&&a.a.ya(a.Z.fn,a.n.fn);a.b("observableArray",a.Z);var J="arrayChange";a.Ma.trackArrayChanges=function(b){function d(){if(!c){c=
!0;var d=b.notifySubscribers;b.notifySubscribers=function(a,b){b&&b!==G||++g;return d.apply(this,arguments)};var e=[].concat(b.u()||[]);f=null;b.T(function(c){c=[].concat(c||[]);if(b.zb(J)){var d;if(!f||1<g)f=a.a.Ga(e,c,{sparse:!0});d=f;d.length&&b.notifySubscribers(d,J)}e=c;f=null;g=0})}}if(!b.rb){var c=!1,f=null,g=0,k=b.T;b.T=b.subscribe=function(a,b,c){c===J&&d();return k.apply(this,arguments)};b.rb=function(b,e,d){function n(a,b,c){return k[k.length]={status:a,value:b,index:c}}if(c&&!g){var k=
[],l=b.length,r=d.length,y=0;switch(e){case "push":y=l;case "unshift":for(e=0;e<r;e++)n("added",d[e],y+e);break;case "pop":y=l-1;case "shift":l&&n("deleted",b[y],y);break;case "splice":e=Math.min(Math.max(0,0>d[0]?l+d[0]:d[0]),l);for(var l=1===r?l:Math.min(e+(d[1]||0),l),r=e+r-2,y=Math.max(l,r),t=[],u=[],E=2;e<y;++e,++E)e<l&&u.push(n("deleted",b[e],e)),e<r&&t.push(n("added",d[E],e));a.a.vb(u,t);break;default:return}f=k}}}};a.t=a.j=function(b,d,c){function f(){a.a.F(x,function(a,b){b.J()});x={}}function g(){f();
C=0;t=!0;l=!1}function k(){var a=e.throttleEvaluation;a&&0<=a?(clearTimeout(P),P=setTimeout(h,a)):e.hb?e.hb():h()}function h(b){if(r){if(E)throw Error("A 'pure' computed must not be called recursively");}else if(!t){if(s&&s()){if(!y){v();return}}else y=!1;r=!0;if(A)try{var c={};a.k.Fa({ua:function(a,b){c[b]||(c[b]=1,++C)},t:e,la:q});C=0;p=u.call(d)}finally{a.k.end(),r=!1}else try{var h=x,f=C;a.k.Fa({ua:function(a,b){t||(f&&h[b]?(x[b]=h[b],++C,delete h[b],--f):x[b]||(x[b]=a.T(k),++C))},t:e,la:E?q:
!C});x={};C=0;try{var m=d?u.call(d):u()}finally{a.k.end(),f&&a.a.F(h,function(a,b){b.J()}),l=!1}e.Qa(p,m)&&(e.notifySubscribers(p,"beforeChange"),p=m,!0!==b&&e.notifySubscribers(p))}finally{r=!1}C||v()}}function e(){if(0<arguments.length){if("function"===typeof O)O.apply(d,arguments);else throw Error("Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.");return this}a.k.Jb(e);l&&h(!0);return p}function m(){l&&
!C&&h(!0);return p}function n(){return l||0<C}var p,l=!0,r=!1,y=!1,t=!1,u=b,E=!1,A=!1;u&&"object"==typeof u?(c=u,u=c.read):(c=c||{},u||(u=c.read));if("function"!=typeof u)throw Error("Pass a function that returns the value of the ko.computed");var O=c.write,w=c.disposeWhenNodeIsRemoved||c.q||null,B=c.disposeWhen||c.Ja,s=B,v=g,x={},C=0,P=null;d||(d=c.owner);a.O.call(e);a.a.za(e,a.j.fn);e.u=m;e.ja=function(){return C};e.hc="function"===typeof c.write;e.J=function(){v()};e.X=n;var z=e.Ta;e.Ta=function(a){z.call(e,
a);e.hb=function(){e.jb(p);l=!0;e.kb(e)}};c.pure?(A=E=!0,e.ta=function(){A&&(A=!1,h(!0))},e.mb=function(){e.xb()||(f(),A=l=!0)}):c.deferEvaluation&&(e.ta=function(){m();delete e.ta});a.w(e,"peek",e.u);a.w(e,"dispose",e.J);a.w(e,"isActive",e.X);a.w(e,"getDependenciesCount",e.ja);w&&(y=!0,w.nodeType&&(s=function(){return!a.a.Ka(w)||B&&B()}));A||c.deferEvaluation||h();w&&n()&&w.nodeType&&(v=function(){a.a.v.Kb(w,v);g()},a.a.v.ba(w,v));return e};a.jc=function(b){return a.Na(b,a.j)};z=a.n.rc;a.j[z]=a.n;
a.j.fn={equalityComparer:H};a.j.fn[z]=a.j;a.a.va&&a.a.ya(a.j.fn,a.O.fn);a.b("dependentObservable",a.j);a.b("computed",a.j);a.b("isComputed",a.jc);a.Ib=function(b,d){if("function"===typeof b)return a.t(b,d,{pure:!0});b=a.a.extend({},b);b.pure=!0;return a.t(b,d)};a.b("pureComputed",a.Ib);(function(){function b(a,g,k){k=k||new c;a=g(a);if("object"!=typeof a||null===a||a===q||a instanceof Date||a instanceof String||a instanceof Number||a instanceof Boolean)return a;var h=a instanceof Array?[]:{};k.save(a,
h);d(a,function(c){var d=g(a[c]);switch(typeof d){case "boolean":case "number":case "string":case "function":h[c]=d;break;case "object":case "undefined":var n=k.get(d);h[c]=n!==q?n:b(d,g,k)}});return h}function d(a,b){if(a instanceof Array){for(var c=0;c<a.length;c++)b(c);"function"==typeof a.toJSON&&b("toJSON")}else for(c in a)b(c)}function c(){this.keys=[];this.gb=[]}a.Qb=function(c){if(0==arguments.length)throw Error("When calling ko.toJS, pass the object you want to convert.");return b(c,function(b){for(var c=
0;a.B(b)&&10>c;c++)b=b();return b})};a.toJSON=function(b,c,d){b=a.Qb(b);return a.a.cb(b,c,d)};c.prototype={save:function(b,c){var d=a.a.m(this.keys,b);0<=d?this.gb[d]=c:(this.keys.push(b),this.gb.push(c))},get:function(b){b=a.a.m(this.keys,b);return 0<=b?this.gb[b]:q}}})();a.b("toJS",a.Qb);a.b("toJSON",a.toJSON);(function(){a.i={o:function(b){switch(a.a.C(b)){case "option":return!0===b.__ko__hasDomDataOptionValue__?a.a.f.get(b,a.d.options.Va):7>=a.a.ka?b.getAttributeNode("value")&&b.getAttributeNode("value").specified?
b.value:b.text:b.value;case "select":return 0<=b.selectedIndex?a.i.o(b.options[b.selectedIndex]):q;default:return b.value}},aa:function(b,d,c){switch(a.a.C(b)){case "option":switch(typeof d){case "string":a.a.f.set(b,a.d.options.Va,q);"__ko__hasDomDataOptionValue__"in b&&delete b.__ko__hasDomDataOptionValue__;b.value=d;break;default:a.a.f.set(b,a.d.options.Va,d),b.__ko__hasDomDataOptionValue__=!0,b.value="number"===typeof d?d:""}break;case "select":if(""===d||null===d)d=q;for(var f=-1,g=0,k=b.options.length,
h;g<k;++g)if(h=a.i.o(b.options[g]),h==d||""==h&&d===q){f=g;break}if(c||0<=f||d===q&&1<b.size)b.selectedIndex=f;break;default:if(null===d||d===q)d="";b.value=d}}}})();a.b("selectExtensions",a.i);a.b("selectExtensions.readValue",a.i.o);a.b("selectExtensions.writeValue",a.i.aa);a.h=function(){function b(b){b=a.a.Aa(b);123===b.charCodeAt(0)&&(b=b.slice(1,-1));var c=[],d=b.match(f),h,l,r=0;if(d){d.push(",");for(var y=0,t;t=d[y];++y){var u=t.charCodeAt(0);if(44===u){if(0>=r){h&&c.push(l?{key:h,value:l.join("")}:
{unknown:h});h=l=r=0;continue}}else if(58===u){if(!l)continue}else if(47===u&&y&&1<t.length)(u=d[y-1].match(g))&&!k[u[0]]&&(b=b.substr(b.indexOf(t)+1),d=b.match(f),d.push(","),y=-1,t="/");else if(40===u||123===u||91===u)++r;else if(41===u||125===u||93===u)--r;else if(!h&&!l){h=34===u||39===u?t.slice(1,-1):t;continue}l?l.push(t):l=[t]}}return c}var d=["true","false","null","undefined"],c=/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i,f=RegExp("\"(?:[^\"\\\\]|\\\\.)*\"|'(?:[^'\\\\]|\\\\.)*'|/(?:[^/\\\\]|\\\\.)*/w*|[^\\s:,/][^,\"'{}()/:[\\]]*[^\\s,\"'{}()/:[\\]]|[^\\s]",
"g"),g=/[\])"'A-Za-z0-9_$]+$/,k={"in":1,"return":1,"typeof":1},h={};return{fa:[],$:h,Wa:b,xa:function(e,m){function f(b,e){var m;if(!y){var t=a.getBindingHandler(b);if(t&&t.preprocess&&!(e=t.preprocess(e,b,f)))return;if(t=h[b])m=e,0<=a.a.m(d,m)?m=!1:(t=m.match(c),m=null===t?!1:t[1]?"Object("+t[1]+")"+t[2]:m),t=m;t&&k.push("'"+b+"':function(_z){"+m+"=_z}")}r&&(e="function(){return "+e+" }");g.push("'"+b+"':"+e)}m=m||{};var g=[],k=[],r=m.valueAccessors,y=m.bindingParams,t="string"===typeof e?b(e):e;
a.a.s(t,function(a){f(a.key||a.unknown,a.value)});k.length&&f("_ko_property_writers","{"+k.join(",")+" }");return g.join(",")},lc:function(a,b){for(var c=0;c<a.length;c++)if(a[c].key==b)return!0;return!1},Ca:function(b,c,d,h,f){if(b&&a.B(b))!a.Db(b)||f&&b.u()===h||b(h);else if((b=c.get("_ko_property_writers"))&&b[d])b[d](h)}}}();a.b("expressionRewriting",a.h);a.b("expressionRewriting.bindingRewriteValidators",a.h.fa);a.b("expressionRewriting.parseObjectLiteral",a.h.Wa);a.b("expressionRewriting.preProcessBindings",
a.h.xa);a.b("expressionRewriting._twoWayBindings",a.h.$);a.b("jsonExpressionRewriting",a.h);a.b("jsonExpressionRewriting.insertPropertyAccessorsIntoJson",a.h.xa);(function(){function b(a){return 8==a.nodeType&&k.test(g?a.text:a.nodeValue)}function d(a){return 8==a.nodeType&&h.test(g?a.text:a.nodeValue)}function c(a,c){for(var e=a,h=1,f=[];e=e.nextSibling;){if(d(e)&&(h--,0===h))return f;f.push(e);b(e)&&h++}if(!c)throw Error("Cannot find closing comment tag to match: "+a.nodeValue);return null}function f(a,
b){var d=c(a,b);return d?0<d.length?d[d.length-1].nextSibling:a.nextSibling:null}var g=v&&"\x3c!--test--\x3e"===v.createComment("test").text,k=g?/^\x3c!--\s*ko(?:\s+([\s\S]+))?\s*--\x3e$/:/^\s*ko(?:\s+([\s\S]+))?\s*$/,h=g?/^\x3c!--\s*\/ko\s*--\x3e$/:/^\s*\/ko\s*$/,e={ul:!0,ol:!0};a.e={P:{},childNodes:function(a){return b(a)?c(a):a.childNodes},ha:function(c){if(b(c)){c=a.e.childNodes(c);for(var d=0,e=c.length;d<e;d++)a.removeNode(c[d])}else a.a.La(c)},S:function(c,d){if(b(c)){a.e.ha(c);for(var e=c.nextSibling,
h=0,f=d.length;h<f;h++)e.parentNode.insertBefore(d[h],e)}else a.a.S(c,d)},Hb:function(a,c){b(a)?a.parentNode.insertBefore(c,a.nextSibling):a.firstChild?a.insertBefore(c,a.firstChild):a.appendChild(c)},Ab:function(c,d,e){e?b(c)?c.parentNode.insertBefore(d,e.nextSibling):e.nextSibling?c.insertBefore(d,e.nextSibling):c.appendChild(d):a.e.Hb(c,d)},firstChild:function(a){return b(a)?!a.nextSibling||d(a.nextSibling)?null:a.nextSibling:a.firstChild},nextSibling:function(a){b(a)&&(a=f(a));return a.nextSibling&&
d(a.nextSibling)?null:a.nextSibling},gc:b,xc:function(a){return(a=(g?a.text:a.nodeValue).match(k))?a[1]:null},Fb:function(c){if(e[a.a.C(c)]){var h=c.firstChild;if(h){do if(1===h.nodeType){var g;g=h.firstChild;var k=null;if(g){do if(k)k.push(g);else if(b(g)){var r=f(g,!0);r?g=r:k=[g]}else d(g)&&(k=[g]);while(g=g.nextSibling)}if(g=k)for(k=h.nextSibling,r=0;r<g.length;r++)k?c.insertBefore(g[r],k):c.appendChild(g[r])}while(h=h.nextSibling)}}}}})();a.b("virtualElements",a.e);a.b("virtualElements.allowedBindings",
a.e.P);a.b("virtualElements.emptyNode",a.e.ha);a.b("virtualElements.insertAfter",a.e.Ab);a.b("virtualElements.prepend",a.e.Hb);a.b("virtualElements.setDomNodeChildren",a.e.S);(function(){a.I=function(){this.Yb={}};a.a.extend(a.I.prototype,{nodeHasBindings:function(b){switch(b.nodeType){case 1:return null!=b.getAttribute("data-bind")||a.g.getComponentNameForNode(b);case 8:return a.e.gc(b);default:return!1}},getBindings:function(b,d){var c=this.getBindingsString(b,d),c=c?this.parseBindingsString(c,
d,b):null;return a.g.lb(c,b,d,!1)},getBindingAccessors:function(b,d){var c=this.getBindingsString(b,d),c=c?this.parseBindingsString(c,d,b,{valueAccessors:!0}):null;return a.g.lb(c,b,d,!0)},getBindingsString:function(b){switch(b.nodeType){case 1:return b.getAttribute("data-bind");case 8:return a.e.xc(b);default:return null}},parseBindingsString:function(b,d,c,f){try{var g=this.Yb,k=b+(f&&f.valueAccessors||""),h;if(!(h=g[k])){var e,m="with($context){with($data||{}){return{"+a.h.xa(b,f)+"}}}";e=new Function("$context",
"$element",m);h=g[k]=e}return h(d,c)}catch(n){throw n.message="Unable to parse bindings.\nBindings value: "+b+"\nMessage: "+n.message,n;}}});a.I.instance=new a.I})();a.b("bindingProvider",a.I);(function(){function b(a){return function(){return a}}function d(a){return a()}function c(b){return a.a.ma(a.k.A(b),function(a,c){return function(){return b()[c]}})}function f(a,b){return c(this.getBindings.bind(this,a,b))}function g(b,c,d){var e,h=a.e.firstChild(c),f=a.I.instance,g=f.preprocessNode;if(g){for(;e=
h;)h=a.e.nextSibling(e),g.call(f,e);h=a.e.firstChild(c)}for(;e=h;)h=a.e.nextSibling(e),k(b,e,d)}function k(b,c,d){var h=!0,f=1===c.nodeType;f&&a.e.Fb(c);if(f&&d||a.I.instance.nodeHasBindings(c))h=e(c,null,b,d).shouldBindDescendants;h&&!n[a.a.C(c)]&&g(b,c,!f)}function h(b){var c=[],d={},e=[];a.a.F(b,function A(h){if(!d[h]){var f=a.getBindingHandler(h);f&&(f.after&&(e.push(h),a.a.s(f.after,function(c){if(b[c]){if(-1!==a.a.m(e,c))throw Error("Cannot combine the following bindings, because they have a cyclic dependency: "+
e.join(", "));A(c)}}),e.length--),c.push({key:h,yb:f}));d[h]=!0}});return c}function e(b,c,e,g){var m=a.a.f.get(b,p);if(!c){if(m)throw Error("You cannot apply bindings multiple times to the same element.");a.a.f.set(b,p,!0)}!m&&g&&a.Ob(b,e);var k;if(c&&"function"!==typeof c)k=c;else{var n=a.I.instance,l=n.getBindingAccessors||f,s=a.j(function(){(k=c?c(e,b):l.call(n,b,e))&&e.H&&e.H();return k},null,{q:b});k&&s.X()||(s=null)}var v;if(k){var x=s?function(a){return function(){return d(s()[a])}}:function(a){return k[a]},
z=function(){return a.a.ma(s?s():k,d)};z.get=function(a){return k[a]&&d(x(a))};z.has=function(a){return a in k};g=h(k);a.a.s(g,function(c){var d=c.yb.init,h=c.yb.update,f=c.key;if(8===b.nodeType&&!a.e.P[f])throw Error("The binding '"+f+"' cannot be used with virtual elements");try{"function"==typeof d&&a.k.A(function(){var a=d(b,x(f),z,e.$data,e);if(a&&a.controlsDescendantBindings){if(v!==q)throw Error("Multiple bindings ("+v+" and "+f+") are trying to control descendant bindings of the same element. You cannot use these bindings together on the same element.");
v=f}}),"function"==typeof h&&a.j(function(){h(b,x(f),z,e.$data,e)},null,{q:b})}catch(g){throw g.message='Unable to process binding "'+f+": "+k[f]+'"\nMessage: '+g.message,g;}})}return{shouldBindDescendants:v===q}}function m(b){return b&&b instanceof a.L?b:new a.L(b)}a.d={};var n={script:!0};a.getBindingHandler=function(b){return a.d[b]};a.L=function(b,c,d,e){var h=this,f="function"==typeof b&&!a.B(b),g,m=a.j(function(){var g=f?b():b,k=a.a.c(g);c?(c.H&&c.H(),a.a.extend(h,c),m&&(h.H=m)):(h.$parents=
[],h.$root=k,h.ko=a);h.$rawData=g;h.$data=k;d&&(h[d]=k);e&&e(h,c,k);return h.$data},null,{Ja:function(){return g&&!a.a.nb(g)},q:!0});m.X()&&(h.H=m,m.equalityComparer=null,g=[],m.Tb=function(b){g.push(b);a.a.v.ba(b,function(b){a.a.sa(g,b);g.length||(m.J(),h.H=m=q)})})};a.L.prototype.createChildContext=function(b,c,d){return new a.L(b,this,c,function(a,b){a.$parentContext=b;a.$parent=b.$data;a.$parents=(b.$parents||[]).slice(0);a.$parents.unshift(a.$parent);d&&d(a)})};a.L.prototype.extend=function(b){return new a.L(this.H||
this.$data,this,null,function(c,d){c.$rawData=d.$rawData;a.a.extend(c,"function"==typeof b?b():b)})};var p=a.a.f.N(),l=a.a.f.N();a.Ob=function(b,c){if(2==arguments.length)a.a.f.set(b,l,c),c.H&&c.H.Tb(b);else return a.a.f.get(b,l)};a.pa=function(b,c,d){1===b.nodeType&&a.e.Fb(b);return e(b,c,m(d),!0)};a.Wb=function(d,e,h){h=m(h);return a.pa(d,"function"===typeof e?c(e.bind(null,h,d)):a.a.ma(e,b),h)};a.Da=function(a,b){1!==b.nodeType&&8!==b.nodeType||g(m(a),b,!0)};a.ob=function(a,b){!s&&x.jQuery&&(s=
x.jQuery);if(b&&1!==b.nodeType&&8!==b.nodeType)throw Error("ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node");b=b||x.document.body;k(m(a),b,!0)};a.Ia=function(b){switch(b.nodeType){case 1:case 8:var c=a.Ob(b);if(c)return c;if(b.parentNode)return a.Ia(b.parentNode)}return q};a.$b=function(b){return(b=a.Ia(b))?b.$data:q};a.b("bindingHandlers",a.d);a.b("applyBindings",a.ob);a.b("applyBindingsToDescendants",a.Da);a.b("applyBindingAccessorsToNode",a.pa);
a.b("applyBindingsToNode",a.Wb);a.b("contextFor",a.Ia);a.b("dataFor",a.$b)})();(function(b){function d(d,e){var f=g.hasOwnProperty(d)?g[d]:b,n;f||(f=g[d]=new a.O,c(d,function(a){k[d]=a;delete g[d];n?f.notifySubscribers(a):setTimeout(function(){f.notifySubscribers(a)},0)}),n=!0);f.T(e)}function c(a,b){f("getConfig",[a],function(c){c?f("loadComponent",[a,c],function(a){b(a)}):b(null)})}function f(c,d,g,k){k||(k=a.g.loaders.slice(0));var p=k.shift();if(p){var l=p[c];if(l){var r=!1;if(l.apply(p,d.concat(function(a){r?
g(null):null!==a?g(a):f(c,d,g,k)}))!==b&&(r=!0,!p.suppressLoaderExceptions))throw Error("Component loaders must supply values by invoking the callback, not by returning values synchronously.");}else f(c,d,g,k)}else g(null)}var g={},k={};a.g={get:function(a,c){var f=k.hasOwnProperty(a)?k[a]:b;f?setTimeout(function(){c(f)},0):d(a,c)},sb:function(a){delete k[a]},ib:f};a.g.loaders=[];a.b("components",a.g);a.b("components.get",a.g.get);a.b("components.clearCachedDefinition",a.g.sb)})();(function(){function b(b,
d,f,g){function p(){0===--r&&g(l)}var l={},r=2,y=f.template;f=f.viewModel;y?c(d,y,function(c){a.g.ib("loadTemplate",[b,c],function(a){l.template=a;p()})}):p();f?c(d,f,function(c){a.g.ib("loadViewModel",[b,c],function(a){l[k]=a;p()})}):p()}function d(a,b,c){if("function"===typeof b)c(function(a){return new b(a)});else if("function"===typeof b[k])c(b[k]);else if("instance"in b){var f=b.instance;c(function(){return f})}else"viewModel"in b?d(a,b.viewModel,c):a("Unknown viewModel value: "+b)}function c(a,
b,c){"string"===typeof b.require?N||x.require?(N||x.require)([b.require],c):a("Uses require, but no AMD loader is present"):c(b)}function f(a){return function(b){throw Error("Component '"+a+"': "+b);}}var g={};a.g.tc=function(b,c){if(!c)throw Error("Invalid configuration for "+b);if(a.g.Ra(b))throw Error("Component "+b+" is already registered");g[b]=c};a.g.Ra=function(a){return a in g};a.g.wc=function(b){delete g[b];a.g.sb(b)};a.g.tb={getConfig:function(a,b){b(g.hasOwnProperty(a)?g[a]:null)},loadComponent:function(a,
d,g){var k=f(a);c(k,d,function(c){b(a,k,c,g)})},loadTemplate:function(b,c,d){b=f(b);if("string"===typeof c)d(a.a.wa(c));else if(c instanceof Array)d(c);else if(x.DocumentFragment?c instanceof DocumentFragment:c&&11===c.nodeType)d(a.a.R(c.childNodes));else if(c.element)if(c=c.element,x.HTMLElement?c instanceof HTMLElement:c&&c.tagName&&1===c.nodeType)d(a.a.ga(c.childNodes));else if("string"===typeof c){var g=v.getElementById(c);g?d(a.a.ga(g.childNodes)):b("Cannot find element with ID "+c)}else b("Unknown element type: "+
c);else b("Unknown template value: "+c)},loadViewModel:function(a,b,c){d(f(a),b,c)}};var k="createViewModel";a.b("components.register",a.g.tc);a.b("components.isRegistered",a.g.Ra);a.b("components.unregister",a.g.wc);a.b("components.defaultLoader",a.g.tb);a.g.loaders.push(a.g.tb);a.g.Ub=g})();(function(){function b(b,f){var g=b.getAttribute("params");if(g){var g=d.parseBindingsString(g,f,b,{valueAccessors:!0,bindingParams:!0}),g=a.a.ma(g,function(d){return a.t(d,null,{q:b})}),k=a.a.ma(g,function(d){return d.X()?
a.t(function(){return a.a.c(d())},null,{q:b}):d.u()});k.hasOwnProperty("$raw")||(k.$raw=g);return k}return{$raw:{}}}a.g.getComponentNameForNode=function(b){b=a.a.C(b);return a.g.Ra(b)&&b};a.g.lb=function(c,d,g,k){if(1===d.nodeType){var h=a.g.getComponentNameForNode(d);if(h){c=c||{};if(c.component)throw Error('Cannot use the "component" binding on a custom element matching a component');var e={name:h,params:b(d,g)};c.component=k?function(){return e}:e}}return c};var d=new a.I;9>a.a.ka&&(a.g.register=
function(a){return function(b){v.createElement(b);return a.apply(this,arguments)}}(a.g.register),v.createDocumentFragment=function(b){return function(){var d=b(),g=a.g.Ub,k;for(k in g)g.hasOwnProperty(k)&&d.createElement(k);return d}}(v.createDocumentFragment))})();(function(){var b=0;a.d.component={init:function(d,c,f,g,k){function h(){var a=e&&e.dispose;"function"===typeof a&&a.call(e);m=null}var e,m;a.a.v.ba(d,h);a.t(function(){var f=a.a.c(c()),g,l;"string"===typeof f?g=f:(g=a.a.c(f.name),l=a.a.c(f.params));
if(!g)throw Error("No component name specified");var r=m=++b;a.g.get(g,function(b){if(m===r){h();if(!b)throw Error("Unknown component '"+g+"'");var c=b.template;if(!c)throw Error("Component '"+g+"' has no template");c=a.a.ga(c);a.e.S(d,c);var c=l,f=b.createViewModel;b=f?f.call(b,c,{element:d}):c;c=k.createChildContext(b);e=b;a.Da(c,d)}})},null,{q:d});return{controlsDescendantBindings:!0}}};a.e.P.component=!0})();var Q={"class":"className","for":"htmlFor"};a.d.attr={update:function(b,d){var c=a.a.c(d())||
{};a.a.F(c,function(c,d){d=a.a.c(d);var k=!1===d||null===d||d===q;k&&b.removeAttribute(c);8>=a.a.ka&&c in Q?(c=Q[c],k?b.removeAttribute(c):b[c]=d):k||b.setAttribute(c,d.toString());"name"===c&&a.a.Mb(b,k?"":d.toString())})}};(function(){a.d.checked={after:["value","attr"],init:function(b,d,c){function f(){var f=b.checked,h=p?k():f;if(!a.W.la()&&(!e||f)){var g=a.k.A(d);m?n!==h?(f&&(a.a.ca(g,h,!0),a.a.ca(g,n,!1)),n=h):a.a.ca(g,h,f):a.h.Ca(g,c,"checked",h,!0)}}function g(){var c=a.a.c(d());b.checked=
m?0<=a.a.m(c,k()):h?c:k()===c}var k=a.Ib(function(){return c.has("checkedValue")?a.a.c(c.get("checkedValue")):c.has("value")?a.a.c(c.get("value")):b.value}),h="checkbox"==b.type,e="radio"==b.type;if(h||e){var m=h&&a.a.c(d())instanceof Array,n=m?k():q,p=e||m;e&&!b.name&&a.d.uniqueName.init(b,function(){return!0});a.t(f,null,{q:b});a.a.r(b,"click",f);a.t(g,null,{q:b})}}};a.h.$.checked=!0;a.d.checkedValue={update:function(b,d){b.value=a.a.c(d())}}})();a.d.css={update:function(b,d){var c=a.a.c(d());"object"==
typeof c?a.a.F(c,function(c,d){d=a.a.c(d);a.a.Ba(b,c,d)}):(c=String(c||""),a.a.Ba(b,b.__ko__cssValue,!1),b.__ko__cssValue=c,a.a.Ba(b,c,!0))}};a.d.enable={update:function(b,d){var c=a.a.c(d());c&&b.disabled?b.removeAttribute("disabled"):c||b.disabled||(b.disabled=!0)}};a.d.disable={update:function(b,d){a.d.enable.update(b,function(){return!a.a.c(d())})}};a.d.event={init:function(b,d,c,f,g){var k=d()||{};a.a.F(k,function(h){"string"==typeof h&&a.a.r(b,h,function(b){var k,n=d()[h];if(n){try{var p=a.a.R(arguments);
f=g.$data;p.unshift(f);k=n.apply(f,p)}finally{!0!==k&&(b.preventDefault?b.preventDefault():b.returnValue=!1)}!1===c.get(h+"Bubble")&&(b.cancelBubble=!0,b.stopPropagation&&b.stopPropagation())}})})}};a.d.foreach={Eb:function(b){return function(){var d=b(),c=a.a.Xa(d);if(!c||"number"==typeof c.length)return{foreach:d,templateEngine:a.M.Pa};a.a.c(d);return{foreach:c.data,as:c.as,includeDestroyed:c.includeDestroyed,afterAdd:c.afterAdd,beforeRemove:c.beforeRemove,afterRender:c.afterRender,beforeMove:c.beforeMove,
afterMove:c.afterMove,templateEngine:a.M.Pa}}},init:function(b,d){return a.d.template.init(b,a.d.foreach.Eb(d))},update:function(b,d,c,f,g){return a.d.template.update(b,a.d.foreach.Eb(d),c,f,g)}};a.h.fa.foreach=!1;a.e.P.foreach=!0;a.d.hasfocus={init:function(b,d,c){function f(f){b.__ko_hasfocusUpdating=!0;var e=b.ownerDocument;if("activeElement"in e){var g;try{g=e.activeElement}catch(k){g=e.body}f=g===b}e=d();a.h.Ca(e,c,"hasfocus",f,!0);b.__ko_hasfocusLastValue=f;b.__ko_hasfocusUpdating=!1}var g=
f.bind(null,!0),k=f.bind(null,!1);a.a.r(b,"focus",g);a.a.r(b,"focusin",g);a.a.r(b,"blur",k);a.a.r(b,"focusout",k)},update:function(b,d){var c=!!a.a.c(d());b.__ko_hasfocusUpdating||b.__ko_hasfocusLastValue===c||(c?b.focus():b.blur(),a.k.A(a.a.na,null,[b,c?"focusin":"focusout"]))}};a.h.$.hasfocus=!0;a.d.hasFocus=a.d.hasfocus;a.h.$.hasFocus=!0;a.d.html={init:function(){return{controlsDescendantBindings:!0}},update:function(b,d){a.a.$a(b,d())}};I("if");I("ifnot",!1,!0);I("with",!0,!1,function(a,d){return a.createChildContext(d)});
var K={};a.d.options={init:function(b){if("select"!==a.a.C(b))throw Error("options binding applies only to SELECT elements");for(;0<b.length;)b.remove(0);return{controlsDescendantBindings:!0}},update:function(b,d,c){function f(){return a.a.ra(b.options,function(a){return a.selected})}function g(a,b,c){var d=typeof b;return"function"==d?b(a):"string"==d?a[b]:c}function k(c,d){if(p.length){var e=0<=a.a.m(p,a.i.o(d[0]));a.a.Nb(d[0],e);l&&!e&&a.k.A(a.a.na,null,[b,"change"])}}var h=0!=b.length&&b.multiple?
b.scrollTop:null,e=a.a.c(d()),m=c.get("optionsIncludeDestroyed");d={};var n,p;p=b.multiple?a.a.Ea(f(),a.i.o):0<=b.selectedIndex?[a.i.o(b.options[b.selectedIndex])]:[];e&&("undefined"==typeof e.length&&(e=[e]),n=a.a.ra(e,function(b){return m||b===q||null===b||!a.a.c(b._destroy)}),c.has("optionsCaption")&&(e=a.a.c(c.get("optionsCaption")),null!==e&&e!==q&&n.unshift(K)));var l=!1;d.beforeRemove=function(a){b.removeChild(a)};e=k;c.has("optionsAfterRender")&&(e=function(b,d){k(0,d);a.k.A(c.get("optionsAfterRender"),
null,[d[0],b!==K?b:q])});a.a.Za(b,n,function(d,e,f){f.length&&(p=f[0].selected?[a.i.o(f[0])]:[],l=!0);e=b.ownerDocument.createElement("option");d===K?(a.a.bb(e,c.get("optionsCaption")),a.i.aa(e,q)):(f=g(d,c.get("optionsValue"),d),a.i.aa(e,a.a.c(f)),d=g(d,c.get("optionsText"),f),a.a.bb(e,d));return[e]},d,e);a.k.A(function(){c.get("valueAllowUnset")&&c.has("value")?a.i.aa(b,a.a.c(c.get("value")),!0):(b.multiple?p.length&&f().length<p.length:p.length&&0<=b.selectedIndex?a.i.o(b.options[b.selectedIndex])!==
p[0]:p.length||0<=b.selectedIndex)&&a.a.na(b,"change")});a.a.dc(b);h&&20<Math.abs(h-b.scrollTop)&&(b.scrollTop=h)}};a.d.options.Va=a.a.f.N();a.d.selectedOptions={after:["options","foreach"],init:function(b,d,c){a.a.r(b,"change",function(){var f=d(),g=[];a.a.s(b.getElementsByTagName("option"),function(b){b.selected&&g.push(a.i.o(b))});a.h.Ca(f,c,"selectedOptions",g)})},update:function(b,d){if("select"!=a.a.C(b))throw Error("values binding applies only to SELECT elements");var c=a.a.c(d());c&&"number"==
typeof c.length&&a.a.s(b.getElementsByTagName("option"),function(b){var d=0<=a.a.m(c,a.i.o(b));a.a.Nb(b,d)})}};a.h.$.selectedOptions=!0;a.d.style={update:function(b,d){var c=a.a.c(d()||{});a.a.F(c,function(c,d){d=a.a.c(d);if(null===d||d===q||!1===d)d="";b.style[c]=d})}};a.d.submit={init:function(b,d,c,f,g){if("function"!=typeof d())throw Error("The value for a submit binding must be a function");a.a.r(b,"submit",function(a){var c,e=d();try{c=e.call(g.$data,b)}finally{!0!==c&&(a.preventDefault?a.preventDefault():
a.returnValue=!1)}})}};a.d.text={init:function(){return{controlsDescendantBindings:!0}},update:function(b,d){a.a.bb(b,d())}};a.e.P.text=!0;a.d.uniqueName={init:function(b,d){if(d()){var c="ko_unique_"+ ++a.d.uniqueName.Zb;a.a.Mb(b,c)}}};a.d.uniqueName.Zb=0;a.d.value={after:["options","foreach"],init:function(b,d,c){if("input"!=b.tagName.toLowerCase()||"checkbox"!=b.type&&"radio"!=b.type){var f=["change"],g=c.get("valueUpdate"),k=!1,h=null;g&&("string"==typeof g&&(g=[g]),a.a.ea(f,g),f=a.a.qb(f));var e=
function(){h=null;k=!1;var e=d(),f=a.i.o(b);a.h.Ca(e,c,"value",f)};!a.a.ka||"input"!=b.tagName.toLowerCase()||"text"!=b.type||"off"==b.autocomplete||b.form&&"off"==b.form.autocomplete||-1!=a.a.m(f,"propertychange")||(a.a.r(b,"propertychange",function(){k=!0}),a.a.r(b,"focus",function(){k=!1}),a.a.r(b,"blur",function(){k&&e()}));a.a.s(f,function(c){var d=e;a.a.vc(c,"after")&&(d=function(){h=a.i.o(b);setTimeout(e,0)},c=c.substring(5));a.a.r(b,c,d)});var m=function(){var e=a.a.c(d()),f=a.i.o(b);if(null!==
h&&e===h)setTimeout(m,0);else if(e!==f)if("select"===a.a.C(b)){var g=c.get("valueAllowUnset"),f=function(){a.i.aa(b,e,g)};f();g||e===a.i.o(b)?setTimeout(f,0):a.k.A(a.a.na,null,[b,"change"])}else a.i.aa(b,e)};a.t(m,null,{q:b})}else a.pa(b,{checkedValue:d})},update:function(){}};a.h.$.value=!0;a.d.visible={update:function(b,d){var c=a.a.c(d()),f="none"!=b.style.display;c&&!f?b.style.display="":!c&&f&&(b.style.display="none")}};(function(b){a.d[b]={init:function(d,c,f,g,k){return a.d.event.init.call(this,
d,function(){var a={};a[b]=c();return a},f,g,k)}}})("click");a.G=function(){};a.G.prototype.renderTemplateSource=function(){throw Error("Override renderTemplateSource");};a.G.prototype.createJavaScriptEvaluatorBlock=function(){throw Error("Override createJavaScriptEvaluatorBlock");};a.G.prototype.makeTemplateSource=function(b,d){if("string"==typeof b){d=d||v;var c=d.getElementById(b);if(!c)throw Error("Cannot find template with ID "+b);return new a.p.l(c)}if(1==b.nodeType||8==b.nodeType)return new a.p.da(b);
throw Error("Unknown template type: "+b);};a.G.prototype.renderTemplate=function(a,d,c,f){a=this.makeTemplateSource(a,f);return this.renderTemplateSource(a,d,c)};a.G.prototype.isTemplateRewritten=function(a,d){return!1===this.allowTemplateRewriting?!0:this.makeTemplateSource(a,d).data("isRewritten")};a.G.prototype.rewriteTemplate=function(a,d,c){a=this.makeTemplateSource(a,c);d=d(a.text());a.text(d);a.data("isRewritten",!0)};a.b("templateEngine",a.G);a.eb=function(){function b(b,c,d,h){b=a.h.Wa(b);
for(var e=a.h.fa,m=0;m<b.length;m++){var n=b[m].key;if(e.hasOwnProperty(n)){var p=e[n];if("function"===typeof p){if(n=p(b[m].value))throw Error(n);}else if(!p)throw Error("This template engine does not support the '"+n+"' binding within its templates");}}d="ko.__tr_ambtns(function($context,$element){return(function(){return{ "+a.h.xa(b,{valueAccessors:!0})+" } })()},'"+d.toLowerCase()+"')";return h.createJavaScriptEvaluatorBlock(d)+c}var d=/(<([a-z]+\d*)(?:\s+(?!data-bind\s*=\s*)[a-z0-9\-]+(?:=(?:\"[^\"]*\"|\'[^\']*\'))?)*\s+)data-bind\s*=\s*(["'])([\s\S]*?)\3/gi,
c=/\x3c!--\s*ko\b\s*([\s\S]*?)\s*--\x3e/g;return{ec:function(b,c,d){c.isTemplateRewritten(b,d)||c.rewriteTemplate(b,function(b){return a.eb.nc(b,c)},d)},nc:function(a,g){return a.replace(d,function(a,c,d,f,n){return b(n,c,d,g)}).replace(c,function(a,c){return b(c,"\x3c!-- ko --\x3e","#comment",g)})},Xb:function(b,c){return a.D.Ua(function(d,h){var e=d.nextSibling;e&&e.nodeName.toLowerCase()===c&&a.pa(e,b,h)})}}}();a.b("__tr_ambtns",a.eb.Xb);(function(){a.p={};a.p.l=function(a){this.l=a};a.p.l.prototype.text=
function(){var b=a.a.C(this.l),b="script"===b?"text":"textarea"===b?"value":"innerHTML";if(0==arguments.length)return this.l[b];var d=arguments[0];"innerHTML"===b?a.a.$a(this.l,d):this.l[b]=d};var b=a.a.f.N()+"_";a.p.l.prototype.data=function(c){if(1===arguments.length)return a.a.f.get(this.l,b+c);a.a.f.set(this.l,b+c,arguments[1])};var d=a.a.f.N();a.p.da=function(a){this.l=a};a.p.da.prototype=new a.p.l;a.p.da.prototype.text=function(){if(0==arguments.length){var b=a.a.f.get(this.l,d)||{};b.fb===
q&&b.Ha&&(b.fb=b.Ha.innerHTML);return b.fb}a.a.f.set(this.l,d,{fb:arguments[0]})};a.p.l.prototype.nodes=function(){if(0==arguments.length)return(a.a.f.get(this.l,d)||{}).Ha;a.a.f.set(this.l,d,{Ha:arguments[0]})};a.b("templateSources",a.p);a.b("templateSources.domElement",a.p.l);a.b("templateSources.anonymousTemplate",a.p.da)})();(function(){function b(b,c,d){var f;for(c=a.e.nextSibling(c);b&&(f=b)!==c;)b=a.e.nextSibling(f),d(f,b)}function d(c,d){if(c.length){var f=c[0],g=c[c.length-1],k=f.parentNode,
l=a.I.instance,r=l.preprocessNode;if(r){b(f,g,function(a,b){var c=a.previousSibling,d=r.call(l,a);d&&(a===f&&(f=d[0]||b),a===g&&(g=d[d.length-1]||c))});c.length=0;if(!f)return;f===g?c.push(f):(c.push(f,g),a.a.ia(c,k))}b(f,g,function(b){1!==b.nodeType&&8!==b.nodeType||a.ob(d,b)});b(f,g,function(b){1!==b.nodeType&&8!==b.nodeType||a.D.Sb(b,[d])});a.a.ia(c,k)}}function c(a){return a.nodeType?a:0<a.length?a[0]:null}function f(b,e,f,k,p){p=p||{};var l=b&&c(b),l=l&&l.ownerDocument,r=p.templateEngine||g;
a.eb.ec(f,r,l);f=r.renderTemplate(f,k,p,l);if("number"!=typeof f.length||0<f.length&&"number"!=typeof f[0].nodeType)throw Error("Template engine must return an array of DOM nodes");l=!1;switch(e){case "replaceChildren":a.e.S(b,f);l=!0;break;case "replaceNode":a.a.Lb(b,f);l=!0;break;case "ignoreTargetNode":break;default:throw Error("Unknown renderMode: "+e);}l&&(d(f,k),p.afterRender&&a.k.A(p.afterRender,null,[f,k.$data]));return f}var g;a.ab=function(b){if(b!=q&&!(b instanceof a.G))throw Error("templateEngine must inherit from ko.templateEngine");
g=b};a.Ya=function(b,d,k,n,p){k=k||{};if((k.templateEngine||g)==q)throw Error("Set a template engine before calling renderTemplate");p=p||"replaceChildren";if(n){var l=c(n);return a.j(function(){var g=d&&d instanceof a.L?d:new a.L(a.a.c(d)),q=a.B(b)?b():"function"===typeof b?b(g.$data,g):b,g=f(n,p,q,g,k);"replaceNode"==p&&(n=g,l=c(n))},null,{Ja:function(){return!l||!a.a.Ka(l)},q:l&&"replaceNode"==p?l.parentNode:l})}return a.D.Ua(function(c){a.Ya(b,d,k,c,"replaceNode")})};a.uc=function(b,c,g,k,p){function l(a,
b){d(b,y);g.afterRender&&g.afterRender(b,a)}function r(c,d){y=p.createChildContext(c,g.as,function(a){a.$index=d});var e=a.B(b)?b():"function"===typeof b?b(c,y):b;return f(null,"ignoreTargetNode",e,y,g)}var y;return a.j(function(){var b=a.a.c(c)||[];"undefined"==typeof b.length&&(b=[b]);b=a.a.ra(b,function(b){return g.includeDestroyed||b===q||null===b||!a.a.c(b._destroy)});a.k.A(a.a.Za,null,[k,b,r,g,l])},null,{q:k})};var k=a.a.f.N();a.d.template={init:function(b,c){var d=a.a.c(c());"string"==typeof d||
d.name?a.e.ha(b):(d=a.e.childNodes(b),d=a.a.oc(d),(new a.p.da(b)).nodes(d));return{controlsDescendantBindings:!0}},update:function(b,c,d,f,g){var l=c(),r;c=a.a.c(l);d=!0;f=null;"string"==typeof c?c={}:(l=c.name,"if"in c&&(d=a.a.c(c["if"])),d&&"ifnot"in c&&(d=!a.a.c(c.ifnot)),r=a.a.c(c.data));"foreach"in c?f=a.uc(l||b,d&&c.foreach||[],c,b,g):d?(g="data"in c?g.createChildContext(r,c.as):g,f=a.Ya(l||b,g,c,b)):a.e.ha(b);g=f;(r=a.a.f.get(b,k))&&"function"==typeof r.J&&r.J();a.a.f.set(b,k,g&&g.X()?g:q)}};
a.h.fa.template=function(b){b=a.h.Wa(b);return 1==b.length&&b[0].unknown||a.h.lc(b,"name")?null:"This template engine does not support anonymous templates nested within its templates"};a.e.P.template=!0})();a.b("setTemplateEngine",a.ab);a.b("renderTemplate",a.Ya);a.a.vb=function(a,d,c){if(a.length&&d.length){var f,g,k,h,e;for(f=g=0;(!c||f<c)&&(h=a[g]);++g){for(k=0;e=d[k];++k)if(h.value===e.value){h.moved=e.index;e.moved=h.index;d.splice(k,1);f=k=0;break}f+=k}}};a.a.Ga=function(){function b(b,c,f,
g,k){var h=Math.min,e=Math.max,m=[],n,p=b.length,l,r=c.length,q=r-p||1,t=p+r+1,u,s,v;for(n=0;n<=p;n++)for(s=u,m.push(u=[]),v=h(r,n+q),l=e(0,n-1);l<=v;l++)u[l]=l?n?b[n-1]===c[l-1]?s[l-1]:h(s[l]||t,u[l-1]||t)+1:l+1:n+1;h=[];e=[];q=[];n=p;for(l=r;n||l;)r=m[n][l]-1,l&&r===m[n][l-1]?e.push(h[h.length]={status:f,value:c[--l],index:l}):n&&r===m[n-1][l]?q.push(h[h.length]={status:g,value:b[--n],index:n}):(--l,--n,k.sparse||h.push({status:"retained",value:c[l]}));a.a.vb(e,q,10*p);return h.reverse()}return function(a,
c,f){f="boolean"===typeof f?{dontLimitMoves:f}:f||{};a=a||[];c=c||[];return a.length<=c.length?b(a,c,"added","deleted",f):b(c,a,"deleted","added",f)}}();a.b("utils.compareArrays",a.a.Ga);(function(){function b(b,d,g,k,h){var e=[],m=a.j(function(){var m=d(g,h,a.a.ia(e,b))||[];0<e.length&&(a.a.Lb(e,m),k&&a.k.A(k,null,[g,m,h]));e.length=0;a.a.ea(e,m)},null,{q:b,Ja:function(){return!a.a.nb(e)}});return{Y:e,j:m.X()?m:q}}var d=a.a.f.N();a.a.Za=function(c,f,g,k,h){function e(b,d){w=p[d];u!==d&&(z[b]=w);
w.Oa(u++);a.a.ia(w.Y,c);s.push(w);x.push(w)}function m(b,c){if(b)for(var d=0,e=c.length;d<e;d++)c[d]&&a.a.s(c[d].Y,function(a){b(a,d,c[d].qa)})}f=f||[];k=k||{};var n=a.a.f.get(c,d)===q,p=a.a.f.get(c,d)||[],l=a.a.Ea(p,function(a){return a.qa}),r=a.a.Ga(l,f,k.dontLimitMoves),s=[],t=0,u=0,v=[],x=[];f=[];for(var z=[],l=[],w,B=0,D,F;D=r[B];B++)switch(F=D.moved,D.status){case "deleted":F===q&&(w=p[t],w.j&&w.j.J(),v.push.apply(v,a.a.ia(w.Y,c)),k.beforeRemove&&(f[B]=w,x.push(w)));t++;break;case "retained":e(B,
t++);break;case "added":F!==q?e(B,F):(w={qa:D.value,Oa:a.n(u++)},s.push(w),x.push(w),n||(l[B]=w))}m(k.beforeMove,z);a.a.s(v,k.beforeRemove?a.Q:a.removeNode);for(var B=0,n=a.e.firstChild(c),G;w=x[B];B++){w.Y||a.a.extend(w,b(c,g,w.qa,h,w.Oa));for(t=0;r=w.Y[t];n=r.nextSibling,G=r,t++)r!==n&&a.e.Ab(c,r,G);!w.ic&&h&&(h(w.qa,w.Y,w.Oa),w.ic=!0)}m(k.beforeRemove,f);m(k.afterMove,z);m(k.afterAdd,l);a.a.f.set(c,d,s)}})();a.b("utils.setDomNodeChildrenFromArrayMapping",a.a.Za);a.M=function(){this.allowTemplateRewriting=
!1};a.M.prototype=new a.G;a.M.prototype.renderTemplateSource=function(b){var d=(9>a.a.ka?0:b.nodes)?b.nodes():null;if(d)return a.a.R(d.cloneNode(!0).childNodes);b=b.text();return a.a.wa(b)};a.M.Pa=new a.M;a.ab(a.M.Pa);a.b("nativeTemplateEngine",a.M);(function(){a.Sa=function(){var a=this.kc=function(){if(!s||!s.tmpl)return 0;try{if(0<=s.tmpl.tag.tmpl.open.toString().indexOf("__"))return 2}catch(a){}return 1}();this.renderTemplateSource=function(b,f,g){g=g||{};if(2>a)throw Error("Your version of jQuery.tmpl is too old. Please upgrade to jQuery.tmpl 1.0.0pre or later.");
var k=b.data("precompiled");k||(k=b.text()||"",k=s.template(null,"{{ko_with $item.koBindingContext}}"+k+"{{/ko_with}}"),b.data("precompiled",k));b=[f.$data];f=s.extend({koBindingContext:f},g.templateOptions);f=s.tmpl(k,b,f);f.appendTo(v.createElement("div"));s.fragments={};return f};this.createJavaScriptEvaluatorBlock=function(a){return"{{ko_code ((function() { return "+a+" })()) }}"};this.addTemplate=function(a,b){v.write("<script type='text/html' id='"+a+"'>"+b+"\x3c/script>")};0<a&&(s.tmpl.tag.ko_code=
{open:"__.push($1 || '');"},s.tmpl.tag.ko_with={open:"with($1) {",close:"} "})};a.Sa.prototype=new a.G;var b=new a.Sa;0<b.kc&&a.ab(b);a.b("jqueryTmplTemplateEngine",a.Sa)})()})})();})();
